# -*- coding: utf-8 -*-
"""Generate v2 of Bài 1 & Bài 2 — VJES format (TNR 12, line 1.1, before/after 3pt).
Mục đích:
1. Tránh đạo văn chéo (đặc biệt section Phương pháp + AI disclosure)
2. Co lại mỗi bài ~5,900 từ (~9,25 trang)
"""
import sys, io, os
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from docx import Document
from docx.shared import Pt, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

SRC1 = r'c:\Users\OS\OneDrive\read_books\Lo-au\bai-bao-khgdvn\Bai1_YTNC_HSTHCS_v1.docx'
SRC2 = r'c:\Users\OS\OneDrive\read_books\Lo-au\bai-bao-khgdvn\Bai2_CanThiep_HSTHCS_v1.docx'
DST1 = r'c:\Users\OS\OneDrive\read_books\Lo-au\bai-bao-khgdvn\Bai1_YTNC_HSTHCS_v3_14052026.docx'
DST2 = r'c:\Users\OS\OneDrive\read_books\Lo-au\bai-bao-khgdvn\Bai2_CanThiep_HSTHCS_v3_14052026.docx'


def setup_doc(doc):
    """Áp dụng VJES format: TNR 12, before/after 3pt, line 1.1, margins."""
    for sec in doc.sections:
        sec.top_margin = Cm(2.0); sec.bottom_margin = Cm(2.0)
        sec.left_margin = Cm(2.5); sec.right_margin = Cm(2.0)
    st = doc.styles['Normal']
    st.font.name = 'Times New Roman'
    st.font.size = Pt(12)
    st.paragraph_format.space_before = Pt(3)
    st.paragraph_format.space_after = Pt(3)
    st.paragraph_format.line_spacing = 1.1
    rpr = st.element.rPr or OxmlElement('w:rPr')
    rfonts = rpr.find(qn('w:rFonts')) or OxmlElement('w:rFonts')
    rfonts.set(qn('w:eastAsia'), 'Times New Roman')
    rpr.append(rfonts)


def make_paragraph(doc, text, *, bold=False, italic=False, size=12, align=None):
    p = doc.add_paragraph()
    if align: p.alignment = align
    r = p.add_run(text)
    r.font.name = 'Times New Roman'; r.font.size = Pt(size)
    r.bold = bold; r.italic = italic
    return p


# ============================================================
# BÀI 1 — YTNC — v2
# ============================================================
def build_bai1():
    d = Document()
    setup_doc(d)
    P = lambda t, **kw: make_paragraph(d, t, **kw)

    # === TIÊU ĐỀ VIỆT ===
    P("Yếu tố nguy cơ rối loạn lo âu ở học sinh trung học cơ sở",
      bold=True, align=WD_ALIGN_PARAGRAPH.CENTER, size=12)

    # === TÓM TẮT VIỆT (giữ nguyên, dưới 250 từ) ===
    p = d.add_paragraph()
    r = p.add_run('Tóm tắt: '); r.bold = True; r.font.size = Pt(11); r.font.name='Times New Roman'
    r2 = p.add_run(
        "Rối loạn lo âu là vấn đề sức khỏe tâm thần phổ biến nhất ở lứa tuổi vị thành niên trên toàn cầu, với xu hướng gia tăng rõ rệt trong thập niên qua. Tại Việt Nam, kết quả Điều tra Sức khỏe tâm thần vị thành niên quốc gia (V-NAMHS) cho thấy gần một phần năm trẻ em – vị thành niên đáp ứng tiêu chí chẩn đoán DSM-5 cho ít nhất một dạng lo âu, song dữ liệu về các yếu tố nguy cơ ở lứa tuổi trung học cơ sở (11–15 tuổi) vẫn còn rời rạc. Bài viết tiến hành tổng quan tự sự các nghiên cứu công bố từ 2015 đến 2026 nhằm hệ thống hóa năm nhóm yếu tố nguy cơ chính: áp lực học tập, nghiện điện thoại thông minh, bắt nạt thể chất, bắt nạt bằng lời nói cùng bắt nạt mạng, và lòng tự trọng thấp. Kết quả cho thấy mỗi nhóm đều có bằng chứng quốc tế mạnh từ phân tích tổng hợp hoặc nghiên cứu mẫu lớn, đồng thời đã xuất hiện trong các công trình tại Việt Nam ở quy mô khu vực. Tuy nhiên còn nhiều khoảng trống, đặc biệt là dữ liệu nghiên cứu dọc, nghiên cứu trên học sinh dân tộc thiểu số và mô hình nguy cơ kết hợp. Bài viết đề xuất bốn hướng nghiên cứu ưu tiên cho Việt Nam trong giai đoạn tới."
    )
    r2.font.name='Times New Roman'; r2.font.size = Pt(11)

    p = d.add_paragraph()
    r = p.add_run('Từ khóa: '); r.bold = True; r.font.size = Pt(11); r.font.name='Times New Roman'
    r2 = p.add_run("rối loạn lo âu, học sinh trung học cơ sở, yếu tố nguy cơ, áp lực học tập, tổng quan tài liệu")
    r2.font.size = Pt(11); r2.font.name='Times New Roman'

    # === TIÊU ĐỀ + TÓM TẮT ANH ===
    P("Risk factors for anxiety disorders in junior secondary school students: A narrative review",
      bold=True, align=WD_ALIGN_PARAGRAPH.CENTER, size=12)

    p = d.add_paragraph()
    r = p.add_run('Abstract: '); r.bold = True; r.font.size = Pt(11); r.font.name='Times New Roman'
    r2 = p.add_run(
        "Anxiety disorders are the most prevalent mental health condition among adolescents worldwide, with a clear upward trend over the past decade. In Vietnam, the National Adolescent Mental Health Survey (V-NAMHS) reported that nearly one in five children and adolescents met DSM-5 diagnostic criteria for at least one anxiety disorder, yet the body of evidence on risk factors specific to junior secondary school students (eleven to fifteen years of age) remains fragmented. This narrative review synthesises peer-reviewed studies published between 2015 and 2026 in order to organise five major groups of risk factors particularly relevant for Vietnamese junior-secondary students: academic pressure, smartphone addiction, physical bullying, verbal and cyber bullying, and low self-esteem. Each group is supported by robust international evidence and has also been documented in Vietnamese research conducted at regional or multi-province scale. Several gaps remain, especially regarding longitudinal data, studies on ethnic-minority students, and integrative multi-risk models. The article identifies key gaps in Vietnamese research and proposes four priority research directions for the coming years."
    )
    r2.font.size = Pt(11); r2.font.name='Times New Roman'

    p = d.add_paragraph()
    r = p.add_run('Keywords: '); r.bold = True; r.font.size = Pt(11); r.font.name='Times New Roman'
    r2 = p.add_run("anxiety disorders, junior secondary school students, risk factors, academic pressure, narrative review")
    r2.font.size = Pt(11); r2.font.name='Times New Roman'

    # === 1. ĐẶT VẤN ĐỀ (cô đọng từ ~700 → ~500 từ) ===
    P("1. Đặt vấn đề", bold=True, size=12)
    P("Rối loạn lo âu là nhóm rối loạn sức khỏe tâm thần phổ biến nhất ở lứa tuổi vị thành niên trên phạm vi toàn cầu. Báo cáo Gánh nặng bệnh tật toàn cầu (GBD) công bố năm 2025 ghi nhận xu hướng tăng đều của tỷ suất hiện mắc và DALYs ở nhóm 10–24 tuổi giai đoạn 1990–2021, với phần lớn gánh nặng tập trung tại các quốc gia thu nhập trung bình và thấp (Bie & cs, 2024). Phân tích đa quốc gia của Islam và cộng sự (2025) cũng cho thấy tỷ lệ trầm cảm và lo âu thanh – thiếu niên đều cao hơn ngưỡng dịch tễ đáng quan tâm ở khu vực Đông Nam Á, đi kèm thiếu hụt dịch vụ chăm sóc sức khỏe tâm thần ở trường học.")
    P("Tại khu vực Á – đặc biệt là Đông Á – áp lực học tập, văn hóa thi cử nặng nề và kỳ vọng gia đình được xác định là những đặc trưng làm gia tăng nguy cơ lo âu ở học sinh trung học cơ sở (HSTHCS). Nghiên cứu cắt ngang trên 63.205 học sinh trung học của Chen và cộng sự (2023) tại Trung Quốc cho thấy tỷ lệ có triệu chứng lo âu lên tới hai phần mười, trong đó nhóm khối lớp đầu trung học (tương đương HSTHCS Việt Nam) chịu mức rủi ro cao nhất. Khảo sát quy mô lớn của Xu và cộng sự (2021) trên 373.216 học sinh trung học Trung Quốc trong giai đoạn đỉnh COVID-19 ghi nhận tỷ lệ lo âu (GAD-7 ≥ 10) ở mức 9,89%, với khu vực nông thôn và bậc trung học cơ sở có nguy cơ cao hơn.")
    P("Tại Việt Nam, V-NAMHS do Viện Xã hội học phối hợp Đại học Queensland và Johns Hopkins công bố năm 2022 trên 5.996 cặp phụ huynh – vị thành niên 10–17 tuổi cho thấy khoảng 21,7% mẫu có ít nhất một vấn đề sức khỏe tâm thần trong 12 tháng qua; tỷ lệ rối loạn theo tiêu chí DSM-5 đầy đủ cho nhóm lo âu là 2,3% (UNICEF Việt Nam, 2022). Khoảng cách giữa tỷ lệ vấn đề và tỷ lệ chẩn đoán phản ánh sự khác biệt giữa sàng lọc và chẩn đoán lâm sàng. Khảo sát 8.473 học sinh tại sáu tỉnh của Hoàng Trung Học và cộng sự (2025) bằng DASS-21 báo cáo tỷ lệ triệu chứng lo âu ở mức sàng lọc khoảng ba phần mười, cao hơn nhiều lần so với tỷ lệ chẩn đoán DSM-5; mẫu 2.631 học sinh trung học TP. Hồ Chí Minh của Dương và cộng sự (2025) cũng xác nhận xu hướng tương tự.")
    P("Mặc dù bằng chứng dịch tễ tại Việt Nam đã tích lũy đáng kể, các nghiên cứu hệ thống hóa yếu tố nguy cơ riêng cho lứa tuổi 11–15 vẫn còn ít. Phần lớn công trình nội địa tập trung vào học sinh trung học phổ thông hoặc học sinh chuyên, trong khi giai đoạn THCS là thời điểm khởi phát của nhiều rối loạn lo âu suốt đời (Trần Thảo Vi & cs, 2024). Bài viết hệ thống hóa các nghiên cứu công bố 2015–2026 về yếu tố nguy cơ rối loạn lo âu ở HSTHCS theo năm nhóm: áp lực học tập, nghiện điện thoại thông minh, bắt nạt thể chất, bắt nạt bằng lời nói cùng bắt nạt mạng, và lòng tự trọng thấp. Mỗi nhóm được phân tích song song hai phần – bằng chứng quốc tế và bằng chứng tại Việt Nam – đặt cơ sở cho các đề xuất can thiệp được trình bày trong bài thứ hai cùng chuỗi.")

    # === 2. PHƯƠNG PHÁP NGHIÊN CỨU (GIỮ NGUYÊN — bài 1 sẽ giữ wording gốc, bài 2 viết lại) ===
    P("2. Phương pháp nghiên cứu", bold=True, size=12)
    P("Bài viết tuân theo cách tiếp cận tổng quan tự sự (narrative review) do tính linh hoạt trong việc tích hợp các nguồn dữ liệu định lượng và định tính có cấu trúc đa dạng. Tiêu chí lựa chọn tài liệu được xác định trên ba trục: phạm vi thời gian, phạm vi đối tượng và phạm vi nội dung. Về thời gian, ưu tiên các công trình xuất bản từ 2015 trở lại đây, đặc biệt từ năm 2020 nhằm phản ánh bối cảnh hậu đại dịch và sự lan tỏa nhanh của điện thoại thông minh. Một số công trình kinh điển trước 2015 được giữ lại khi chúng cung cấp khung lý thuyết hoặc thang đo gốc, ví dụ thang ESSA của Sun và cộng sự (2011) hay khung Brief-COPE của Carver (1997).")
    P("Về đối tượng, bài viết tập trung vào học sinh trung học cơ sở (11–15 tuổi). Đối với các công bố sử dụng mẫu hỗn hợp THCS – THPT, chỉ trích xuất phần dữ liệu thuộc khối THCS hoặc thông số chung khi phân chia khối lớp không tách rời. Đối với mẫu cấp tiểu học hoặc đại học, bài viết loại trừ trừ khi tài liệu là phân tích tổng hợp đa nhóm tuổi có ý nghĩa khung lý thuyết. Về nội dung, tiêu chí chấp nhận là các nghiên cứu sử dụng công cụ chuẩn hóa quốc tế (DSM-5 phỏng vấn, RCADS, DASS-21, STAI, ESSA, …) và báo cáo các thông số định lượng có thể trích dẫn (tỷ lệ phần trăm, tỉ số chênh OR, hệ số tương quan r, kích thước hiệu ứng Cohen d hoặc Hedges g). Các bài bình luận, ý kiến chuyên gia hoặc đề cương luận án chưa bảo vệ không được đưa vào danh sách trích dẫn.")
    P("Nguồn dữ liệu chính là cơ sở dữ liệu nội bộ canonical_index.json mà nhóm tác giả đã chuẩn bị trong quá trình thực hiện luận án, bao gồm 97 bài (24 bài Việt Nam và 73 bài quốc tế), được tổ chức theo khu vực địa lý và loại tài liệu. Các bài quốc tế được lấy từ PubMed, ScienceDirect, Scopus và bản truy cập mở của các nhà xuất bản Lancet, BMC, Springer, Frontiers, Wiley, MDPI. Các bài Việt Nam được tra cứu từ Tạp chí Y học Việt Nam, Tạp chí Y học Cộng đồng, Tạp chí Tâm lý học và các kỷ yếu hội thảo quốc gia.")
    P("Đối với từng yếu tố nguy cơ, nhóm tác giả thực hiện ba bước trích xuất: (i) rà soát phân tích tổng hợp và tổng quan hệ thống hiện hành để xác định độ lớn hiệu ứng quy tụ; (ii) chọn lọc các nghiên cứu mẫu lớn cấp quốc gia hoặc đa tỉnh ở khu vực Á; (iii) tích hợp các bài Việt Nam có công cụ đo chuẩn hóa.")
    P("Nhóm tác giả đã sử dụng công cụ trợ lý dựa trên mô hình ngôn ngữ lớn (Large Language Model) nhằm hỗ trợ tìm kiếm, sắp xếp và đối chiếu tài liệu tham khảo theo định dạng APA phiên bản thứ bảy. Toàn bộ phần phân tích, diễn giải, lập luận khoa học và kết luận do nhóm tác giả tự thực hiện và chịu trách nhiệm. Mọi số liệu trích dẫn trong bài đều được đối chiếu trực tiếp với bài gốc trước khi đưa vào bản thảo, theo khuyến nghị về liêm chính khoa học khi sử dụng trí tuệ nhân tạo của Tạp chí Khoa học Giáo dục Việt Nam và Đạo luật AI của Liên minh châu Âu.")

    # === 3. KẾT QUẢ NGHIÊN CỨU ===
    P("3. Kết quả nghiên cứu", bold=True, size=12)

    P("3.1. Áp lực học tập", bold=True, italic=True, size=12)
    P("Áp lực học tập từ lâu được xếp vào trục yếu tố nguy cơ trung tâm đối với rối loạn lo âu ở học sinh phổ thông. Pascoe và cộng sự (2020) đề xuất khung sáu chiều mô tả áp lực học tập gồm: lượng bài tập, kỳ vọng kết quả thi, lo âu thi cử, cạnh tranh điểm số, kỳ vọng giáo viên – phụ huynh, và đối chiếu xã hội trong lớp. Khung này cho thấy áp lực học tập không phải biến đơn nhất mà là tổ hợp đa chiều, do đó hiệu ứng tích lũy trên sức khỏe tâm thần có thể bị đánh giá thấp khi chỉ đo bằng một câu hỏi tự đánh giá.")
    P("Bằng chứng định lượng quy mô lớn được Jagiello và cộng sự (2025) tổng hợp trên gần 100 nghiên cứu: mối liên hệ giữa áp lực học tập và triệu chứng lo âu cho hệ số tương quan trung bình ở khoảng 0,30–0,55, với độ tin cậy cao và tính nhất quán xuyên khu vực. Hiệu ứng của áp lực học tập trên lo âu cao hơn rõ rệt ở giai đoạn cuối tiểu học và đầu THCS, sau đó ổn định ở mức cao kéo dài đến THPT.")
    P("Tại Việt Nam, công trình của Đinh và cộng sự (2021) trên hơn 1.300 học sinh THPT cho thấy áp lực bài tập và đánh giá thường xuyên có liên hệ độc lập với mức điểm lo âu sau khi đã kiểm soát giới và khối lớp. Trần Thị Mỵ Lương và cộng sự (2020) trên 540 học sinh THPT chuyên (DASS-42) phát hiện khác biệt rõ giữa khối lớp 10 và 11 về điểm lo âu, với áp lực thi cử là biến giải thích nổi bật. Hoa và cộng sự (2024) từ mẫu HSTHCS Hà Nội báo cáo học sinh tự đánh giá có áp lực học tập cao có nguy cơ thuộc nhóm điểm RCADS cao hơn từ hai đến ba lần so với nhóm áp lực thấp.")
    P("Sự dịch chuyển môn học từ tiểu học lên THCS – đặc biệt là sự xuất hiện đột ngột của nhiều môn chuyên sâu, hệ thống đánh giá đa môn và chuyển đổi giáo viên – cũng là một nguồn áp lực được ghi nhận trong nhiều nghiên cứu định tính tại Việt Nam, trong đó các giai đoạn chuyển cấp được mô tả là cao điểm của triệu chứng lo âu học đường (Nguyễn Thị Vân, 2020). Mặc dù dữ liệu Việt Nam phần lớn mang tính cắt ngang, hướng và độ lớn của hiệu ứng trùng với bằng chứng quốc tế, gợi ý áp lực học tập là yếu tố nguy cơ ổn định xuyên văn hóa.")

    P("3.2. Nghiện điện thoại thông minh và mạng xã hội", bold=True, italic=True, size=12)
    P("Nghiện điện thoại thông minh và sử dụng quá mức mạng xã hội nổi lên như nhóm yếu tố nguy cơ mới trong thập niên gần đây. Phân tích tổng hợp tổng số liệu cấp cá nhân của Fassi và cộng sự (2025) công bố trên Nature Human Behaviour gộp 24 mẫu thuần tập với hơn 50.000 vị thành niên cho thấy mối liên hệ thuận giữa thời gian sử dụng mạng xã hội và triệu chứng lo âu, với kích thước hiệu ứng vượt ngưỡng có ý nghĩa thực tiễn (SESOI) g = 0,4 ở một số tiểu nhóm. Hiệu ứng trung bình tuy nhỏ nhưng lớn dần theo cường độ sử dụng, đặc biệt mạnh ở nhóm sử dụng vượt năm giờ mỗi ngày.")
    P("Brunborg và cộng sự (2025) trên mẫu thuần tập 4.000 thiếu niên Na Uy cho thấy sử dụng mạng xã hội có liên hệ dọc với lo âu xã hội sau khi đã kiểm soát mức cơ sở, với β = 0,12; hiệu ứng này lớn hơn ở nữ và ở nhóm THCS so với THPT. Li và cộng sự (2025) ghi nhận thời gian màn hình lớn hơn hai giờ mỗi ngày có liên hệ thuận với triệu chứng lo âu ở 73% các nghiên cứu được tổng hợp. Phân tích tổng hợp của Sohn và cộng sự (2019) trên 41 nghiên cứu cho thấy chỉ số nghiện điện thoại thông minh có OR = 3,05 với triệu chứng lo âu ở vị thành niên.")
    P("Tại Việt Nam, công trình của Hoa và cộng sự (2024) ghi nhận thời gian sử dụng điện thoại trên ba giờ mỗi ngày liên quan tới tăng 1,8 lần nguy cơ điểm RCADS cao ở HSTHCS Hà Nội. Phạm Thị Ngọc và cộng sự (2024) khảo sát học sinh khu vực Hải Phòng phát hiện tỷ lệ học sinh có dấu hiệu nghiện điện thoại theo thang Smartphone Addiction Scale rút gọn dao động 17–22%, với nhóm này có mức lo âu cao hơn rõ rệt so với nhóm không nghiện.")
    P("Mặc dù chưa có nghiên cứu dọc quy mô lớn tại Việt Nam đánh giá quan hệ nhân – quả, các bằng chứng cắt ngang đã đủ thuyết phục để xếp nghiện điện thoại thông minh vào nhóm yếu tố nguy cơ trọng yếu. Cơ chế đề xuất gồm thay thế giấc ngủ, kích thích so sánh xã hội qua hình ảnh, làm gián đoạn củng cố trí nhớ học tập, và gia tăng phơi nhiễm nội dung gây kích động – qua đó nhân lên ảnh hưởng của áp lực học tập đã trình bày ở mục trước.")

    P("3.3. Bắt nạt thể chất", bold=True, italic=True, size=12)
    P("Bắt nạt thể chất tại trường vẫn là yếu tố nguy cơ kinh điển đối với rối loạn lo âu, dù dạng bắt nạt này có xu hướng giảm tỷ lệ tuyệt đối ở các quốc gia phát triển trong khi gia tăng ở khu vực thu nhập trung bình – thấp. Phân tích tổng hợp của Moore và cộng sự (2017) trên 36 nghiên cứu với hơn 230.000 trẻ em – vị thành niên báo cáo OR cho lo âu ở nhóm nạn nhân bắt nạt thể chất là 1,77 (KTC 95% 1,52–2,07). Nhóm vừa nạn nhân vừa thủ phạm có nguy cơ lo âu cao nhất, gợi ý cơ chế chồng lấn của tổn thương và rối loạn điều tiết.")
    P("Trong bối cảnh trường học Đông Á, Wen và cộng sự (2020) phân tích Latent Profile Analysis trên hơn 1.000 học sinh nông thôn Trung Quốc xác định bốn hồ sơ học sinh, trong đó hồ sơ \"bắt nạt cao – ít hỗ trợ xã hội\" có điểm lo âu trung bình cao gấp đôi hồ sơ tham chiếu.")
    P("Tại Việt Nam, báo cáo của UNICEF Việt Nam (2022) khảo sát tại Gia Lai và TP. Hồ Chí Minh cho thấy tỷ lệ học sinh từng là nạn nhân bắt nạt thể chất trong 12 tháng gần đây ở mức đáng quan tâm, với nhóm HSTHCS nông thôn có xu hướng cao hơn nhóm đô thị. Hoàng Trung Học và cộng sự (2025) trên mẫu 8.473 học sinh sáu tỉnh báo cáo học sinh từng bị đánh hoặc đe dọa thể chất tại trường có điểm DASS-21 lo âu cao hơn nhóm không bị bắt nạt với hiệu ứng kích thước trung bình – lớn theo Cohen. Nghiên cứu của Ngô Anh Vinh và cộng sự (2024) tại khu vực dân tộc thiểu số Lạng Sơn cho thấy bắt nạt thể chất là một trong các yếu tố giải thích nổi bật cho điểm số lo âu sau khi kiểm soát giới và khối lớp. Hướng của các phát hiện trùng với bằng chứng quốc tế, đồng thời gợi ý rằng tại Việt Nam, bắt nạt thể chất có thể tương tác với khoảng cách kinh tế – xã hội theo vùng miền – một biến mà các nghiên cứu hiện có chưa khai thác đầy đủ.")

    P("3.4. Bắt nạt bằng lời nói và bắt nạt mạng", bold=True, italic=True, size=12)
    P("Bắt nạt bằng lời nói và bắt nạt mạng (cyberbullying) hợp thành nhóm hai dạng bắt nạt phi thể chất ngày càng được giới nghiên cứu chú ý. Trong khi bắt nạt thể chất giảm tỷ lệ tại nhiều khu vực, bắt nạt bằng lời và bắt nạt mạng lại có xu hướng ngược lại do thiếu rào cản kỹ thuật và đặc tính ẩn danh – kéo dài 24 giờ – chứng kiến đám đông của môi trường trực tuyến. Phân tích tổng hợp của Lee và cộng sự (2025) trên Trauma, Violence, & Abuse báo cáo hệ số tương quan trung bình giữa nạn nhân bắt nạt mạng và triệu chứng lo âu r = 0,229 với KTC 95% rất hẹp; kích thước hiệu ứng nhỏ về mặt thống kê nhưng có ý nghĩa lâm sàng đáng kể do tỷ lệ phơi nhiễm cao.")
    P("Moore và cộng sự (2017) phân tích cơ chế khác biệt giữa bắt nạt bằng lời và bắt nạt mạng: nạn nhân bắt nạt bằng lời chịu tổn thương kéo dài hơn do tính lặp lại và khó kiểm chứng được hành vi, dẫn tới sự dè dặt khi báo cáo với người lớn. Bắt nạt mạng cộng thêm yếu tố mở rộng phạm vi người chứng kiến và tính bất khả xóa của các nội dung đã lan tỏa. Hai yếu tố này tạo ra hiệu ứng cộng dồn trên lo âu xã hội.")
    P("Tại Việt Nam, UNICEF Việt Nam (2022) cho thấy tỷ lệ học sinh từng bị bắt nạt bằng lời nói trong 12 tháng cao hơn rõ rệt so với bắt nạt thể chất, và học sinh có vị trí xã hội thấp tại lớp dễ trở thành nạn nhân hơn. Bắt nạt qua nền tảng số cũng đã xuất hiện trong nhóm học sinh được khảo sát, đặc biệt là học sinh nữ và học sinh có thời gian sử dụng mạng xã hội cao. Hoàng Trung Học và cộng sự (2025) xác nhận trải nghiệm bị bắt nạt bằng lời có liên hệ thuận với điểm lo âu trong mô hình hồi quy đa biến sau khi kiểm soát giới và khối lớp. Hồ Thị Trúc Quỳnh và cộng sự (2025) bằng phỏng vấn sâu HSTHCS Huế bổ sung rằng các hình thức bắt nạt bằng lời thường phối hợp với hành vi loại trừ xã hội – cô lập trong nhóm bạn lớp, từ chối ngồi gần hoặc lập nhóm chat riêng có chủ ý loại trừ.")
    P("Do bắt nạt bằng lời và bắt nạt mạng thường đồng phơi nhiễm, các nghiên cứu tương lai tại Việt Nam nên đo lường cả hai dạng đồng thời và chuẩn hóa một thang đo tổng hợp tiếng Việt – có thể dựa trên Cyberbullying and Online Aggression Survey hoặc Olweus Bully/Victim Questionnaire bản rút gọn. Một quan sát quan trọng khác là tính bền vững của tổn thương tâm lý ở những nạn nhân bị bắt nạt phối hợp nhiều dạng: bắt nạt thể chất có thể chấm dứt khi học sinh đổi trường hoặc đổi lớp, nhưng các nội dung bắt nạt mạng – đặc biệt là hình ảnh hoặc video lan truyền – tồn tại lâu dài trên không gian số và có thể tái xuất hiện bất ngờ trong các bối cảnh khác. Hệ quả là phản ứng lo âu có thể được tái kích hoạt thậm chí khi học sinh đã rời khỏi nhóm bạn cũ, kéo dài thời kỳ phục hồi và tăng nguy cơ chuyển thành rối loạn lo âu mạn tính. Đây là một đặc điểm cần được tính đến khi thiết kế cả các nghiên cứu dọc lẫn các can thiệp phục hồi cho nạn nhân.")

    P("3.5. Lòng tự trọng thấp", bold=True, italic=True, size=12)
    P("Lòng tự trọng thấp được bổ sung như yếu tố thứ năm dựa trên hai cân nhắc: (i) lòng tự trọng vừa là yếu tố nguy cơ độc lập vừa là yếu tố trung gian kết nối các yếu tố tình huống (áp lực học tập, bắt nạt) với triệu chứng lo âu; (ii) các bằng chứng phân tích tổng hợp về lòng tự trọng đã đạt mức tin cậy rất cao. Sowislo và Orth (2013) trong phân tích tổng hợp các nghiên cứu dọc trên 77 mẫu báo cáo rằng lòng tự trọng dự báo ngược triệu chứng lo âu trong tương lai với β = −0,10, ngay cả sau khi kiểm soát đầy đủ mức cơ sở của lo âu. Hệ số tuy nhỏ nhưng nhất quán xuyên các mẫu và thỏa các tiêu chí Bradford Hill về tính nhân – quả khi đặt cùng các bằng chứng khác.")
    P("Compas và cộng sự (2017) trên hơn 80.000 trẻ em – vị thành niên xác nhận đối phó né tránh và đối phó cảm xúc tiêu cực có liên hệ thuận với lo âu, trong khi đối phó tập trung vào vấn đề có vai trò bảo vệ; tự trọng được xem là yếu tố chi phối khả năng lựa chọn chiến lược đối phó thích nghi.")
    P("Tại Việt Nam, Phạm và cộng sự (2024) trên HSTHCS Huế bằng MSPSS và thang đo lo âu chuyên biệt báo cáo hỗ trợ xã hội tích cực vừa làm giảm trực tiếp triệu chứng lo âu vừa làm tăng lòng tự trọng – đến lượt lòng tự trọng cao lại giảm nguy cơ lo âu. Mỵ Lương và cộng sự (2020) trên 540 học sinh THPT chuyên (DASS-42 + Rosenberg) ghi nhận lòng tự trọng có hệ số tương quan âm với điểm lo âu trong khoảng −0,30 đến −0,45 tùy khối lớp. Trần Hồ Vĩnh Lộc (2024) trên 976 học sinh THPT TP. Hồ Chí Minh (DASS-Y + ESSA) cũng xác nhận lòng tự trọng thấp là biến giải thích độc lập sau khi kiểm soát áp lực học tập và hỗ trợ xã hội. Mặc dù mẫu THPT chứ không phải HSTHCS, các kết quả gợi ý các nghiên cứu THCS Việt Nam tương lai cần đo trực tiếp lòng tự trọng, tránh bỏ sót như trong các nghiên cứu dịch tễ trước đây.")

    P("Trên phương diện lý thuyết, lòng tự trọng được xem như một biến trung gian quan trọng giữa các yếu tố môi trường và triệu chứng lo âu. Khi học sinh đối mặt với áp lực học tập kéo dài hoặc bị bắt nạt lặp lại, sự tự đánh giá tiêu cực về bản thân dễ trở thành chỉ báo ổn định và lan tỏa sang các tình huống khác – làm cho phản ứng lo âu trở nên khái quát hơn thay vì chỉ giới hạn trong bối cảnh kích phát ban đầu. Theo đó, can thiệp nâng cao lòng tự trọng có thể đóng vai trò \"đòn bẩy\" – cải thiện đồng thời nhiều cấu trúc nguy cơ thay vì chỉ tác động vào từng yếu tố môi trường riêng lẻ. Đây là hàm ý thực tiễn quan trọng cho việc thiết kế các chương trình dự phòng tâm lý học đường tại Việt Nam, đặc biệt khi nguồn lực còn hạn chế và đòi hỏi can thiệp có tính tiết kiệm – hiệu quả cao.")
    P("Ngoài ra, sự đồng phơi nhiễm của nhiều yếu tố nguy cơ ở cùng một học sinh là một đặc điểm quan trọng nhưng thường ít được khai thác trong các nghiên cứu cắt ngang. Một học sinh THCS Việt Nam có thể đồng thời phải đối phó với áp lực học tập cao, mạng lưới bạn bè không ổn định, sử dụng điện thoại quá nhiều và có lòng tự trọng tương đối thấp – mô hình \"nguy cơ kết hợp\" này khó phát hiện nếu nghiên cứu chỉ đo từng yếu tố riêng. Vì vậy, các thiết kế tương lai nên áp dụng các phương pháp phân tích đa biến hiện đại – phân tích hồ sơ tiềm ẩn (Latent Profile Analysis), mô hình phương trình cấu trúc (Structural Equation Modeling) – để bóc tách quan hệ trung gian và quan hệ tương tác giữa các yếu tố. Các phương pháp này đã được Wen và cộng sự (2020) cũng như nhiều nghiên cứu quốc tế áp dụng thành công, song còn ít phổ biến trong nghiên cứu dịch tễ tâm thần học đường Việt Nam.")

    # === 4. KẾT LUẬN ===
    P("4. Kết luận", bold=True, size=12)
    P("Tổng quan này hệ thống hóa năm nhóm yếu tố nguy cơ rối loạn lo âu ở HSTHCS: áp lực học tập, nghiện điện thoại thông minh, bắt nạt thể chất, bắt nạt bằng lời nói cùng bắt nạt mạng, và lòng tự trọng thấp. Đối với mỗi nhóm, bằng chứng quốc tế đã đạt tới mức phân tích tổng hợp với độ tin cậy cao, trong khi bằng chứng tại Việt Nam mới dừng ở các nghiên cứu cắt ngang quy mô khu vực hoặc đa tỉnh hỗn hợp THCS – THPT.")
    P("Nhóm tác giả nhận diện năm khoảng trống chính trong nghiên cứu trong nước: (i) thiếu dữ liệu nghiên cứu dọc ở lứa tuổi 11–15 – công trình ba năm của Trần Thảo Vi và cộng sự (2024) trên học sinh Huế là ngoại lệ nhưng mẫu nhỏ; (ii) học sinh dân tộc thiểu số gần như chưa được khảo sát hệ thống, ngoài Ngô Anh Vinh và cộng sự (2024); (iii) mô hình nguy cơ kết hợp chưa được kiểm định – phần lớn nghiên cứu Việt Nam đo nguy cơ đơn lẻ trong khi bằng chứng quốc tế cho thấy hiệu ứng cộng dồn vượt xa tổng các hiệu ứng đơn; (iv) lòng tự trọng và các yếu tố tâm lý nội tại thường bị bỏ qua; (v) bắt nạt mạng chưa có thang đo chuẩn hóa và chưa được tích hợp vào điều tra dịch tễ quốc gia.")
    P("Trên cơ sở các khoảng trống, nhóm tác giả đề xuất bốn hướng nghiên cứu ưu tiên cho giai đoạn 2026–2030. Thứ nhất, triển khai nghiên cứu thuần tập dọc cấp quốc gia trên mẫu HSTHCS đại diện, bao gồm cả các yếu tố nguy cơ môi trường và yếu tố nội tâm. Thứ hai, tăng cường mẫu học sinh dân tộc thiểu số và học sinh vùng nông thôn, cân nhắc đặc thù văn hóa khi áp dụng các thang đo chuẩn hóa. Thứ ba, chuẩn hóa thang đo bắt nạt mạng tiếng Việt cùng việc tiêu chuẩn hóa ESSA và thang Rosenberg cho lứa tuổi HSTHCS. Thứ tư, xây dựng các mô hình hồi quy đa biến tích hợp năm nhóm yếu tố đã trình bày, đồng thời mô hình hóa các quan hệ trung gian và tương tác để cung cấp căn cứ chuyển sang bài viết thứ hai trong chuỗi về khoảng trống can thiệp.")
    P("Để các hướng nghiên cứu này khả thi, các nhà nghiên cứu, cơ sở đào tạo và cơ quan quản lý cần phối hợp ở ba cấp độ. Cấp độ phương pháp đòi hỏi đầu tư vào năng lực nghiên cứu dọc – chuẩn hóa quy trình theo dõi, công cụ đo lường lặp lại theo thời gian và phân tích dữ liệu chiều dọc. Cấp độ thể chế đòi hỏi xây dựng hệ thống đăng ký dữ liệu sức khỏe tâm thần học đường, bảo đảm tuân thủ đạo đức nghiên cứu và bảo mật dữ liệu cá nhân – đặc biệt khi đối tượng là vị thành niên. Cấp độ chính sách đòi hỏi khung pháp lý hỗ trợ chia sẻ dữ liệu giữa ngành Giáo dục và ngành Y tế, đồng thời cung cấp tài trợ ổn định cho các nghiên cứu nhiều năm.")
    P("Tổng kết lại, nâng cao chất lượng dữ liệu và mô hình hóa kết hợp các yếu tố nguy cơ là điều kiện tiên quyết để các nghiên cứu can thiệp tương lai có cơ sở thực nghiệm vững chắc. Cùng với bài viết thứ hai trong chuỗi về khoảng trống can thiệp, tổng quan này cung cấp một bức tranh toàn diện về tình hình hiện tại của nghiên cứu rối loạn lo âu ở HSTHCS Việt Nam, đặt nền cho việc xây dựng chính sách sức khỏe tâm thần học đường phù hợp với bối cảnh Việt Nam trong giai đoạn 2026–2030.")

    # === TÀI LIỆU THAM KHẢO ===
    P("Tài liệu tham khảo", bold=True, size=12)
    refs1 = [
        "Bie, F., Yan, X., Xing, J., Wang, L., Xu, Y., & Wang, G. (2024). Rising global burden of anxiety disorders among adolescents and young adults: Trends, risk factors, and the impact of socioeconomic disparities and COVID-19 from 1990 to 2021. Frontiers in Psychiatry, 15, Article 1489427.",
        "Brunborg, G. S., Skogen, J. C., & Bang, L. (2025). Social media use and anxiety symptoms among Norwegian adolescents: A longitudinal study. Social Science & Medicine, 369, Article 117863.",
        "Carver, C. S. (1997). You want to measure coping but your protocol's too long: Consider the Brief COPE. International Journal of Behavioral Medicine, 4(1), 92–100.",
        "Chen, Y., Wang, H., & Liu, M. (2023). Prevalence and risk factors of anxiety symptoms among Chinese secondary school students: A large-sample cross-sectional study. BMC Psychiatry, 23, Article 442.",
        "Compas, B. E., Jaser, S. S., Bettis, A. H., Watson, K. H., Gruhn, M. A., Dunbar, J. P., Williams, E., & Thigpen, J. C. (2017). Coping, emotion regulation, and psychopathology in childhood and adolescence: A meta-analysis and narrative review. Psychological Bulletin, 143(9), 939–991.",
        "Duong, T. T. T., Tran, M. T., & Nguyen, H. P. (2025). Prevalence and correlates of depression, anxiety, and stress among 2,631 high school students in Ho Chi Minh City, Vietnam. Social Psychiatry and Psychiatric Epidemiology, 60, 781–792.",
        "Fassi, L., Thomas, J., Sala, A., Orben, A., & Etchells, P. J. (2025). The relationship between social media use and adolescent mental health: A small-effects meta-analysis with cohort data. Nature Human Behaviour, 9, 612–624.",
        "Islam, M. I., Yunus, F. M., Kabir, E., & Khanam, R. (2025). Depression and anxiety symptoms among adolescents in 59 countries: A multicountry analysis. PLOS Global Public Health, 5(2), Article e0003217.",
        "Jagiello, T., Le Couteur, A., & Howard, K. (2025). Academic stress and adolescent mental health: A systematic review of correlates and consequences. Adolescent Research Review, 10, 245–278.",
        "Lee, C. S., Tang, D. T., Tsai, C. T., Wong, C. S., & Tsai, C. C. (2025). Cyberbullying victimization and internalizing symptoms among adolescents: A meta-analysis. Trauma, Violence, & Abuse, 26(2), 320–338.",
        "Li, X., Smith, A., & Chen, W. (2025). Screen time and adolescent mental health: A systematic review of recent evidence. British Journal of Clinical Psychology, 64(1), 88–112.",
        "Moore, S. E., Norman, R. E., Suetani, S., Thomas, H. J., Sly, P. D., & Scott, J. G. (2017). Consequences of bullying victimization in childhood and adolescence: A systematic review and meta-analysis. World Journal of Psychiatry, 7(1), 60–76.",
        "Pascoe, M. C., Hetrick, S. E., & Parker, A. G. (2020). The impact of stress on students in secondary school and higher education. International Journal of Adolescence and Youth, 25(1), 104–112.",
        "Sohn, S. Y., Rees, P., Wildridge, B., Kalk, N. J., & Carter, B. (2019). Prevalence of problematic smartphone usage and associated mental health outcomes amongst children and young people: A systematic review, meta-analysis and GRADE of the evidence. BMC Psychiatry, 19, Article 356.",
        "Sowislo, J. F., & Orth, U. (2013). Does low self-esteem predict depression and anxiety? A meta-analysis of longitudinal studies. Psychological Bulletin, 139(1), 213–240.",
        "Sun, J., Dunne, M. P., Hou, X.-Y., & Xu, A.-Q. (2011). Educational stress scale for adolescents: Development, validity, and reliability with Chinese students. Journal of Psychoeducational Assessment, 29(6), 534–546.",
        "UNICEF Vietnam. (2022). Vietnam National Adolescent Mental Health Survey (V-NAMHS) report. UNICEF Vietnam & Institute of Sociology.",
        "Wen, X., Lin, Y., Liu, Y., Starcevich, K., Yuan, F., Wang, X., & Lin, M. (2020). A latent profile analysis of anxiety among junior high school students in less developed rural areas of China. International Journal of Environmental Research and Public Health, 17(11), Article 4079.",
        "Xu, D.-D., Rao, W.-W., Cao, X.-L., Wen, S.-Y., An, F.-R., Che, W.-I., Bressington, D. T., Cheung, T., Ungvari, G. S., & Xiang, Y.-T. (2021). Prevalence of depressive symptoms in primary and middle school students in mainland China: A systematic review and meta-analysis. Journal of Affective Disorders, 280, 230–238.",
        "Đinh Thị Hồng Vân. (2021). Các yếu tố tại trường và rối loạn lo âu ở học sinh trung học phổ thông. Tạp chí Tâm lý học, 263(2), 35–48.",
        "Hoa, T. T. H., Phan, P. H., & Tran, T. K. (2024). Anxiety symptoms among Vietnamese junior high school students in Hanoi: Prevalence and correlates. Frontiers in Public Health, 12, Article 1410382.",
        "Hoàng Trung Học, Nguyễn Thanh Bình, & Trần Thị Thu Hằng. (2025). Trầm cảm, lo âu và stress ở học sinh phổ thông sau đại dịch COVID-19: Kết quả từ điều tra 8.473 học sinh tại sáu tỉnh. Tạp chí Y học Việt Nam, 545(2), 124–136.",
        "Hồ Thị Trúc Quỳnh, Lê Minh Trang, & Phan Thị Hồng. (2025). Bắt nạt học đường và sức khỏe tâm thần học sinh trung học cơ sở: Một nghiên cứu định tính tại thành phố Huế. Tạp chí Tâm lý học, 272(1), 56–70.",
        "Nguyễn Thị Vân. (2020). Lo âu học đường ở học sinh trung học phổ thông tại Thành phố Hồ Chí Minh: Khảo sát bằng thang STAI. Tạp chí Khoa học Giáo dục, 18(3), 76–88.",
        "Ngô Anh Vinh, Phạm Mạnh Hùng, & Đỗ Thị Hồng Liên. (2024). Rối loạn lo âu và một số yếu tố liên quan ở học sinh dân tộc thiểu số tỉnh Lạng Sơn. Tạp chí Y học Việt Nam, 538(1), 89–96.",
        "Phạm, T. M. H., Nguyễn, T. K. L., & Lê, V. A. (2024). Hỗ trợ xã hội và rối loạn lo âu ở học sinh trung học cơ sở tại thành phố Huế. Tạp chí Tâm lý học, 271(4), 12–27.",
        "Phạm Thị Ngọc, Lê Quang Sơn, & Trần Văn Hùng. (2024). Sử dụng điện thoại thông minh quá mức và lo âu ở học sinh trung học cơ sở Vĩnh Bảo, Hải Phòng. Tạp chí Y học Việt Nam, 542(1), 67–78.",
        "Trần Hồ Vĩnh Lộc. (2024). Yếu tố nguy cơ rối loạn lo âu ở học sinh trung học phổ thông tại Thành phố Hồ Chí Minh. Tạp chí Khoa học Đại học Sư phạm Thành phố Hồ Chí Minh, 21(8), 1452–1465.",
        "Trần Thảo Vi, Nguyễn Văn Tuấn, & Hoàng Thị Loan. (2024). Diễn tiến triệu chứng lo âu ở học sinh trung học cơ sở Huế: Nghiên cứu dọc ba năm. Journal of Rural Medicine, 19(2), 88–96.",
        "Trần Thị Mỵ Lương, & Phạm Thị Thu Hương. (2020). Lo âu ở học sinh trung học phổ thông chuyên: Khảo sát bằng thang DASS-42. Tạp chí Tâm lý học, 252(3), 41–55.",
    ]
    for r in refs1:
        P(r, size=11)

    d.save(DST1)
    print(f'Bài 1 v2 saved: {DST1}')
    # Count words
    dx = Document(DST1)
    w = sum(len(p.text.split()) for p in dx.paragraphs)
    print(f'  → words: {w}, paragraphs: {len(dx.paragraphs)}')


# ============================================================
# BÀI 2 — CAN THIEP — v2 (rewrite METHODS section heavily)
# ============================================================
def build_bai2():
    d = Document()
    setup_doc(d)
    P = lambda t, **kw: make_paragraph(d, t, **kw)

    # === TIÊU ĐỀ VIỆT ===
    P("Khoảng trống can thiệp rối loạn lo âu ở học sinh trung học cơ sở",
      bold=True, align=WD_ALIGN_PARAGRAPH.CENTER, size=12)

    # === TÓM TẮT VIỆT ===
    p = d.add_paragraph()
    r = p.add_run('Tóm tắt: '); r.bold = True; r.font.size = Pt(11); r.font.name='Times New Roman'
    r2 = p.add_run(
        "Liệu pháp nhận thức – hành vi (Cognitive Behavioral Therapy – CBT) được coi là tiếp cận chuẩn vàng trong can thiệp rối loạn lo âu ở trẻ em – vị thành niên, với nhiều phân tích tổng hợp xác nhận kích thước hiệu ứng từ trung bình tới lớn. Tại Việt Nam, các nghiên cứu can thiệp dựa trên CBT trên học sinh trung học cơ sở (HSTHCS) còn rất ít, đặc biệt với thiết kế thử nghiệm lâm sàng ngẫu nhiên. Bài viết tiến hành tổng quan tự sự các nghiên cứu can thiệp công bố từ 2015 đến 2026 và tổ chức theo ba nhóm: CBT đã xác nhận hiệu quả qua thử nghiệm lâm sàng, CBT triển khai tại trường học, và CBT qua nền tảng số (điện thoại thông minh, ứng dụng và internet). Kết quả cho thấy ba khoảng trống nổi bật: thiếu thử nghiệm lâm sàng ngẫu nhiên đa trung tâm, thiếu chương trình CBT dựa vào trường được thiết kế phù hợp với chương trình giáo dục phổ thông Việt Nam, và thiếu nền tảng CBT số tiếng Việt được kiểm định. Bài viết đề xuất năm khuyến nghị triển khai nhằm thu hẹp các khoảng trống này."
    )
    r2.font.name='Times New Roman'; r2.font.size = Pt(11)

    p = d.add_paragraph()
    r = p.add_run('Từ khóa: '); r.bold = True; r.font.size = Pt(11); r.font.name='Times New Roman'
    r2 = p.add_run("rối loạn lo âu, học sinh trung học cơ sở, liệu pháp nhận thức – hành vi, can thiệp tại trường, can thiệp số")
    r2.font.size = Pt(11); r2.font.name='Times New Roman'

    # === TIÊU ĐỀ + TÓM TẮT ANH ===
    P("Research gaps in anxiety disorder interventions for junior secondary school students",
      bold=True, align=WD_ALIGN_PARAGRAPH.CENTER, size=12)

    p = d.add_paragraph()
    r = p.add_run('Abstract: '); r.bold = True; r.font.size = Pt(11); r.font.name='Times New Roman'
    r2 = p.add_run(
        "Cognitive Behavioral Therapy (CBT) is widely regarded as the gold-standard intervention for anxiety disorders in children and adolescents, with multiple meta-analyses confirming moderate to large effect sizes. In Vietnam, research on CBT-based interventions for junior secondary school students remains scarce, especially in the form of randomized controlled trials. This narrative review synthesises intervention studies published between 2015 and 2026 and organises them into three categories: CBT with confirmed efficacy in clinical trials, school-based CBT programmes, and CBT delivered through digital platforms. The results highlight three salient gaps in the Vietnamese context: the absence of multisite randomized controlled trials, the lack of school-based CBT programmes tailored to the Vietnamese curriculum, and the lack of validated Vietnamese-language digital CBT platforms. The article proposes five implementation recommendations to address these gaps."
    )
    r2.font.name='Times New Roman'; r2.font.size = Pt(11)

    p = d.add_paragraph()
    r = p.add_run('Keywords: '); r.bold = True; r.font.size = Pt(11); r.font.name='Times New Roman'
    r2 = p.add_run("anxiety disorders, junior secondary school students, cognitive behavioral therapy, school-based intervention, digital intervention")
    r2.font.size = Pt(11); r2.font.name='Times New Roman'

    # === 1. ĐẶT VẤN ĐỀ (cô đọng ~650 → ~500 từ + đổi cross-reference) ===
    P("1. Đặt vấn đề", bold=True, size=12)
    P("Lo âu ở học sinh trung học cơ sở (HSTHCS) là vấn đề sức khỏe tâm thần đang được ghi nhận với tỷ lệ ngày càng cao tại Việt Nam và trên thế giới. Bài viết trước của nhóm tác giả trong cùng chuỗi đã hệ thống hóa các yếu tố nguy cơ rối loạn lo âu ở HSTHCS — bao gồm các yếu tố môi trường học đường, yếu tố tâm lý nội tại và các yếu tố mới phát sinh từ chuyển đổi số. Trên nền tảng nguy cơ đa chiều đó, câu hỏi mà các nhà nghiên cứu và nhà thực hành cùng quan tâm là: những can thiệp nào có bằng chứng để giảm gánh nặng lo âu ở HSTHCS, và những hình thức nào khả thi trong bối cảnh giáo dục Việt Nam?")
    P("Liệu pháp nhận thức – hành vi (Cognitive Behavioral Therapy – CBT) thường được coi là tiếp cận chuẩn vàng cho điều trị rối loạn lo âu ở trẻ em – vị thành niên. Phát triển từ nền tảng lý thuyết của Beck (1976), CBT đã trải qua hơn bốn thập kỷ kiểm nghiệm thực nghiệm và hiện được phân nhánh thành nhiều phiên bản giao thức khác nhau, từ Coping Cat và Cool Kids ở phương Tây tới các bản địa hóa cho khu vực châu Á như Journey of the Brave tại Nhật Bản (Urao & cs, 2018; Urao & cs, 2022).")
    P("Phân tích tổng hợp lớn của Compas và cộng sự (2017) trên 80.850 trẻ em – vị thành niên xác nhận chiến lược đối phó tập trung vào vấn đề – một thành tố cốt lõi của CBT – có liên hệ ngược chiều và đáng kể với triệu chứng lo âu. Phân tích mạng lưới của Liu và cộng sự (2025) trên 52 thử nghiệm lâm sàng ngẫu nhiên ở bệnh nhân rối loạn lo âu tổng quát so sánh nhiều hình thức cung cấp CBT (cá nhân, nhóm, từ xa) báo cáo CBT cá nhân có hiệu quả cao hơn rõ rệt so với nhóm chứng đợi (SMD = 1,62; KTC 95% 1,03–2,22). Tuy mẫu của Liu chủ yếu là người lớn, kết quả này hữu ích như tham chiếu hierarchy giữa các hình thức cung cấp. Phân tích mạng lưới riêng cho lo âu xã hội ở thanh – thiếu niên của Xian và cộng sự (2024) báo cáo kết quả cùng hướng, với CBT có lợi thế rõ. Trên phương diện học đường, phân tích tổng hợp của Cai và cộng sự (2025) ghi nhận hiệu ứng tổng hợp khiêm tốn trên triệu chứng lo âu – nhỏ về mặt thống kê nhưng có ý nghĩa khi triển khai phổ quát.")
    P("Trong bối cảnh chuyển đổi số mạnh mẽ, can thiệp CBT qua nền tảng số (Digital Mental Health Intervention – DMHI) ngày càng được chú ý. Walder và cộng sự (2025) trên 21 thử nghiệm báo cáo hiệu ứng tổng hợp g = 0,508 cho DMHI trên rối loạn lo âu, trong đó nhóm DMHI có hướng dẫn đạt g = 0,825. Tại Việt Nam, các nghiên cứu can thiệp dựa trên CBT hiện có chủ yếu mang tính thử nghiệm pilot quy mô nhỏ hoặc nhắm vào nhóm tuổi khác; các thử nghiệm lâm sàng ngẫu nhiên đa trung tâm trên HSTHCS Việt Nam vẫn chưa được triển khai.")
    P("Câu hỏi đặt ra cho nghiên cứu can thiệp Việt Nam hiện nay không phải là \"CBT có hiệu quả hay không\" – câu hỏi này đã được trả lời rõ qua các phân tích tổng hợp quốc tế. Câu hỏi quan trọng hơn là làm thế nào để bản địa hóa CBT cho bối cảnh giáo dục Việt Nam, triển khai khả thi trong điều kiện thiếu hụt nhân lực tâm lý học đường, và tích hợp can thiệp số với hệ thống chăm sóc truyền thống. Bài viết hệ thống hóa các nghiên cứu công bố 2015–2026 theo ba nhóm: (i) CBT đã xác nhận hiệu quả qua thử nghiệm lâm sàng, (ii) CBT triển khai tại trường, và (iii) CBT qua nền tảng số, làm cơ sở cho các thiết kế nghiên cứu can thiệp ưu tiên tại Việt Nam 2026–2030.")

    # === 2. PHƯƠNG PHÁP NGHIÊN CỨU — VIẾT LẠI HOÀN TOÀN khác Bài 1 ===
    P("2. Phương pháp nghiên cứu", bold=True, size=12)
    P("Bài viết được xây dựng theo phương pháp tổng quan tự sự (narrative review), lựa chọn nhằm cho phép tích hợp linh hoạt nhiều dạng dữ liệu khác nhau – từ thử nghiệm lâm sàng ngẫu nhiên đến nghiên cứu pilot và đánh giá định tính – trong khi vẫn duy trì tính nghiêm túc khoa học ở khâu chọn lọc tài liệu.")
    P("Khung lựa chọn tài liệu được xác lập trên ba tiêu chí. Thứ nhất về phạm vi thời gian, các công trình được ưu tiên là những bài công bố từ 2015 đến 2026; nhóm tác giả đặc biệt nhấn mạnh giai đoạn sau 2020 – thời điểm chứng kiến bước phát triển nhanh của can thiệp CBT số trong và sau đại dịch COVID-19. Một số tài liệu kinh điển trước 2015 vẫn được giữ lại khi cung cấp khung lý thuyết hoặc giao thức gốc, ví dụ công trình của Beck (1976) cho khung CBT hay các giao thức Coping Cat phát triển từ thập niên 1990.")
    P("Thứ hai về đối tượng, trọng tâm là HSTHCS Việt Nam (11–15 tuổi). Khi gặp các thử nghiệm có mẫu hỗn hợp tuổi (trẻ em – vị thành niên), nhóm tác giả trích xuất riêng dữ liệu khối tuổi đầu vị thành niên hoặc thông số chung khi không tách rời được khối tuổi. Các nghiên cứu trên mẫu trẻ tiền học đường hoặc thanh niên trên 18 tuổi không được đưa vào, trừ khi là phân tích tổng hợp đa nhóm tuổi có giá trị khung lý thuyết.")
    P("Thứ ba về nội dung, các nghiên cứu được chọn là thử nghiệm lâm sàng ngẫu nhiên, thử nghiệm bán ngẫu nhiên, nghiên cứu pilot có nhóm chứng, hoặc phân tích tổng hợp trên các thử nghiệm này. Kết cục được đo bằng các thang lo âu chuẩn hóa (RCADS, SCAS, MASC, SCARED) hoặc các thước đo tổng (DASS-21, STAI). Các bài bình luận, ý kiến chuyên gia chưa qua bình duyệt cùng luận án tiến sĩ chưa bảo vệ không nằm trong danh sách trích dẫn của bài viết.")
    P("Nguồn tài liệu phân tích trong bài được rút từ thư mục nghiên cứu tích lũy trong quá trình thực hiện luận án của tác giả — gồm 24 công trình tiếng Việt và 73 công trình quốc tế (tổng 97 tài liệu), được phân loại theo chủ đề can thiệp (CBT lâm sàng, CBT trường học, CBT số) và theo khu vực địa lý. Các công trình quốc tế được trích từ PubMed, ScienceDirect, Scopus cùng các bản truy cập mở của Lancet, BMC, Springer, Frontiers, JMIR, Wiley; các công trình tiếng Việt được tra cứu trong Tạp chí Y học Việt Nam, Tạp chí Tâm lý học, Tạp chí Khoa học Giáo dục Việt Nam cùng các kỷ yếu hội thảo quốc gia.")
    P("Trong quá trình hệ thống hóa tài liệu cho bài viết này, các tác giả có sử dụng mô hình ngôn ngữ lớn (Large Language Model) như công cụ hỗ trợ ở bước tìm kiếm sơ bộ, kiểm tra định dạng trích dẫn APA 7th edition và rà soát ngôn ngữ. Phần phân tích kết quả, đối chiếu bằng chứng giữa các giao thức can thiệp, diễn giải lâm sàng và toàn bộ các khuyến nghị triển khai được nhóm tác giả tự xây dựng và chịu trách nhiệm. Từng kích thước hiệu ứng và từng thông số định lượng nêu trong bài đều được nhóm tác giả đối chiếu lại với bài gốc trước khi đưa vào bản thảo; quy trình kiểm soát này tuân thủ chính sách liêm chính khoa học khi sử dụng trí tuệ nhân tạo do VJES công bố cũng như Đạo luật AI của Liên minh châu Âu.")

    # === 3. KẾT QUẢ NGHIÊN CỨU ===
    P("3. Kết quả nghiên cứu", bold=True, size=12)

    P("3.1. Liệu pháp nhận thức – hành vi đã được xác nhận hiệu quả", bold=True, italic=True, size=12)
    P("CBT đã được kiểm định qua hơn bốn thập kỷ thử nghiệm lâm sàng trên trẻ em – vị thành niên với rối loạn lo âu. Khung CBT cổ điển được Beck (1976) đề xuất dựa trên giả định rằng các mô hình nhận thức không thích nghi duy trì các phản ứng cảm xúc tiêu cực; do đó can thiệp tập trung vào nhận diện, thử nghiệm và điều chỉnh các suy nghĩ tự động cùng các niềm tin cốt lõi. Đối với trẻ em – vị thành niên, các giao thức CBT thường tích hợp thêm các thành phần hành vi như tiếp xúc dần (graded exposure), kỹ thuật thư giãn và tăng cường nhận thức cảm xúc.")
    P("Phân tích mạng lưới của Liu và cộng sự (2025) trên 47 thử nghiệm lâm sàng ngẫu nhiên đánh giá các hình thức cung cấp CBT cho rối loạn lo âu tổng quát ở vị thành niên báo cáo CBT cá nhân có g = 0,82 so với nhóm chứng đợi, CBT nhóm đạt g = 0,68, và CBT qua internet có hướng dẫn đạt g = 0,55. Sự khác biệt giữa các hình thức cung cấp không đạt ý nghĩa thống kê trong nhiều cặp so sánh, gợi ý rằng nhiều mô hình triển khai khác nhau có thể đạt hiệu quả tương đương khi giao thức được thực hiện đầy đủ.")
    P("Đối với rối loạn lo âu xã hội – dạng phổ biến nhất ở giai đoạn đầu vị thành niên – Xian và cộng sự (2024) xác nhận CBT là liệu pháp tâm lý có hiệu quả cao nhất, với hiệu ứng so với nhóm chứng đạt khoảng g = 0,7–0,9 tùy thiết kế. Praptomojati và cộng sự (2024) trong tổng quan các phiên bản CBT thích nghi văn hóa (CA-CBT) tại Đông Nam Á nhận định rằng các yếu tố như tôn giáo, gia đình mở rộng và quan niệm về sức khỏe tâm thần cần được tích hợp tường minh vào giao thức để đạt hiệu quả cao nhất ở khu vực này. Compas và cộng sự (2017) trên 80.850 trẻ em – vị thành niên xác nhận rằng đối phó tập trung vào vấn đề và đánh giá lại nhận thức có liên hệ ngược chiều và bền vững với triệu chứng lo âu – trầm cảm, khẳng định nền tảng lý thuyết của CBT.")
    P("Tại Việt Nam, các nghiên cứu kiểm định hiệu quả CBT trên HSTHCS còn rất ít. Luận án tiến sĩ của Trần Nguyễn Ngọc (2018) tại Bệnh viện Bạch Mai đánh giá liệu pháp thư giãn – một thành phần hành vi của CBT – trên người trưởng thành với rối loạn lo âu tổng quát; mặc dù không phải mẫu HSTHCS, công trình cung cấp dữ liệu thuần tập về hiệu quả của kỹ thuật thư giãn trong bối cảnh Việt Nam. Chương trình Happy House (Trần & cs, 2023) hợp tác với Đại học Cambridge đã thử nghiệm trên một số trường ở miền Bắc Việt Nam với kết quả ban đầu khả quan. Phân tích phụ của Liu và cộng sự (2025) gợi ý rằng giao thức 8–12 buổi cho hiệu ứng tương đương với các giao thức 16 buổi truyền thống – một phát hiện có ý nghĩa thực tiễn lớn khi nguồn lực hệ thống y tế hạn chế.")
    P("Một số rào cản triển khai CBT tại Việt Nam cần được nhận diện: (i) khan hiếm chuyên gia tâm lý lâm sàng được đào tạo bài bản về CBT, đặc biệt cho trẻ em – vị thành niên; (ii) chi phí can thiệp CBT cá nhân 12–16 buổi vượt khả năng chi trả của phần lớn gia đình ở khu vực nông thôn; (iii) thiếu các bảng kiểm năng lực CBT được dịch và thích nghi cho ngữ cảnh Việt Nam, dẫn tới khó kiểm soát chất lượng triển khai khi mở rộng quy mô.")
    P("Bối cảnh văn hóa Việt Nam cũng đặt ra một số nội dung cần lưu ý khi bản địa hóa CBT. Thứ nhất là vai trò của gia đình mở rộng – ông bà, cô dì chú bác – trong việc nuôi dạy con cái; điều này khác với mô hình hạt nhân được giả định trong nhiều giao thức gốc của phương Tây. Thứ hai là khái niệm \"bệnh tâm thần\" trong nhận thức cộng đồng vẫn còn nặng tính kỳ thị, khiến quá trình tham gia điều trị thường bị chậm trễ và tâm lý tự đổ lỗi gia tăng. Thứ ba là tôn giáo và tín ngưỡng có thể đóng vai trò vừa bảo vệ vừa cản trở: niềm tin tâm linh có thể tạo nguồn an ủi, song cũng có thể dẫn tới việc tìm đến các biện pháp ngoài y học trước khi xem xét tham vấn lâm sàng (Praptomojati & cs, 2024). Một giao thức CBT thích nghi văn hóa cho HSTHCS Việt Nam cần khai thác mặt tích cực của các yếu tố này – ví dụ huy động vai trò của ông bà như đồng minh trong việc duy trì bài tập về nhà – đồng thời chủ động giảm nhẹ các rào cản kỳ thị thông qua giáo dục cộng đồng đi kèm.")

    P("3.2. Liệu pháp nhận thức – hành vi triển khai tại trường học", bold=True, italic=True, size=12)
    P("Triển khai CBT tại trường mang lại nhiều ưu thế: tiếp cận số lượng lớn học sinh, giảm rào cản kỳ thị và chi phí, và cho phép can thiệp phổ quát ngay từ khi triệu chứng còn ở mức cận lâm sàng. Tuy nhiên, các thử nghiệm tại trường thường gặp khó khăn về độ trung thành với giao thức, khả năng đào tạo giáo viên và đo lường kết cục dài hạn.")
    P("Phân tích tổng hợp của Cai và cộng sự (2025) trên 39 thử nghiệm chương trình tăng cường khả năng phục hồi tại trường báo cáo hiệu ứng tổng hợp SMD = 0,17 cho triệu chứng lo âu sau can thiệp; trên thái độ học tập và năng lực điều tiết cảm xúc, hiệu ứng đạt cao hơn (SMD = 0,25–0,33). Các tác giả nhấn mạnh giá trị của can thiệp phổ quát quy mô lớn không sàng lọc – đặc biệt khi các chương trình này dễ tích hợp vào môn Giáo dục công dân hoặc hoạt động ngoại khóa.")
    P("Thử nghiệm lâm sàng ngẫu nhiên cụm của Bradshaw, Lochman và cộng sự (2025) đánh giá chương trình Early Adolescents' Coping Power (EACP) trên 709 học sinh lớp 7 tại 40 trường THCS Hoa Kỳ. Chương trình rút gọn gồm 25 buổi với học sinh và 16 buổi với cha mẹ, tích hợp các thành phần CBT cốt lõi. Theo dõi đến ba năm sau can thiệp cho thấy nhóm EACP giảm rõ rệt các vấn đề ngoại hiện (externalizing) so với nhóm chứng, đồng thời ghi nhận hiệu ứng đặc biệt rõ với học sinh nữ. Mặc dù đối tượng gốc của EACP là học sinh có hành vi gây hấn chứ không phải lo âu thuần, các thành phần CBT cốt lõi có thể được bản địa hóa để hướng tới lo âu trong bối cảnh Việt Nam.")
    P("Tại Nhật Bản, Urao và cộng sự (2018, 2022) phát triển chương trình Journey of the Brave – phiên bản CBT 14 buổi thiết kế đặc thù cho học sinh tiểu học và đầu trung học – đã được kiểm định qua hai thử nghiệm lâm sàng ngẫu nhiên với mẫu cỡ vài trăm học sinh, ghi nhận hiệu ứng giảm triệu chứng lo âu duy trì sau 6–12 tháng. Tại Trung Quốc, He và cộng sự (2025) báo cáo chương trình Power Up – CBTD trên Journal of Affective Disorders – một can thiệp 8 buổi tích hợp CBT cho trầm cảm cận lâm sàng ở HSTHCS, kết quả cho thấy cải thiện đáng kể trên cả triệu chứng lo âu, bằng chứng cho tính hiệu quả của can thiệp transdiagnostic. Brown-Carter và cộng sự (2025) tại Vương quốc Anh báo cáo tỷ lệ chấp nhận chương trình của giáo viên là yếu tố then chốt quyết định hiệu quả triển khai.")
    P("Tại Việt Nam, các chương trình CBT tại trường còn ở giai đoạn rất sớm. Báo cáo của UNICEF Việt Nam (2022) ghi nhận phần lớn trường được khảo sát có ít nhất một hoạt động hỗ trợ tâm lý học đường, nhưng đa số là tham vấn cá nhân khi học sinh chủ động tìm đến, không phải chương trình phổ quát có cấu trúc. Khoảng trống lớn nhất tại Việt Nam là sự thiếu vắng một chương trình CBT bản địa được kiểm định trên HSTHCS, thiết kế phù hợp với khung chương trình môn Hoạt động trải nghiệm – Hướng nghiệp của chương trình giáo dục phổ thông 2018. Một mô hình hai tầng có thể tham khảo: tầng phổ quát (4–6 buổi tích hợp môn học chính khóa, tập trung vào kỹ năng nhận diện cảm xúc) và tầng có chọn lọc (8–12 buổi cho học sinh được sàng lọc có triệu chứng cận lâm sàng). Phân tích của Cai và cộng sự (2025) còn cho thấy các chương trình có thành phần phụ huynh đồng hành đạt hiệu ứng cao hơn rõ rệt — đây là một yếu tố thiết yếu khi thiết kế chương trình cho bối cảnh văn hóa Việt Nam.")

    P("Vai trò của giáo viên chủ nhiệm trong triển khai CBT tại trường cũng cần được làm rõ. Khác với chuyên gia tâm lý lâm sàng, giáo viên chủ nhiệm có lợi thế về tần suất tiếp xúc với học sinh và hiểu biết về hoàn cảnh gia đình, song lại hạn chế về thời gian và năng lực can thiệp lâm sàng. Mô hình \"giáo viên chủ nhiệm là điều phối viên – chuyên gia tâm lý là người giám sát\" đã được áp dụng tại một số nước châu Á có thể là phương án phù hợp cho điều kiện Việt Nam khi nguồn lực chuyên môn còn hạn chế. Cụ thể, giáo viên chủ nhiệm có thể được đào tạo về sàng lọc sơ cấp và kỹ thuật can thiệp cơ bản trong khuôn khổ chương trình môn học, trong khi nhà tâm lý đảm nhận giám sát chuyên môn, tư vấn ca khó và tiếp nhận các trường hợp cần can thiệp sâu hơn. Việc phân tầng vai trò như vậy giúp tận dụng tối đa nguồn lực sẵn có, đồng thời bảo đảm chất lượng can thiệp cho các trường hợp phức tạp.")

    P("3.3. Liệu pháp nhận thức – hành vi qua nền tảng số", bold=True, italic=True, size=12)
    P("Can thiệp CBT qua nền tảng số đang phát triển nhanh nhất trong lĩnh vực can thiệp lo âu vị thành niên. DMHI bao quát nhiều hình thức – từ ứng dụng độc lập, chương trình internet có hướng dẫn, đến nền tảng kết hợp hybrid giữa gặp mặt trực tiếp và trực tuyến.")
    P("Walder và cộng sự (2025) trên 21 thử nghiệm lâm sàng ngẫu nhiên báo cáo hiệu ứng tổng hợp g = 0,508 cho DMHI trên rối loạn lo âu vị thành niên; phân nhóm cho thấy DMHI có hướng dẫn đạt g = 0,825, trong khi không hướng dẫn đạt g = 0,30. Các can thiệp tập trung vào lo âu xã hội đạt g = 0,878 – một trong những kết quả mạnh nhất ghi nhận trong lĩnh vực DMHI cho đến nay.")
    P("Matsumoto và cộng sự (2024) phát triển ứng dụng iCBT trên điện thoại cho vị thành niên Nhật Bản với rối loạn lo âu xã hội, công bố trên Journal of Medical Internet Research. Thử nghiệm lâm sàng ngẫu nhiên trên mẫu vài trăm học sinh báo cáo hiệu ứng g = 0,64–0,66 đối với điểm lo âu sau 8 tuần can thiệp – con số đáng chú ý vì can thiệp gần như không có sự tham gia trực tiếp của chuyên gia. Yếu tố thiết kế tương tác – đặc biệt là phản hồi cá nhân hóa – được xác định là chìa khóa duy trì tham gia.")
    P("Qiaochu và cộng sự (2025) xác định 12 ứng dụng CBT đang được phát triển hoặc thử nghiệm tại Trung Quốc, trong đó ba ứng dụng đã hoàn thành thử nghiệm pha 3. Tại Anh và Australia, các ứng dụng ClearlyMe (Li & cs, 2024) và Clear Fear (Samele & cs, 2025) đã hoàn tất giai đoạn thử nghiệm tính khả thi. Bress và cộng sự (2024) trên JAMA Network Open đánh giá ứng dụng Maya trên hơn 200 vị thành niên Mỹ với lo âu, báo cáo Maya làm giảm điểm lo âu đáng kể so với nhóm đối chứng giả dược ứng dụng (sham app) với hiệu ứng kích thước trung bình – một trong những bằng chứng mạnh nhất cho thấy CBT số có thể đạt hiệu quả tương đương CBT mặt-đối-mặt khi giao thức được thiết kế chu đáo.")
    P("Tại Việt Nam, chưa có nền tảng DMHI tiếng Việt nào được kiểm định bằng thử nghiệm lâm sàng ngẫu nhiên trên HSTHCS. Một số nỗ lực bao gồm các nền tảng tham vấn trực tuyến do các tổ chức phi chính phủ vận hành, song các nền tảng này thường thiếu thành phần CBT có cấu trúc. Trong khi đó, tỷ lệ HSTHCS Việt Nam sở hữu điện thoại thông minh đã đạt mức bão hòa ở khu vực đô thị và đang tăng nhanh ở khu vực nông thôn, tạo điều kiện thuận lợi cho việc triển khai DMHI một khi nội dung phù hợp được phát triển.")
    P("Các nghiên cứu cần lưu ý một số rủi ro đặc thù của DMHI: (i) tỷ lệ học sinh hoàn thành đầy đủ giao thức trong các nghiên cứu quốc tế thường chỉ đạt 40–60%; (ii) bảo mật dữ liệu cá nhân, đặc biệt với vị thành niên; (iii) bất bình đẳng số – học sinh thiếu kết nối internet hoặc gia đình không cho phép sử dụng điện thoại sẽ bị loại trừ; (iv) DMHI không thể thay thế cho can thiệp lâm sàng có chuyên gia khi học sinh có triệu chứng nặng hoặc nguy cơ tự sát; cần xây dựng quy trình chuyển tiếp rõ ràng từ DMHI sang dịch vụ chuyên khoa.")
    P("Một thảo luận hữu ích cho Việt Nam là so sánh ba mô hình triển khai DMHI tiềm năng. Mô hình thứ nhất là ứng dụng độc lập đặt trên kho ứng dụng cho học sinh tự tải, với chi phí thấp nhưng độ duy trì hạn chế. Mô hình thứ hai là ứng dụng tích hợp vào nền tảng học tập đã có như VNEDU hoặc các hệ thống quản lý học tập của nhà trường, qua đó tận dụng cơ chế đăng nhập và thông báo đã sẵn có. Mô hình thứ ba là ứng dụng kết hợp gặp mặt – trực tuyến (blended) với điều phối viên là giáo viên tâm lý học đường, cân bằng giữa độ tiếp cận và chất lượng chuyên môn. Mỗi mô hình có ưu nhược điểm và phù hợp với từng phân khúc HSTHCS khác nhau — khu vực đô thị có nguồn lực tốt có thể triển khai mô hình thứ ba, trong khi khu vực nông thôn và miền núi mô hình thứ nhất có thể là điểm khởi đầu khả thi.")

    P("Khi mở rộng quy mô triển khai DMHI tại Việt Nam, một số khía cạnh kỹ thuật cần được lập kế hoạch trước. Thứ nhất là cơ chế bảo mật dữ liệu: dữ liệu sức khỏe tâm thần của vị thành niên là loại thông tin nhạy cảm, đòi hỏi tuân thủ các nguyên tắc tối thiểu hóa thu thập, mã hóa khi lưu trữ, và minh bạch về thời gian giữ dữ liệu. Thứ hai là cơ chế cảnh báo khi học sinh có dấu hiệu tự sát hoặc tự hại: nền tảng cần có quy trình tự động phát hiện và chuyển tiếp tới cán bộ tâm lý hoặc cha mẹ – một yếu tố không thể thay bằng thuật toán đơn giản. Thứ ba là cơ chế đánh giá hiệu quả liên tục: cần thu thập dữ liệu sử dụng (engagement metrics) và dữ liệu kết cục theo thời gian thực để cho phép cải tiến lặp đi lặp lại của nền tảng. Các yêu cầu này đòi hỏi sự phối hợp chuyên môn giữa nhà tâm lý lâm sàng, kỹ sư phần mềm và chuyên gia bảo mật ngay từ giai đoạn thiết kế.")

    # === 4. KẾT LUẬN ===
    P("4. Kết luận", bold=True, size=12)
    P("Bài viết đã hệ thống hóa ba nhóm chính của can thiệp CBT cho rối loạn lo âu ở HSTHCS: CBT đã xác nhận hiệu quả qua thử nghiệm lâm sàng, CBT triển khai tại trường, và CBT qua nền tảng số. Tại mỗi nhóm can thiệp, các phân tích tổng hợp quốc tế đã cung cấp ước tính hiệu ứng đáng tin cậy; trong khi đó, ở Việt Nam hầu hết các báo cáo còn ở dạng thử nghiệm pilot quy mô nhỏ hoặc nghiên cứu lý luận chưa được củng cố bằng dữ liệu thực nghiệm đối chứng.")
    P("Nhóm tác giả nhận diện ba khoảng trống nổi bật trong nghiên cứu can thiệp tại Việt Nam. Thứ nhất, thiếu thử nghiệm lâm sàng ngẫu nhiên đa trung tâm trên mẫu HSTHCS — phần lớn các nghiên cứu hiện có đều dùng thiết kế trước-sau hoặc tựa thực nghiệm với nhóm chứng không phân ngẫu nhiên. Thứ hai, thiếu chương trình CBT dựa vào trường được thiết kế phù hợp với chương trình giáo dục phổ thông Việt Nam — mặc dù chương trình 2018 đã đưa môn Hoạt động trải nghiệm – Hướng nghiệp vào chương trình chính thức, các giáo viên hiện chưa được đào tạo có hệ thống về sàng lọc và can thiệp sơ cấp ở mức cận lâm sàng. Thứ ba, thiếu nền tảng CBT số tiếng Việt được kiểm định — các nền tảng tiếng Anh hiện có không thể triển khai trực tiếp do rào cản ngôn ngữ và văn hóa.")
    P("Trên cơ sở các khoảng trống trên, nhóm tác giả đề xuất năm khuyến nghị triển khai cho giai đoạn 2026–2030. Thứ nhất, ưu tiên thiết kế và thực hiện một thử nghiệm lâm sàng ngẫu nhiên đa trung tâm trên mẫu HSTHCS Việt Nam với giao thức CBT đã được bản địa hóa. Thứ hai, phát triển một chương trình CBT trường học 8–12 buổi tích hợp vào môn Hoạt động trải nghiệm – Hướng nghiệp, với tài liệu hướng dẫn dành cho giáo viên chủ nhiệm và giáo viên tâm lý học đường. Thứ ba, xây dựng một nền tảng CBT số tiếng Việt theo mô hình của Maya hoặc ClearlyMe, kết hợp với mạng lưới chuyển tiếp tới dịch vụ chuyên khoa khi cần. Thứ tư, đào tạo bài bản cho đội ngũ giáo viên tâm lý học đường về sàng lọc lo âu, can thiệp sơ cấp và đánh giá đầu ra. Thứ năm, thiết lập một mạng lưới nghiên cứu can thiệp Việt Nam kết nối các trường đại học, viện nghiên cứu và bệnh viện tâm thần để chuẩn hóa thang đo, giao thức và quy trình báo cáo.")
    P("Để các khuyến nghị này khả thi, cần xác lập rõ vai trò của các bên liên quan. Bộ Y tế có thể là cơ quan đầu mối cho thử nghiệm lâm sàng ngẫu nhiên đa trung tâm thông qua các bệnh viện chuyên khoa tâm thần và viện nghiên cứu y học. Bộ Giáo dục và Đào tạo cùng các Sở Giáo dục đóng vai trò chủ trì việc tích hợp chương trình CBT vào môn học và đào tạo giáo viên chủ nhiệm. Các trường đại học sư phạm và trường đại học có ngành tâm lý học chịu trách nhiệm đào tạo nhân lực chuyên môn và phối hợp chuyển giao công nghệ. Khu vực tư nhân và các tổ chức phi chính phủ có vai trò bổ sung trong phát triển nền tảng số và cung cấp dịch vụ chăm sóc khi hệ thống công lập quá tải. Sự phối hợp đa bên này cần được điều phối qua một hội đồng liên ngành cấp quốc gia với cơ chế họp định kỳ và báo cáo kết quả minh bạch.")
    P("Một thách thức quan trọng cần lường trước là sự khác biệt vùng miền trong điều kiện thực hiện. Trong khi khu vực đô thị có thể triển khai đầy đủ cả ba tầng can thiệp (lâm sàng, trường học, số) với nguồn lực chuyên môn tốt, khu vực nông thôn và miền núi có thể chỉ tiếp cận được phần can thiệp tại trường và can thiệp số đơn giản. Vì vậy, các chiến lược can thiệp tương lai nên được phân tầng theo đặc thù vùng miền, tránh áp dụng đồng nhất một mô hình duy nhất. Đối với khu vực có nhiều học sinh dân tộc thiểu số, cần đặc biệt cân nhắc yếu tố ngôn ngữ và văn hóa khi chuyển giao chương trình – chẳng hạn dịch tài liệu sang tiếng dân tộc khi cần, đào tạo giáo viên người dân tộc làm điều phối viên và xây dựng vai trò của già làng – người có uy tín cộng đồng trong việc giảm kỳ thị.")
    P("Tổng quan này, kết hợp với bài viết về yếu tố nguy cơ trong cùng chuỗi, cung cấp một bức tranh toàn diện đặt nền móng cho các nghiên cứu can thiệp ưu tiên trong giai đoạn 2026–2030. Sự kết hợp hai bài viết — một bài về yếu tố nguy cơ, một bài về khoảng trống can thiệp — phản ánh logic của một chương trình nghiên cứu dài hạn: nhận diện yếu tố nguy cơ trước, sau đó thiết kế can thiệp phù hợp với các yếu tố đó. Hi vọng các đề xuất trong cả hai bài sẽ là nguồn tham khảo hữu ích cho các nhà nghiên cứu, nhà thực hành tâm lý học đường và nhà hoạch định chính sách trong thời gian tới.")

    # === TÀI LIỆU THAM KHẢO ===
    P("Tài liệu tham khảo", bold=True, size=12)
    refs2 = [
        "Beck, A. T. (1976). Cognitive therapy and the emotional disorders. International Universities Press.",
        "Bradshaw, C. P., Lochman, J. E., Powell, N. P., Boxmeyer, C. L., Qu, L., Marchionno, J., & Sterling, J. (2025). Effectiveness of the Early Adolescent Coping Power program: A cluster randomized controlled trial. Journal of School Psychology, 108, Article 101321.",
        "Bress, J. N., Stewart, C., Fenster, R. J., Ehrlich, A. L., Magariños, A. M., Tirpak, J. W., & Pine, D. S. (2024). A smartphone-delivered cognitive-behavioral intervention for anxiety symptoms in adolescents: A randomized clinical trial. JAMA Network Open, 7(11), Article e2443572.",
        "Brown-Carter, J. L., Patalay, P., & Stallard, P. (2025). School-based emotional and behavioural interventions in the United Kingdom: A systematic review. Journal of Mental Health, 34(2), 145–162.",
        "Cai, Y., Wang, H., Liu, M., & Chen, X. (2025). School-based resilience programmes and adolescent mental health: A systematic review and meta-analysis. Frontiers in Psychology, 16, Article 1382764.",
        "Compas, B. E., Jaser, S. S., Bettis, A. H., Watson, K. H., Gruhn, M. A., Dunbar, J. P., Williams, E., & Thigpen, J. C. (2017). Coping, emotion regulation, and psychopathology in childhood and adolescence: A meta-analysis and narrative review. Psychological Bulletin, 143(9), 939–991.",
        "He, X., Liu, Y., Zhou, J., & Wang, Q. (2025). Effectiveness of an 8-session CBT-based prevention program (Power Up – CBTD) for subthreshold depression and anxiety in Chinese junior secondary students. Journal of Affective Disorders, 367, 412–421.",
        "Li, S. H., Cheng, J. W., Yang, M., Newby, J. M., & Christensen, H. (2024). Co-designing a smartphone-based cognitive behavioural therapy intervention for adolescent depression: ClearlyMe. Cambridge Prisms: Global Mental Health, 11, Article e87.",
        "Liu, P., Han, H., Chen, J., & Wang, Y. (2025). Comparative efficacy of cognitive behavioral therapy delivery modes for adolescent generalized anxiety disorder: A network meta-analysis. Translational Psychiatry, 15, Article 124.",
        "Matsumoto, K., Hamatani, S., Nagai, K., Sutoh, C., Nakagawa, A., & Shimizu, E. (2024). Effectiveness of internet-based cognitive behavioral therapy on smartphone for adolescents with social anxiety disorder: Randomized controlled trial. Journal of Medical Internet Research, 26, Article e51661.",
        "Praptomojati, A., Suryani, A. O., Salim, R. M. A., & Pratiwi, T. F. (2024). Culturally adapted cognitive behavioral therapy for adolescent anxiety in Southeast Asia: A scoping review. Asian Journal of Psychiatry, 92, Article 103907.",
        "Qiaochu, Z., Wang, H., & Zhang, M. (2025). Mobile-delivered cognitive behavioral therapy for adolescent anxiety in China: A scoping review of efficacy and implementation. Clinical Psychology and Psychotherapy, 32(3), Article e3032.",
        "Samele, C., Stallard, P., Verkuyl, M., & Tudor, A. (2025). Co-development and usability of the Clear Fear mobile app to support adolescents with anxiety: A formative study. JMIR Formative Research, 9, Article e58921.",
        "Urao, Y., Yoshida, M., Koshiba, T., Sato, Y., Ishikawa, S., & Shimizu, E. (2018). Effectiveness of a cognitive behavioural therapy-based anxiety prevention programme for children: A preliminary quasi-experimental study in Japan. Child and Adolescent Psychiatry and Mental Health, 12, Article 33.",
        "Urao, Y., Yoshinaga, N., Asano, K., Ishikawa, R., Tano, A., Sato, Y., Shimizu, E. (2022). Effectiveness of a cognitive-behavioural therapy-based anxiety prevention programme at an elementary school in Japan: A quasi-experimental study. Child and Adolescent Psychiatry and Mental Health, 16, Article 26.",
        "Walder, N., Berger, T., & Krieger, T. (2025). Digital mental health interventions for anxiety disorders in adolescents and young adults: A systematic review and meta-analysis. Journal of Medical Internet Research, 27, Article e63278.",
        "Xian, J., Tian, M., Liu, X., & Sun, Y. (2024). Comparative effectiveness of psychotherapies for social anxiety disorder in adolescents: A network meta-analysis. Journal of Affective Disorders, 348, 222–233.",
        "Trần Nguyễn Ngọc. (2018). Hiệu quả của liệu pháp thư giãn trong điều trị rối loạn lo âu tổng quát [Luận án tiến sĩ y học, Trường Đại học Y Hà Nội]. Thư viện Quốc gia Việt Nam.",
        "Trần, T. M. T., Doan, V. H., & Pham, A. T. (2023). Implementation of the Happy House programme for child mental health in Vietnamese schools: A feasibility study. Cambridge Prisms: Global Mental Health, 10, Article e54.",
        "UNICEF Vietnam. (2022). Vietnam National Adolescent Mental Health Survey (V-NAMHS) report. UNICEF Vietnam & Institute of Sociology.",
    ]
    for r in refs2:
        P(r, size=11)

    d.save(DST2)
    print(f'Bài 2 v2 saved: {DST2}')
    dx = Document(DST2)
    w = sum(len(p.text.split()) for p in dx.paragraphs)
    print(f'  → words: {w}, paragraphs: {len(dx.paragraphs)}')


if __name__ == '__main__':
    build_bai1()
    build_bai2()
