# -*- coding: utf-8 -*-
"""Kiem tra cuoi cung - sach watermark + placeholder.
28/05/2026."""
import os, sys, io, hashlib, zipfile
os.environ['PYTHONIOENCODING'] = 'utf-8'
if hasattr(sys.stdout, 'buffer'):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from docx import Document
from docx.oxml.ns import qn

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
BACKUP = os.path.join(ROOT, 'Luận án TS', '01_LuanAn_v3_1_FixCoping_28052026_BEFORE_TOC.docx')
CURRENT = os.path.join(ROOT, 'Luận án TS', '01_LuanAn_v3_1_FixCoping_28052026.docx')

bk = Document(BACKUP)
nw = Document(CURRENT)

print("="*70)
print("KIEM TRA SACH WATERMARK + PLACEHOLDER")
print("="*70)

# 1. Check no Claude/F9/placeholder text
print("\n[1] Tim cac tu khoa nghi van:")
suspicious = ['Nhấn F9', 'Ấn F9', 'F9 hoặc', 'Update Field', 'Claude',
              'CLAUDE', 'Anthropic', 'placeholder', 'PLACEHOLDER',
              'TODO:', 'Generated by', 'Watermark', 'WATERMARK']
found_any = False
for term in suspicious:
    for i, p in enumerate(nw.paragraphs):
        if term in p.text:
            print(f"  ✗ FOUND '{term}' at para {i}: {p.text[:80]!r}")
            found_any = True
if not found_any:
    print("  ✓ Khong tim thay tu khoa nao")

# 2. Check no w:pict watermarks
print("\n[2] Watermark elements (w:pict in header/footer):")
total = 0
for sec in nw.sections:
    for hf in [sec.header, sec.first_page_header, sec.even_page_header,
               sec.footer, sec.first_page_footer, sec.even_page_footer]:
        for e in hf._element.iter():
            if e.tag in (qn('w:pict'), qn('w:object'), qn('w:drawing')):
                total += 1
print(f"  Total: {total} {'✓ SACH' if total == 0 else '✗ CON'}")

# 3. Verify TOC field
print("\n[3] TOC field:")
toc_found = False
for elem in nw.element.body.iter():
    if elem.tag == qn('w:instrText'):
        if elem.text and 'TOC' in elem.text:
            print(f"  ✓ TOC field intact: {elem.text!r}")
            toc_found = True
            break
if not toc_found:
    print("  ✗ TOC MISSING")

# 4. Para 61 (TOC paragraph) text
print("\n[4] Paragraph 61 (TOC):")
if 61 < len(nw.paragraphs):
    p61 = nw.paragraphs[61]
    print(f"  Text: {p61.text!r}")
    print(f"  {'✓ Khong co text placeholder' if p61.text.strip() == '' else '✗ Co text bat thuong'}")

# 5. Compare to BEFORE_TOC backup
print("\n[5] So sanh voi backup BEFORE_TOC:")
print(f"  Backup paragraphs: {len(bk.paragraphs)}")
print(f"  Current paragraphs: {len(nw.paragraphs)}")
print(f"  Diff: {len(nw.paragraphs) - len(bk.paragraphs)} (mong doi +1 cho TOC field)")

# Text content match check (with TOC field paragraph being empty)
diffs = 0
for i in range(len(bk.paragraphs)):
    j = i if i <= 60 else i + 1
    if j >= len(nw.paragraphs):
        continue
    if bk.paragraphs[i].text != nw.paragraphs[j].text:
        diffs += 1
        if diffs <= 3:
            print(f"  Diff at backup[{i}] -> current[{j}]:")
            print(f"    bk: {bk.paragraphs[i].text[:80]!r}")
            print(f"    nw: {nw.paragraphs[j].text[:80]!r}")
print(f"  Text differences: {diffs} (mong doi 0)")

# 6. Character count
bk_chars = sum(len(p.text) for p in bk.paragraphs)
nw_chars = sum(len(p.text) for p in nw.paragraphs)
print(f"\n[6] Character count:")
print(f"  Backup:  {bk_chars}")
print(f"  Current: {nw_chars}")
print(f"  Diff:    {nw_chars - bk_chars} (mong doi 0 vi TOC para hien tai trong)")

# 7. Tables
print(f"\n[7] Tables: {len(nw.tables)} (backup: {len(bk.tables)})")

# 8. Images
with zipfile.ZipFile(BACKUP) as zb, zipfile.ZipFile(CURRENT) as zn:
    bk_m = sorted([n for n in zb.namelist() if 'word/media/' in n])
    nw_m = sorted([n for n in zn.namelist() if 'word/media/' in n])
    print(f"\n[8] Media files:")
    print(f"  Backup: {len(bk_m)}")
    print(f"  Current: {len(nw_m)}")
    same = sum(1 for m in bk_m if m in nw_m and zb.read(m) == zn.read(m))
    print(f"  Byte-identical: {same}/{len(bk_m)}")

# 9. SHA256 hash of body text
bk_body = '\n'.join(p.text for p in bk.paragraphs)
nw_body = '\n'.join(p.text for p in nw.paragraphs)
nw_body_no_empty = nw_body  # No placeholder to remove now
bk_hash = hashlib.sha256(bk_body.encode('utf-8')).hexdigest()
# Current minus the empty new paragraph at index 61
nw_paras_minus_toc = [p.text for j, p in enumerate(nw.paragraphs) if j != 61]
nw_body_clean = '\n'.join(nw_paras_minus_toc)
nw_hash_clean = hashlib.sha256(nw_body_clean.encode('utf-8')).hexdigest()
print(f"\n[9] SHA256 hash:")
print(f"  Backup body:               {bk_hash}")
print(f"  Current body (-empty TOC): {nw_hash_clean}")
print(f"  {'✓ KHOP HOAN TOAN' if bk_hash == nw_hash_clean else '✗ KHAC'}")

print()
print("="*70)
print(f"FILE: {CURRENT}")
print(f"SIZE: {os.path.getsize(CURRENT)//1024} KB")
print("="*70)
