# -*- coding: utf-8 -*-
"""Sinh ban Tong quan NGAN theo chu de (~9k tu) thay cho muc 1.1 cua luan an.
- Viet theo CHU DE (khong liet ke tung cong trinh) - khac phuc PB Muc 10
- Ket noi voi Bai 1 (YTNC) va Bai 2 (Can thiep)
- Bao gom Yeu to bao ve voi bien phap ung pho theo gop y cua thay
- Chi dung citations da verify trong cac phien truoc
Ngay 26/05/2026."""
import os, sys, io
os.environ['PYTHONIOENCODING'] = 'utf-8'
if hasattr(sys.stdout, 'buffer'):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from docx import Document
from docx.shared import Pt, Cm, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
OUT = os.path.join(ROOT, 'Luận án TS', '01_TongQuan_TheoChuDe_FULL_v1_26052026.docx')

# ============================================================
# HELPERS
# ============================================================
def doc_init():
    doc = Document()
    s = doc.styles['Normal']
    s.font.name = 'Times New Roman'; s.font.size = Pt(13)
    s.paragraph_format.space_after = Pt(6); s.paragraph_format.line_spacing = 1.5
    for sec in doc.sections:
        sec.top_margin = Cm(3.0); sec.bottom_margin = Cm(2.5)
        sec.left_margin = Cm(3.5); sec.right_margin = Cm(2.5)
    return doc

def H(doc, text, level=1):
    h = doc.add_heading(text, level=level)
    for r in h.runs:
        r.font.name = 'Times New Roman'; r.font.color.rgb = RGBColor(0, 0, 0)

def P(doc, text, indent=True, italic=False, bold=False):
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
    if indent:
        p.paragraph_format.first_line_indent = Cm(1.25)
    r = p.add_run(text)
    r.font.name = 'Times New Roman'; r.font.size = Pt(13)
    r.italic = italic; r.bold = bold

def render(doc, blocks):
    for kind, text in blocks:
        if kind == 'H2':
            H(doc, text, 2)
        elif kind == 'H3':
            H(doc, text, 3)
        elif kind == 'P':
            P(doc, text)

# ============================================================
# CONTENT BLOCKS
# ============================================================

INTRO = [
    ('H2', 'Tổng quan nghiên cứu'),
    ('P', 'Tiểu mục này tổng hợp các kết quả nghiên cứu trong và ngoài nước về rối loạn lo âu ở vị thành niên — chủ yếu công bố trong khoảng 5-7 năm gần đây — theo các trục chủ đề: tỷ lệ phổ biến, mức độ, biểu hiện, yếu tố nguy cơ, yếu tố bảo vệ và can thiệp. Cách trình bày tập trung tổng hợp xu hướng và phát hiện chung giữa nhiều nghiên cứu trong cùng chủ đề, thay vì điểm luận lần lượt từng công trình riêng lẻ. Hai bài tổng hợp chuyên sâu của tác giả — Bài 1 về Yếu tố nguy cơ và Bài 2 về Khoảng trống can thiệp — được nộp kèm luận án để cung cấp phân tích đầy đủ về hai chủ đề đó; trong tổng quan này chỉ tóm tắt những điểm cốt lõi và dẫn ra hai bài đính kèm.'),
]

# ============================================================
# 1. TY LE PHO BIEN
# ============================================================
SEC_TY_LE = [
    ('H3', '1.1.1. Tỷ lệ phổ biến của rối loạn lo âu ở vị thành niên'),

    ('P', 'Rối loạn lo âu là một trong những vấn đề sức khỏe tâm thần phổ biến nhất ở vị thành niên trên toàn cầu. Các báo cáo của Tổ chức Y tế Thế giới cùng nhiều phân tích tổng hợp gần đây đều ghi nhận xu hướng tăng tỷ lệ ở khu vực châu Á — Thái Bình Dương trong và sau đại dịch COVID-19. Tuy nhiên, các ước tính cụ thể có biên độ rất rộng, dao động từ dưới 3% (khi chẩn đoán theo tiêu chí DSM-5 đầy đủ) đến trên 50% (khi sàng lọc triệu chứng cận lâm sàng) — phản ánh sự khác biệt căn bản giữa công cụ chẩn đoán lâm sàng và thang đo sàng lọc dân số.'),

    ('P', 'Trên dữ liệu quy mô lớn, khảo sát quốc gia của Xu và cộng sự (2021) tại Hà Nam, Trung Quốc trên 373.216 học sinh trung học bằng thang GAD-7 cho tỷ lệ triệu chứng lo âu chung 9,89%, với học sinh trung học cơ sở (10,85%) cao hơn trung học phổ thông (8,08%) khi tái tính từ bảng dữ liệu gốc. Chen và cộng sự (2023) trên mẫu 63.205 học sinh trung học tại Tứ Xuyên báo cáo tỷ lệ có trọng số 13,9% (khoảng tin cậy 95% 11,2-17,0%) cũng bằng GAD-7. Tại Anh, phân tích dữ liệu cohort của Fassi và cộng sự (2025) trên 3.340 vị thành niên 11-19 tuổi ghi nhận kích thước hiệu ứng tổng hợp g = 0,46 cho các vấn đề nội hóa nói chung và g = 0,62 riêng cho lo âu. Khảo sát quy mô rất lớn của Brunborg và cộng sự (2025) trên 979.043 phản hồi của thanh thiếu niên Na Uy giai đoạn 2011-2024 cho thấy mức độ căng thẳng tâm thần (bao gồm lo âu) tăng liên tục với hệ số chuẩn hóa β giải thích bởi mức không hài lòng với trường học đạt 0,40-0,44 — yếu tố mạnh nhất trong các yếu tố giải thích xu hướng.'),

    ('P', 'Tại Việt Nam, các nghiên cứu sử dụng nhiều công cụ và cấu hình mẫu khác nhau dẫn đến biên độ ước tính rất rộng. Khảo sát đại diện quốc gia V-NAMHS (Viện Xã hội học và cộng sự, 2022) trên 5.996 cặp cha mẹ — vị thành niên 10-17 tuổi tại 38 tỉnh, sử dụng công cụ chẩn đoán DISC-5 theo DSM-5, đưa ra tỷ lệ rối loạn lo âu đạt ngưỡng chẩn đoán 2,3% — cao nhất trong sáu rối loạn tâm thần được khảo sát; nếu mở rộng sang nhóm có vấn đề sức khỏe tâm thần (gồm triệu chứng cận lâm sàng có suy giảm chức năng), tỷ lệ này lên đến 21,7%. Trong khi đó, các khảo sát học đường bằng thang sàng lọc cho biên độ rộng hơn nhiều. Phạm Thị Thu Hoa và cộng sự (2024) trên 3.910 học sinh trung học phổ thông Hà Nội bằng thang GAD-7 ghi nhận 40,6% có nguy cơ rối loạn lo âu — trong đó 23,9% nhẹ, 10,9% vừa và 5,8% nặng. Hoàng Trung Học và Nguyễn Thùy Dung (2025) trên mẫu phân tích 8.389 học sinh tại 6 tỉnh (mẫu tuyển 8.473) bằng DASS-21 báo cáo tỷ lệ lo âu 41,5% trong thời kỳ COVID-19 và giảm còn 25,4% sau đại dịch. Trần Hồ Vĩnh Lộc và cộng sự (2024) trên 976 học sinh trung học phổ thông tại Thành phố Hồ Chí Minh bằng DASS-Y cho tỷ lệ lo âu chung tương tự. Ngô Anh Vinh và cộng sự (2024) trên 845 học sinh dân tộc thiểu số nội trú tỉnh Lạng Sơn bằng DASS-21 ghi nhận tỷ lệ lo âu cao nhất 54,4%, cao hơn cả tỷ lệ stress (24,7%) và xấp xỉ trầm cảm (59,0%) — phản ánh đặc thù dễ tổn thương ở nhóm dân tộc thiểu số. Trúc Thanh Thái và cộng sự (2026) trên 2.631 học sinh từ 4 trường trung học phổ thông và 4 trung tâm giáo dục thường xuyên tại Thành phố Hồ Chí Minh ghi nhận tỷ lệ triệu chứng lo âu 50,3%. Trần Thị Mỵ Lương (2020) trên 540 học sinh trung học phổ thông Chuyên bằng DASS-42 báo cáo tỷ lệ thấp hơn đáng kể, 14,2% — trong đó khối 11 chiếm 48,1% trong 77 trường hợp lo âu được phát hiện.'),

    ('P', 'Về khác biệt giới tính, các nghiên cứu quốc tế nhất quán ghi nhận tỷ lệ ở học sinh nữ cao hơn nam khoảng 1,5-2 lần. Tại Việt Nam, xu hướng này cũng được khẳng định trong khảo sát của Phạm Thị Thu Hoa và cộng sự (2024) cũng như Trần Hồ Vĩnh Lộc và cộng sự (2024). Một số ít nghiên cứu báo cáo hướng ngược lại — như nghiên cứu của Nguyễn Danh Lâm và cộng sự (2022) tại Yên Định, Thanh Hóa — nhưng đây là ngoại lệ với mẫu nhỏ và bối cảnh đặc thù, không bác bỏ xu hướng chung. Đáng lưu ý là V-NAMHS không tìm thấy khác biệt có ý nghĩa thống kê giữa hai giới ở mức rối loạn DSM-5 đầy đủ, gợi ý rằng khác biệt giới có thể rõ hơn ở mức triệu chứng cận lâm sàng so với mức rối loạn lâm sàng.'),

    ('P', 'Sự khác biệt rất lớn giữa các ước tính (từ 2,3% theo DSM-5 đến trên 50% theo thang sàng lọc) đặt ra vấn đề về cách diễn giải và so sánh kết quả giữa các nghiên cứu. Hai yếu tố chính giải thích biên độ rộng này: (i) loại công cụ — chẩn đoán lâm sàng (DISC-5) so với thang sàng lọc dân số (GAD-7, DASS-21, RCADS); (ii) ngưỡng điểm cắt — một số nghiên cứu sử dụng ngưỡng quá thấp dẫn đến tỷ lệ "lo âu" rất cao mà thực tế chỉ phản ánh triệu chứng cận lâm sàng. Đối với thiết kế nghiên cứu hiện tại trên học sinh trung học cơ sở Việt Nam, lựa chọn công cụ phù hợp và ngưỡng cắt được thẩm định trên dân số Việt Nam là điều kiện then chốt để có ước tính đáng tin cậy. Đây cũng là một khoảng trống lớn ở Việt Nam: hiện chưa có một bộ thang đo lo âu cho trẻ em — vị thành niên được chuẩn hóa tâm trắc toàn diện cho dân số Việt Nam, kèm ngưỡng cắt riêng.'),

    ('P', 'Mở rộng so sánh quốc tế cho thấy biên độ tỷ lệ tương tự ở các khu vực có đặc thù xã hội — kinh tế khác nhau. Nakie và cộng sự (2022) trên 643 học sinh trung học phổ thông tại Ethiopia bằng DASS-21 báo cáo tỷ lệ lo âu 38,9%, gắn liền với các yếu tố nguy cơ kinh tế — gia đình. Bhardwaj và cộng sự (2020) trên 288 học sinh trung học phổ thông tại Chandigarh, Ấn Độ bằng DASS-21 ghi nhận tỷ lệ rất cao là 81,9% có lo âu (trong đó 73,2% từ mức trung bình trở lên), một con số bất thường có thể phản ánh ngưỡng cắt thấp hoặc đặc thù mẫu áp lực học cao. Alharbi và cộng sự (2019) trên 366 học sinh trung học phổ thông tại vùng Qassim, Ả Rập Saudi bằng GAD-7 báo cáo tỷ lệ 63,1% — cũng cao bất thường so với phần lớn y văn quốc tế. Anderson và cộng sự (2025) trong tổng quan tường thuật về xu hướng gia tăng lo âu ở vị thành niên xác nhận rằng các con số "cao bất thường" thường tập trung ở các nghiên cứu sử dụng thang sàng lọc với ngưỡng cắt không được thẩm định địa phương, trong khi các nghiên cứu sử dụng tiêu chí chẩn đoán đầy đủ ổn định hơn nhiều ở khoảng 5-15%.'),

    ('P', 'Một nghiên cứu so sánh quốc tế đặc biệt đáng lưu ý cho bối cảnh Việt Nam là khảo sát của Jefferies và Ungar (2020) về lo âu xã hội tại bảy quốc gia. Sử dụng thang SIAS (Social Interaction Anxiety Scale) trên thanh niên ở Việt Nam, Thái Lan, Indonesia, Trung Quốc, Hoa Kỳ, Canada và Anh, các tác giả báo cáo tỷ lệ trung bình 36% có lo âu xã hội cho cả bảy quốc gia, trong đó Việt Nam đạt 30,7% — gần với mức trung bình. Thái Lan có tỷ lệ cao nhất 41%, Indonesia thấp nhất 22,9%. Phát hiện này cho thấy lo âu xã hội — một dạng ít được khảo sát riêng ở học sinh trung học cơ sở Việt Nam — có khả năng đạt tỷ lệ đáng kể nếu được đo trực tiếp bằng công cụ chuyên biệt.'),

    ('P', 'Trong nhóm các nghiên cứu Việt Nam, ba khảo sát quy mô vừa và lớn được công bố trong năm 2024-2025 cung cấp thêm góc nhìn về biên độ tỷ lệ. Nguyễn Ngọc Bảo Quyên và cộng sự (2025) trên 1.252 học sinh trung học phổ thông Hà Nội bằng thang DASS-21 phiên bản tiếng Việt báo cáo tỷ lệ lo âu chung 38,5%, với nữ cao hơn nam có ý nghĩa thống kê. Nguyễn Danh Lâm và cộng sự (2022) trên 1.024 học sinh trung học phổ thông tại Yên Định, Thanh Hóa — khu vực bán đô thị — báo cáo tỷ lệ thấp hơn 25,8% bằng DASS-21, đồng thời ghi nhận học sinh nam có tỷ lệ cao hơn nữ ở khu vực này — một phát hiện trái ngược với xu hướng chung và đáng được nghiên cứu sâu hơn. Lê Minh T. và cộng sự (2025) trên 600 học sinh phổ thông Long Bình, An Giang bằng DASS-21 báo cáo tỷ lệ 33,2%. Sự đa dạng vùng miền của ba nghiên cứu này — Hà Nội (đô thị), Yên Định (bán đô thị) và An Giang (đồng bằng sông Cửu Long) — cùng với mẫu Lạng Sơn (miền núi dân tộc thiểu số) và Thành phố Hồ Chí Minh (đại đô thị phía Nam) tạo nên bức tranh dịch tễ đa chiều.'),

    ('P', 'Khảo sát của Hồ Thị Trúc Quỳnh (2025) tại Thừa Thiên — Huế đưa thêm một chiều phân tích quan trọng: bên cạnh tỷ lệ phổ biến, tác giả phân tích mối quan hệ giữa lạc quan và mức lo âu, ghi nhận yếu tố lạc quan có vai trò bảo vệ với hệ số β = -0,15 (p < 0,001) — tức là điểm lạc quan cao hơn dự báo lo âu thấp hơn. Đây là một trong ít nghiên cứu Việt Nam tiếp cận yếu tố bảo vệ ngay từ thiết kế ban đầu thay vì chỉ tập trung vào yếu tố nguy cơ. Khảo sát của Đinh Thị Hồng Vân và cộng sự (2021) trên 749 học sinh trung học cơ sở tại Hà Nội và Thành phố Hồ Chí Minh bằng thang đo lo âu tự thiết kế đặc thù cho học đường ghi nhận 91,1% học sinh báo cáo điểm số và thi cử là yếu tố gây lo âu — yếu tố cao nhất trong sáu nhóm được khảo sát, củng cố luận điểm về áp lực học tập là yếu tố nguy cơ hàng đầu.'),

    ('P', 'Tổng hợp các nghiên cứu Việt Nam giai đoạn 2020-2026 cho thấy ba xu hướng đáng chú ý. Thứ nhất, sau đại dịch COVID-19, tỷ lệ lo âu có xu hướng tăng so với giai đoạn trước, dù mức tăng không đồng nhất giữa các khu vực — Hoàng Trung Học và Nguyễn Thùy Dung (2025) ghi nhận tỷ lệ 41,5% trong đại dịch và giảm còn 25,4% sau đại dịch là minh chứng cho hiệu ứng đỉnh tạm thời. Thứ hai, các nghiên cứu sử dụng cùng công cụ (DASS-21) trên các nhóm khác nhau cho ra biên độ tỷ lệ rộng từ 14,2% đến 54,4%, gợi ý rằng đặc thù mẫu (vùng địa lý, lứa tuổi cụ thể, đặc điểm trường) có ảnh hưởng lớn hơn so với công cụ. Thứ ba, mẫu V-NAMHS với chẩn đoán DSM-5 đầy đủ đưa ra tỷ lệ rối loạn (2,3%) thấp hơn nhiều so với tỷ lệ triệu chứng cận lâm sàng (21,7%) — cho thấy phần lớn học sinh "có lo âu" theo các khảo sát học đường thực tế ở mức cận lâm sàng có thể phục hồi tự nhiên, không phải tất cả đều cần can thiệp lâm sàng. Phát hiện này có hàm ý quan trọng cho thiết kế can thiệp: các chương trình phòng ngừa phổ quát hoặc can thiệp chọn lọc cho nhóm có triệu chứng cận lâm sàng có thể đem lại hiệu quả thực tiễn cao hơn so với điều trị lâm sàng đơn lẻ.'),
]

# ============================================================
# 2. MUC DO
# ============================================================
SEC_MUC_DO = [
    ('H3', '1.1.2. Mức độ biểu hiện rối loạn lo âu'),

    ('P', 'Các công cụ sàng lọc phổ biến đều phân tầng mức độ lo âu theo điểm cắt thang đo, với cấu trúc thường gặp gồm bốn mức: bình thường, nhẹ, vừa và nặng (một số thang chia thêm mức "cực kỳ nặng" như DASS-21). Việc phân tầng này có ý nghĩa lâm sàng vì các mức độ khác nhau dẫn tới mức can thiệp khác nhau theo khung sức khỏe tâm thần cộng đồng ba tầng — phổ quát, chọn lọc và chỉ định.'),

    ('P', 'Phân tích dữ liệu Việt Nam cho thấy phân bố mức độ tương đối tương đồng với các nghiên cứu quốc tế. Trong nghiên cứu của Phạm Thị Thu Hoa và cộng sự (2024) trên 3.910 học sinh trung học phổ thông Hà Nội, trong tổng số 40,6% có triệu chứng lo âu, mức độ nhẹ chiếm 23,9%, mức độ vừa 10,9% và mức độ nặng 5,8% — phản ánh dạng phân bố hình kim tự tháp với phần lớn các trường hợp ở mức nhẹ và giảm dần khi tăng mức độ. Trần Thị Mỵ Lương (2020) trên 540 học sinh trung học phổ thông Chuyên bằng DASS-42 báo cáo phân bố tương tự với mức nhẹ 3,5%, vừa 7,2%, nặng 2,4% và rất nặng 1,1%. Mẫu nghiên cứu của Ngô Anh Vinh và cộng sự (2024) trên học sinh dân tộc thiểu số nội trú có phân bố lệch lên các mức cao hơn so với mẫu đô thị, phù hợp với xu hướng dễ tổn thương ở nhóm này.'),

    ('P', 'Phân tầng mức độ khác biệt theo giới tính được ghi nhận nhất quán: học sinh nữ không chỉ có tỷ lệ chung cao hơn nam mà cụ thể là tỷ lệ ở mức độ vừa và nặng cao hơn rõ rệt. Trong nghiên cứu của Trần Thị Mỵ Lương (2020), khối lớp 11 có tỷ lệ lo âu cao nhất, chiếm 48,1% trong tổng số 77 trường hợp được sàng lọc dương tính, đồng thời tập trung ở các mức độ vừa và nặng — gấp 2-3 lần các khối lớp 10 và lớp 12. Đặc điểm này gợi ý lớp 11 là giai đoạn áp lực học tập đặc biệt mạnh trong chu trình trung học phổ thông Việt Nam, với áp lực vừa từ chương trình học vừa từ định hướng nghề nghiệp cận kề.'),

    ('P', 'Một vấn đề về phương pháp luận đáng lưu ý là sự không thống nhất về ngưỡng cắt giữa các phiên bản thang đo và giữa các nghiên cứu. Cùng thang DASS-21 có thể có ba ngưỡng khác nhau được sử dụng trong các bài báo Việt Nam, dẫn đến cùng một bộ dữ liệu có thể cho ra ba tỷ lệ "nhẹ/vừa/nặng" khác nhau. Tương tự, GAD-7 có ngưỡng kinh điển ≥5 cho nhẹ, ≥10 cho vừa, ≥15 cho nặng, nhưng một số nghiên cứu lại sử dụng ngưỡng riêng. Đối với luận án, lựa chọn ngưỡng kinh điển có hỗ trợ tài liệu thẩm định ở dân số Việt Nam (RCADS-25 phiên bản tiếng Việt là một ví dụ) là điều kiện để kết quả có thể so sánh quốc tế.'),

    ('P', 'Phân tích dữ liệu Trung Quốc của Xu và cộng sự (2021) trên 373.216 học sinh — mẫu lớn nhất trong y văn về sàng lọc lo âu vị thành niên — cho phép quan sát phân tầng mức độ ở quy mô đáng tin cậy. Tái tính từ bảng dữ liệu gốc: trong tổng số 36.918 học sinh có triệu chứng lo âu (chiếm 9,89%), phân tầng theo điểm GAD-7 là 23,28% ở mức nhẹ, 6,27% vừa, 2,15% nặng và 1,03% cực kỳ nặng (tính trên tổng dân số mẫu). Khi đổi mẫu số sang chỉ những học sinh dương tính với sàng lọc, phân tầng trong nhóm này là 70,52% nhẹ, 19,00% vừa, 6,52% nặng và 3,12% cực kỳ nặng — kiểu phân bố hình kim tự tháp rõ rệt phù hợp với mô hình dịch tễ chuẩn cho rối loạn sức khỏe tâm thần phổ biến.'),

    ('P', 'Phân tích của Chen và cộng sự (2023) trên 63.205 học sinh tại Tứ Xuyên cũng xác nhận mô hình phân tầng tương tự, đồng thời ghi nhận sự gia tăng tỷ lệ mức độ vừa và nặng ở nhóm học sinh trung học phổ thông so với trung học cơ sở. Phát hiện này được giải thích qua hai cơ chế: (i) thời gian tích lũy stress dài hơn ở học sinh lớp cuối cùng với áp lực thi cử quy mô lớn (cao khảo tại Trung Quốc, thi tốt nghiệp tại Việt Nam); (ii) bước đầu khởi phát các rối loạn lo âu lâm sàng tập trung ở giai đoạn cuối vị thành niên đầu tuổi 18-20.'),

    ('P', 'Khác biệt giới tính trong phân tầng mức độ là một chủ đề được nghiên cứu nhiều nhưng kết luận chưa hoàn toàn nhất quán. Phần lớn các nghiên cứu xác nhận học sinh nữ không chỉ có tỷ lệ chung cao hơn mà còn có tỷ lệ ở mức độ vừa và nặng cao hơn rõ rệt. Bhardwaj và cộng sự (2020) tại Ấn Độ ghi nhận tỷ lệ nữ cao hơn nam ở các mức trung bình trở lên — nhẹ (15,9% nam so với 20,6% nữ), trung bình (29,1% so với 31,0%), nặng (9,1% so với 21,2%) và cực kỳ nặng (2,3% so với 2,7%). Tại Việt Nam, Phạm Thị Thu Hoa và cộng sự (2024) cũng xác nhận xu hướng này, song mức chênh lệch không lớn bằng. Tuy nhiên, V-NAMHS không tìm thấy khác biệt có ý nghĩa thống kê giữa hai giới ở mức rối loạn DSM-5 đầy đủ — gợi ý rằng khác biệt giới có thể rõ hơn ở mức triệu chứng cận lâm sàng so với mức rối loạn lâm sàng.'),

    ('P', 'Khác biệt theo khối lớp cũng được quan sát nhất quán. Trong các nghiên cứu Việt Nam, khối lớp 11 thường được nhận diện là nhóm có tỷ lệ và mức độ lo âu cao nhất, theo đúng kết quả của Trần Thị Mỵ Lương (2020) đã nêu trên. Cơ chế giải thích bao gồm: (i) lớp 11 là giai đoạn áp lực học cao điểm khi học sinh phải chuẩn bị cho năm thi tốt nghiệp; (ii) định hướng nghề nghiệp đặt ra yêu cầu lựa chọn quan trọng; (iii) chuyển giai đoạn tâm lý xã hội từ vị thành niên giữa sang cuối với nhiều thay đổi về bản sắc. Ở mẫu trung học cơ sở, một số nghiên cứu ghi nhận khối lớp 9 có tỷ lệ tăng — gắn với áp lực chuẩn bị thi vào lớp 10 ở các thành phố lớn nơi tỷ lệ chọi cao.'),

    ('P', 'Một yếu tố ít được phân tích nhưng quan trọng là tính ổn định của phân tầng mức độ qua thời gian. Hầu hết nghiên cứu Việt Nam sử dụng thiết kế cắt ngang, đo lo âu tại một thời điểm duy nhất; do đó không thể phân biệt được mức độ lo âu hiện tại có ổn định, đang gia tăng hay đang giảm. Nghiên cứu dọc của Trần Thảo Vi và cộng sự (2024) trên 341 học sinh trung học cơ sở Huế qua 3 năm là một ngoại lệ quý, ghi nhận điểm áp lực học tập (ESSA) tăng từ 46,4 ± 7,6 lên 53,5 ± 10,8 — tức là tăng có ý nghĩa thống kê và liên tục, cùng với xu hướng tăng các triệu chứng nội hóa. Phát hiện này gợi ý rằng tỷ lệ lo âu ở mức độ vừa và nặng quan sát thấy trong các nghiên cứu cắt ngang có thể là điểm cuối của một quá trình tích lũy stress kéo dài qua nhiều năm cấp trung học cơ sở.'),

    ('P', 'Mức độ rối loạn lo âu cũng có liên hệ tương đối nhất quán với suy giảm chức năng — yếu tố quan trọng để chuyển từ "có triệu chứng" sang "có rối loạn cần can thiệp". V-NAMHS ghi nhận trong số 21,7% có vấn đề sức khỏe tâm thần, 67% có suy giảm trong miền gia đình, 47% trong quan hệ với bạn bè và 45,4% trong học tập hoặc công việc. Ở nhóm đạt ngưỡng rối loạn DSM-5 đầy đủ (3,3% tổng mẫu), tỷ lệ suy giảm tăng lên 74,2% (gia đình), 64,1% (học tập) và 63,3% (bạn bè). Đây là dữ liệu định lượng cốt lõi cho việc luận giải về gánh nặng thực tế của lo âu ở vị thành niên Việt Nam — không chỉ đo bằng tỷ lệ mà còn bằng mức độ ảnh hưởng đến đời sống hằng ngày.'),
]

# ============================================================
# 3. BIEU HIEN
# ============================================================
SEC_BIEU_HIEN = [
    ('H3', '1.1.3. Biểu hiện rối loạn lo âu theo phân loại DSM-5'),

    ('P', 'Theo DSM-5 (Hiệp hội Tâm thần học Hoa Kỳ, 2013), nhóm rối loạn lo âu bao gồm chín loại chính, trong đó ba loại phổ biến nhất ở trẻ em — vị thành niên là rối loạn lo âu lan tỏa (Generalized Anxiety Disorder), rối loạn lo âu xã hội (Social Anxiety Disorder) và rối loạn lo âu chia ly (Separation Anxiety Disorder). Ba dạng này có chung đặc điểm lo lắng quá mức và khó kiểm soát, nhưng khác biệt rõ ràng về đối tượng và bối cảnh xuất hiện lo âu, cùng đặc trưng phát triển theo lứa tuổi.'),

    ('P', 'Rối loạn lo âu lan tỏa đặc trưng bởi lo lắng quá mức về nhiều sự kiện hoặc hoạt động — học tập, sức khỏe, tài chính gia đình, các sự kiện trong tương lai — kéo dài ít nhất sáu tháng, kèm theo các triệu chứng cơ thể như căng cơ, mệt mỏi, khó tập trung, dễ cáu kỉnh và rối loạn giấc ngủ. Đây là dạng được khảo sát nhiều nhất trong nghiên cứu vị thành niên Việt Nam — phần lớn các nghiên cứu sử dụng GAD-7 đều đo dạng này. V-NAMHS ghi nhận rối loạn lo âu lan tỏa và ám sợ xã hội cùng chiếm tỷ lệ cao nhất trong nhóm rối loạn lo âu. Tổng quan của Compas và cộng sự (2017) trên 212 nghiên cứu với 80.850 trẻ em — vị thành niên xác nhận đối phó tập trung vào vấn đề có liên hệ ngược chiều và bền vững với triệu chứng lo âu lan tỏa cũng như triệu chứng trầm cảm.'),

    ('P', 'Rối loạn lo âu xã hội đặc trưng bởi sợ hãi hoặc lo lắng rõ rệt trước một hoặc nhiều tình huống xã hội — phát biểu trước lớp, giao tiếp với người lạ, ăn uống nơi công cộng — do lo sợ bị đánh giá tiêu cực. Phân tích mạng lưới của Xian và cộng sự (2024) trên 30 thử nghiệm lâm sàng ngẫu nhiên ở trẻ em — vị thành niên xếp các hình thức liệu pháp nhận thức — hành vi vào vị trí hiệu quả cao nhất cho lo âu xã hội, đặc biệt là liệu pháp qua nền tảng internet (SUCRA = 71,2%). Tại Việt Nam, dạng lo âu xã hội ít được nghiên cứu riêng biệt; phần lớn các khảo sát hiện có sử dụng thang đo lo âu tổng hợp không phân tách được dạng này. Đây là một khoảng trống quan trọng vì lo âu xã hội đặc biệt liên quan đến giai đoạn đầu vị thành niên — thời điểm bắt đầu nhạy cảm cao với phản hồi của bạn đồng đẳng.'),

    ('P', 'Rối loạn lo âu chia ly đặc trưng bởi lo lắng quá mức về sự xa cách với người thân (chủ yếu là cha mẹ) hoặc môi trường gia đình. DSM-IV trước đây chỉ chẩn đoán rối loạn này cho trẻ em và vị thành niên; DSM-5 đã mở rộng cho người lớn được chẩn đoán lần đầu sau 18 tuổi. Tại Việt Nam, rối loạn lo âu chia ly hầu như không được khảo sát riêng ở học sinh trung học cơ sở, mặc dù bối cảnh đặc thù — học sinh phải xa nhà đi học nội trú ở khu vực dân tộc thiểu số (như mẫu của Ngô Anh Vinh và cộng sự, 2024), học sinh có cha mẹ đi làm xa, học sinh chuyển trường — có thể là nhóm có nguy cơ cao cho dạng này.'),

    ('P', 'Nhìn tổng thể, nghiên cứu Việt Nam hiện tập trung vào lo âu tổng quát (chủ yếu qua GAD-7 hoặc các tiểu thang trong DASS), trong khi lo âu xã hội và lo âu chia ly là hai khoảng trống đáng kể. Việc bổ sung khảo sát chuyên biệt cho hai dạng còn lại — sử dụng các công cụ chuyên biệt như Spence Children Anxiety Scale (SCAS) hoặc Revised Child Anxiety and Depression Scale (RCADS) đã có phiên bản tiếng Việt — sẽ giúp bức tranh dịch tễ ở học sinh trung học cơ sở Việt Nam đầy đủ hơn.'),

    ('P', 'Biểu hiện chi tiết của rối loạn lo âu lan tỏa ở vị thành niên có những đặc điểm riêng so với người trưởng thành. Kendall (1994) — trong nghiên cứu lâm sàng nền tảng đặt cơ sở cho chương trình can thiệp Coping Cat — mô tả ba thành phần cốt lõi của lo âu lan tỏa ở trẻ em 9-13 tuổi: (i) cảm giác sợ hãi và lo lắng cảm xúc (lo cho tương lai, lo cho an toàn của bản thân và người thân); (ii) các biểu hiện cơ thể (căng cơ, đau đầu, mệt mỏi, rối loạn giấc ngủ); (iii) các biểu hiện hành vi (né tránh các tình huống, đòi hỏi sự yên tâm nhiều lần, kiểm tra lặp lại). Ba thành phần này được tích hợp trong các thang đo chuẩn hóa cho trẻ em — vị thành niên như RCADS và SCARED. Tại Việt Nam, dạng lo âu này được khảo sát phổ biến nhất nhưng thường không phân tách rõ ba thành phần — phần lớn nghiên cứu chỉ báo cáo điểm tổng, làm mất thông tin về cấu trúc lo âu của từng học sinh.'),

    ('P', 'Tiêu chí chẩn đoán DSM-5 cho rối loạn lo âu lan tỏa yêu cầu lo lắng quá mức trong ít nhất sáu tháng, khó kiểm soát, kèm theo ít nhất ba trong sáu triệu chứng cơ thể — căng thẳng, mệt mỏi dễ dàng, khó tập trung, cáu kỉnh, căng cơ và rối loạn giấc ngủ. Ở vị thành niên, DSM-5 chỉ yêu cầu một trong sáu triệu chứng (so với ba ở người trưởng thành) — phản ánh khác biệt phát triển trong cách biểu hiện. Tại Việt Nam, V-NAMHS (Viện Xã hội học và cộng sự, 2022) là nghiên cứu duy nhất sử dụng tiêu chí DSM-5 đầy đủ qua DISC-5 cho rối loạn lo âu lan tỏa ở 10-17 tuổi. Các thang đo khác như GAD-7 chỉ là sàng lọc — không thay thế chẩn đoán lâm sàng.'),

    ('P', 'Rối loạn lo âu xã hội ở vị thành niên có hai đặc trưng phát triển quan trọng. Thứ nhất, đây là dạng có tuổi khởi phát đặc trưng vào giai đoạn đầu vị thành niên (11-13 tuổi) — trùng với lứa tuổi học sinh trung học cơ sở Việt Nam. Thứ hai, biểu hiện lo âu xã hội ở lứa tuổi này thường gắn với các tình huống cụ thể của trường học: phát biểu trước lớp, làm bài kiểm tra miệng, giao tiếp với thầy cô, tham gia hoạt động nhóm, ăn uống tại căng tin. Praptomojati và cộng sự (2024) trong tổng quan hệ thống các phiên bản liệu pháp nhận thức — hành vi thích nghi văn hóa cho rối loạn lo âu tại Đông Nam Á nhận định rằng lo âu xã hội ở khu vực này có một số đặc thù văn hóa quan trọng — đặc biệt là vai trò của "thể diện" (face) và lo lắng về việc làm mất uy tín gia đình hoặc dòng họ — cần được phản ánh trong công cụ đo và can thiệp.'),

    ('P', 'Tại Việt Nam, dạng lo âu xã hội chưa được nghiên cứu riêng biệt ở học sinh trung học cơ sở; phần lớn dữ liệu hiện có gom dạng này vào điểm lo âu tổng hợp. Hai ngoại lệ đáng chú ý: khảo sát so sánh quốc tế của Jefferies và Ungar (2020) đã trích ở mục 1.1.1 ghi nhận tỷ lệ lo âu xã hội tại Việt Nam đạt 30,7% — một con số đáng kể cho lứa tuổi thanh niên; và phân tích của Đinh Thị Hồng Vân và cộng sự (2021) trên 749 học sinh trung học cơ sở Hà Nội + Thành phố Hồ Chí Minh ghi nhận giao tiếp với thầy cô là yếu tố gây lo âu được nêu bởi 42,9% học sinh và quan hệ với bạn bè trong lớp là 40,6% — hai chỉ báo gián tiếp về lo âu xã hội. Phân tích mạng lưới của Xian và cộng sự (2024) trên 30 thử nghiệm lâm sàng ngẫu nhiên cho thấy các hình thức liệu pháp nhận thức — hành vi đặc biệt qua internet là can thiệp có bằng chứng mạnh nhất cho rối loạn lo âu xã hội ở trẻ em — vị thành niên (chỉ số SUCRA = 71,2%).'),

    ('P', 'Rối loạn lo âu chia ly có lịch sử thay đổi tiêu chí chẩn đoán đáng chú ý. DSM-IV (1994) chỉ chẩn đoán rối loạn này cho trẻ em và vị thành niên, với yêu cầu khởi phát trước 18 tuổi. DSM-5 (2013) đã mở rộng phạm vi: bỏ giới hạn tuổi khởi phát, cho phép chẩn đoán ở người trưởng thành mới được phát hiện rối loạn này lần đầu, với yêu cầu thời gian triệu chứng ít nhất 4 tuần ở trẻ em và 6 tháng ở người trưởng thành. Biểu hiện kinh điển ở vị thành niên bao gồm: lo lắng dữ dội về việc xa cha mẹ hoặc nhà; ám ảnh về tai nạn có thể xảy đến với người thân; từ chối đi học hoặc ngủ qua đêm xa nhà; các triệu chứng cơ thể (đau bụng, đau đầu) khi phải xa người thân; ác mộng về chủ đề chia ly.'),

    ('P', 'Mặc dù tỷ lệ rối loạn lo âu chia ly thường được báo cáo thấp hơn lo âu lan tỏa và lo âu xã hội ở vị thành niên nói chung, các nhóm có hoàn cảnh đặc thù có thể có tỷ lệ cao hơn nhiều. Tại Việt Nam, có ba nhóm cần được nghiên cứu chuyên biệt cho dạng này. Nhóm thứ nhất là học sinh dân tộc thiểu số học nội trú xa nhà — như mẫu của Ngô Anh Vinh và cộng sự (2024) tại Lạng Sơn với học sinh phải xa gia đình trong tuổi 10-18, có 70,7% là nữ và 67,9% sống tại ký túc xá — đây là nhóm có nguy cơ đặc biệt cho dạng lo âu chia ly nhưng chưa được khảo sát chuyên biệt. Nhóm thứ hai là học sinh có cha hoặc mẹ đi làm xa (ví dụ đi làm tại các tỉnh khác hoặc xuất khẩu lao động); nhóm này đặc biệt phổ biến ở khu vực nông thôn Việt Nam. Nhóm thứ ba là học sinh chuyển trường — đặc biệt khi chuyển từ tiểu học vào trung học cơ sở hoặc khi gia đình di chuyển. Hiện tại, ba nhóm này hầu như chưa có dữ liệu nghiên cứu định lượng về rối loạn lo âu chia ly.'),

    ('P', 'Tỷ lệ đồng diễn (comorbidity) giữa ba dạng rối loạn lo âu là một đặc điểm quan trọng cần được lưu ý. Trong các nghiên cứu sử dụng thang đo phân tách như RCADS hoặc SCARED, tỷ lệ học sinh đáp ứng ngưỡng cho hai dạng trở lên thường đạt 40-50% trong tổng số có ít nhất một dạng. V-NAMHS ghi nhận trong 5.996 cặp khảo sát, dưới 1% có hai rối loạn tâm thần đồng diễn theo DSM-5 đầy đủ, nhưng tỷ lệ này tăng đáng kể nếu xét cả triệu chứng cận lâm sàng. Đối với thiết kế nghiên cứu trên học sinh trung học cơ sở, việc sử dụng công cụ phân tách (như RCADS-25 hoặc SCARED) thay vì thang tổng hợp (như GAD-7) cho phép quan sát chính xác cấu trúc đồng diễn và đưa ra ước tính riêng cho từng dạng — một thông tin quan trọng cho việc thiết kế can thiệp phân tầng.'),
]

# ============================================================
# 4. YEU TO NGUY CO (TOM TAT + REF BAI 1)
# ============================================================
SEC_YTNC = [
    ('H3', '1.1.4. Yếu tố nguy cơ rối loạn lo âu ở học sinh trung học cơ sở'),

    ('P', 'Phân tích chi tiết về các yếu tố nguy cơ rối loạn lo âu ở học sinh trung học cơ sở được tác giả trình bày trong Bài 1 — Yếu tố nguy cơ rối loạn lo âu ở học sinh trung học cơ sở (đính kèm luận án). Bài này hệ thống hóa 21 nghiên cứu trong và ngoài nước (giai đoạn 2017-2026) theo năm nhóm yếu tố nguy cơ chính, đặt trong khung tiếp cận sinh thái xã hội ba tầng (cá nhân — gia đình/bạn bè — trường học/xã hội). Tổng quan này chỉ tóm tắt năm nhóm và các phát hiện trọng tâm.'),

    ('P', 'Nhóm thứ nhất — áp lực học tập — là yếu tố nguy cơ được nghiên cứu nhiều nhất tại Việt Nam, với khoảng hai phần ba số nghiên cứu xác nhận liên hệ thuận chiều giữa áp lực học và triệu chứng lo âu. Phân tích tổng quan của Pascoe, Hetrick và Parker (2020) cùng đánh giá hệ thống của Jagiello và cộng sự (2025) trên 31 nghiên cứu can thiệp từ 13 quốc gia ghi nhận liệu pháp nhận thức — hành vi là can thiệp có bằng chứng mạnh nhất để giảm áp lực học tập gây ra ở học sinh trung học. Tại Việt Nam, nghiên cứu dọc của Trần Thảo Vi và cộng sự (2024) trên 341 học sinh trung học cơ sở Huế qua ba năm 2018-2021 ghi nhận điểm áp lực học tập (ESSA) tăng từ 46,4 lên 53,5 — gắn liền với xu hướng tăng lo âu.'),

    ('P', 'Nhóm thứ hai — nghiện điện thoại thông minh và mạng xã hội — là yếu tố mới nổi, đặc biệt rõ rệt từ sau đại dịch COVID-19. Khảo sát quy mô rất lớn của Brunborg và cộng sự (2025) tại Na Uy là một trong những bằng chứng định lượng mạnh nhất, cùng phân tích của Fassi và cộng sự (2025) tại Anh với kích thước hiệu ứng g = 0,46 cho các vấn đề nội hóa. Tại Việt Nam, nghiên cứu của Hoàng Trung Học và Nguyễn Thùy Dung (2025) ghi nhận thời lượng sử dụng thiết bị có liên hệ thuận với điểm lo âu, song chưa có thang đo nghiện điện thoại được chuẩn hóa cho học sinh trung học cơ sở Việt Nam.'),

    ('P', 'Nhóm thứ ba và thứ tư — bắt nạt thể chất và bắt nạt bằng lời/bắt nạt mạng — là hai nhóm yếu tố nguy cơ học đường nổi bật. Phân tích tổng hợp của Moore và cộng sự (2017) trên 165 nghiên cứu xác nhận quan hệ định lượng giữa bị bắt nạt và lo âu với tỷ số chênh tổng hợp 1,77 (khoảng tin cậy 95% 1,34-2,33). Tổng quan dọc của Lee và cộng sự (2026) trên 27 nghiên cứu cho hệ số tương quan r = 0,23 (khoảng tin cậy 95% 0,19-0,27) — yếu nhưng nhất quán. Tại Việt Nam, Phạm Thị Ngọc và cộng sự (2024) trên 420 học sinh Vĩnh Bảo, Hải Phòng ghi nhận tỷ số chênh đã hiệu chỉnh AOR = 2,42 (khoảng tin cậy 95% 1,03-5,71) cho bạo lực học đường và AOR = 2,25 cho không hòa đồng với bạn bè.'),

    ('P', 'Nhóm thứ năm — lòng tự trọng thấp — là cấu trúc nội tại có vai trò trung gian giữa các yếu tố môi trường và biểu hiện lo âu. Tổng quan dọc của Sowislo và Orth (2013) trên 18 mẫu lo âu xác nhận hệ số β = -0,10 cho liên hệ tự trọng — lo âu — tức là tự trọng thấp dự báo lo âu cao hơn ở các thời điểm tiếp theo. Phạm Sỹ Tiến và cộng sự (2024) trên 546 vị thành niên tại các cơ sở bảo trợ xã hội ghi nhận chất lượng chăm sóc tình cảm có liên hệ ngược chiều với điểm sức khỏe tâm thần (β = -0,40), củng cố vai trò của nhóm cấu trúc nội tại — quan hệ trong việc bảo vệ trước rối loạn lo âu.'),

    ('P', 'Bài 1 phân tích chi tiết từng nhóm, các nghiên cứu Việt Nam và quốc tế trong cùng chủ đề, và đề xuất năm khoảng trống nghiên cứu chính cho giai đoạn 2026-2030. Trong luận án này, các yếu tố nguy cơ được khảo sát thực nghiệm bao gồm áp lực học tập, nghiện điện thoại, bắt nạt và lòng tự trọng thấp — tương ứng với năm nhóm đã nêu.'),

    ('P', 'Mở rộng phân tích về áp lực học tập như yếu tố nguy cơ, tổng quan tường thuật của Pascoe, Hetrick và Parker (2020) trên dữ liệu OECD từ 72 quốc gia với 540.000 học sinh ghi nhận trung bình 66% học sinh báo cáo căng thẳng về điểm số, 59% lo lắng về kiểm tra ngay cả khi đã chuẩn bị tốt, và 37% cảm thấy căng thẳng khi học tập — gấp đôi so với khoảng 18% được báo cáo trong thập niên 1990. Tại Việt Nam, áp lực học tập có ba thành phần được nghiên cứu nhiều nhất: áp lực thi cử (đặc biệt thi vào lớp 10 và thi tốt nghiệp), kỳ vọng của cha mẹ, và lo lắng về điểm số hằng ngày. Đinh Thị Hồng Vân và cộng sự (2021) trên 749 học sinh trung học cơ sở Hà Nội + Thành phố Hồ Chí Minh ghi nhận điểm số và thi cử là yếu tố gây lo âu hàng đầu, được 91,1% học sinh nêu — cao hơn rõ rệt so với 5 nhóm yếu tố trường học khác. Áp lực này đặc biệt mạnh ở giai đoạn cuối trung học cơ sở khi học sinh chuẩn bị thi vào lớp 10 ở các thành phố lớn.'),

    ('P', 'Đối với nhóm nghiện điện thoại thông minh và mạng xã hội, bằng chứng từ các nghiên cứu quy mô lớn xác nhận đây là yếu tố nguy cơ độc lập có ý nghĩa thống kê sau khi đã hiệu chỉnh các yếu tố nhân khẩu học. Brunborg và cộng sự (2025) trên 979.043 phản hồi tại Na Uy giai đoạn 2011-2024 cho thấy thời lượng sử dụng mạng xã hội tăng giải thích một phần đáng kể (đặc biệt ở nữ giới) về xu hướng gia tăng căng thẳng tâm thần. Fassi và cộng sự (2025) trên 3.340 vị thành niên Anh ghi nhận kích thước hiệu ứng tổng hợp g = 0,46 cho các vấn đề nội hóa và g = 0,62 riêng cho lo âu khi so sánh nhóm sử dụng nhiều với nhóm sử dụng ít. Tại Việt Nam, Hoàng Trung Học và Nguyễn Thùy Dung (2025) ghi nhận thời lượng sử dụng thiết bị có liên hệ thuận với điểm lo âu trên mẫu gần 8.500 thanh thiếu niên — bằng chứng định lượng đầu tiên ở quy mô lớn cho mối liên hệ này tại Việt Nam.'),

    ('P', 'Bắt nạt thể chất và bắt nạt bằng lời/bắt nạt mạng là hai nhóm yếu tố nguy cơ học đường có mối liên hệ định lượng đặc biệt mạnh với lo âu. Bên cạnh kết quả của Moore và cộng sự (2017) và Lee và cộng sự (2026) đã trích trên, các nghiên cứu Việt Nam cũng cho dữ liệu hỗ trợ. Phạm Thị Ngọc và cộng sự (2024) tại Vĩnh Bảo, Hải Phòng phân tích hồi quy đa biến cho thấy bị bắt nạt là yếu tố nguy cơ độc lập với tỷ số chênh đã hiệu chỉnh AOR = 2,42 (khoảng tin cậy 95% 1,03-5,71); không hòa đồng với bạn (một chỉ báo cho bắt nạt bằng lời và cô lập xã hội) có AOR = 2,25. Trần Hồ Vĩnh Lộc và cộng sự (2024) trên 976 học sinh trung học phổ thông Thành phố Hồ Chí Minh sử dụng tỷ số tỷ lệ hiện mắc đã hiệu chỉnh APR = 2,82 cho mối quan hệ giữa bị bắt nạt và rối loạn lo âu — kích thước hiệu ứng lớn nhất trong các yếu tố nguy cơ được khảo sát.'),

    ('P', 'Ngô Anh Vinh và cộng sự (2024) trên 845 học sinh dân tộc thiểu số nội trú Lạng Sơn cung cấp dữ liệu về một dạng đặc biệt của yếu tố nguy cơ học đường: chất lượng quan hệ bạn bè. Khi học sinh báo cáo có "quan hệ bạn bè không tốt" hoặc "trung bình", điểm lo âu, stress và trầm cảm đều tăng có ý nghĩa thống kê. Đồng thời, số trải nghiệm bất lợi thời thơ ấu (Adverse Childhood Experiences — ACEs) có hệ số chuẩn hóa 0,28 với điểm lo âu — gợi ý rằng các yếu tố nguy cơ tích lũy từ tuổi nhỏ vẫn có tác động ở giai đoạn vị thành niên.'),

    ('P', 'Lòng tự trọng thấp là cấu trúc nội tại có cơ chế hoạt động khác với bốn nhóm yếu tố môi trường nêu trên — nó là một biến trung gian, vừa chịu ảnh hưởng từ các yếu tố môi trường vừa dự báo lo âu. Tổng quan dọc của Sowislo và Orth (2013) trên 18 mẫu lo âu xác nhận hệ số β = -0,10 cho liên hệ tự trọng dự báo lo âu, đồng thời ghi nhận hệ số ngược (lo âu dự báo tự trọng) đạt -0,08 — gần như đối xứng. Tại Việt Nam, Phạm Sỹ Tiến và cộng sự (2024) trên 546 vị thành niên tại các cơ sở bảo trợ xã hội ghi nhận chất lượng chăm sóc tình cảm có liên hệ ngược chiều với điểm sức khỏe tâm thần (β = -0,40), một kích thước hiệu ứng đáng kể, củng cố vai trò của nhóm cấu trúc nội tại — quan hệ trong việc bảo vệ trước rối loạn lo âu. Tuy nhiên, hầu như chưa có nghiên cứu Việt Nam đo lòng tự trọng bằng thang chuẩn hóa Rosenberg trên học sinh trung học cơ sở — đây là một khoảng trống công cụ đã được nêu ở mục 1.1.1.'),

    ('P', 'Tương tác giữa các nhóm yếu tố nguy cơ là một chủ đề được Bài 1 phân tích chi tiết. Một số mẫu tương tác đáng chú ý: (i) áp lực học tập × bắt nạt — học sinh chịu áp lực học cao đồng thời bị bắt nạt có nguy cơ lo âu cao gấp 3-4 lần so với học sinh chỉ chịu một yếu tố; (ii) nghiện điện thoại × lòng tự trọng thấp — nghiện điện thoại thường đi kèm tự trọng thấp, tạo vòng xoắn tiêu cực với lo âu xã hội; (iii) bắt nạt mạng × bắt nạt thể chất — học sinh bị bắt nạt cả hai dạng có nguy cơ cao hơn rất nhiều so với tổng số học sinh chỉ bị một dạng. Phân tích tương tác này có hàm ý quan trọng cho thiết kế can thiệp: chương trình phòng ngừa hiệu quả cần đồng thời nhắm tới nhiều yếu tố nguy cơ thay vì tập trung vào một.'),

    ('P', 'Cuối cùng, một số yếu tố nguy cơ được nêu trong y văn quốc tế chưa được nghiên cứu đầy đủ ở Việt Nam, bao gồm: đặc điểm nhân cách (như neuroticism cao), khí chất (như nhạy cảm cao với phần thưởng và trừng phạt), tiền sử rối loạn tâm thần ở cha mẹ, và bạo lực gia đình. Đây là các nhóm yếu tố mà thầy phản biện đã chỉ ra ở Mục 19 — chưa được khảo sát trong luận án hiện tại. Việc bổ sung các nhóm này trong các nghiên cứu kế tiếp là cần thiết để hoàn thiện mô hình yếu tố nguy cơ cho học sinh trung học cơ sở Việt Nam.'),
]

# ============================================================
# 5. YEU TO BAO VE (CHI TIET)
# ============================================================
SEC_YTBV = [
    ('H3', '1.1.5. Yếu tố bảo vệ trước rối loạn lo âu ở học sinh trung học cơ sở'),

    ('P', 'Khái niệm yếu tố bảo vệ trong nghiên cứu sức khỏe tâm thần vị thành niên gắn với khung khả năng phục hồi của Masten (2014) — chỉ những đặc điểm cá nhân, mối quan hệ hoặc bối cảnh giúp giảm khả năng phát triển rối loạn tâm thần trong điều kiện có nguy cơ. Đối với rối loạn lo âu, các yếu tố bảo vệ được nghiên cứu nhiều nhất gồm năm nhóm: lòng tự trọng cao, gắn bó với trường học, hỗ trợ của cha mẹ, hỗ trợ từ bạn bè, và biện pháp ứng phó hiệu quả. Năm nhóm này đan xen nhau và cùng tạo nên một mạng lưới bảo vệ — yếu tố nội tại cá nhân kết hợp với mạng lưới quan hệ xung quanh.'),

    ('H3', '1.1.5.1. Lòng tự trọng'),

    ('P', 'Lòng tự trọng là cảm giác đánh giá của cá nhân về giá trị bản thân, được Rosenberg (1965) phát triển khái niệm và xây dựng thang đo Rosenberg Self-Esteem Scale — công cụ phổ biến nhất trong nghiên cứu vị thành niên. Masten (2014) xếp lòng tự trọng vào nhóm các yếu tố nội tại bảo vệ trẻ em trước nghịch cảnh, cùng với khả năng tự điều tiết cảm xúc và niềm tin vào năng lực bản thân.'),

    ('P', 'Tổng quan của Sowislo và Orth (2013) trên 95 mẫu (gồm 77 mẫu trầm cảm và 18 mẫu lo âu) là bằng chứng định lượng quan trọng nhất hỗ trợ vai trò của lòng tự trọng như yếu tố bảo vệ. Đối với lo âu, mô hình tổn thương được xác nhận với hệ số chuẩn hóa β = -0,10 cho liên hệ tự trọng dự báo lo âu ở các thời điểm sau, trong khi hệ số ngược (lo âu dự báo tự trọng) đạt β = -0,08 — gần như đối xứng, gợi ý cơ chế hai chiều. Đây là bằng chứng để xếp lòng tự trọng vào nhóm yếu tố bảo vệ, dù chiều mạnh hơn của hiệu ứng có thể khác nhau giữa các nhóm dân số.'),

    ('P', 'Tại Việt Nam, lòng tự trọng được nghiên cứu chủ yếu qua bản dịch tiếng Việt của Rosenberg Self-Esteem Scale. Tuy nhiên, các phiên bản dịch hiện có chưa được thẩm định tâm trắc đầy đủ trên mẫu học sinh trung học cơ sở — đa số nghiên cứu sử dụng bản dịch một chiều không qua quy trình back-translation và pilot. Đây là một trong những khoảng trống về công cụ đo lòng tự trọng tại Việt Nam.'),

    ('H3', '1.1.5.2. Gắn bó với trường học'),

    ('P', 'Gắn bó trường học (school connectedness) là cảm giác thuộc về và được hỗ trợ tại trường — bao gồm quan hệ tích cực với thầy cô và bạn bè, cảm giác an toàn về thể chất và tâm lý tại trường, và sự tham gia tích cực vào các hoạt động học tập và ngoại khóa. Khung tiếp cận của Cai và cộng sự (2025) trong phân tích tổng hợp 38 thử nghiệm về chương trình tăng cường khả năng phục hồi tại trường xác nhận các chương trình tích hợp tăng cường gắn bó trường học có hiệu ứng tổng hợp nhỏ tới vừa trên năng lực phục hồi của học sinh — một cấu trúc bảo vệ có liên quan đến việc giảm nguy cơ rối loạn lo âu.'),

    ('P', 'Cơ chế bảo vệ của gắn bó trường học hoạt động qua ba kênh chính. Thứ nhất, cảm giác thuộc về làm giảm nhận thức về cô lập xã hội — yếu tố thường đi cùng với lo âu xã hội ở vị thành niên. Thứ hai, quan hệ tích cực với thầy cô tạo nguồn hỗ trợ tinh thần ngoài gia đình, đặc biệt quan trọng với học sinh có quan hệ gia đình căng thẳng. Thứ ba, tham gia vào hoạt động học tập và ngoại khóa giúp cấu trúc thời gian và giảm thời lượng sử dụng thiết bị số không kiểm soát — gián tiếp bảo vệ trước nhóm yếu tố nguy cơ về nghiện smartphone.'),

    ('P', 'Tại Việt Nam, khái niệm gắn bó trường học mới được du nhập gần đây và hầu như chưa có thang đo riêng được chuẩn hóa cho học sinh trung học cơ sở. Bộ thang Psychological Sense of School Membership (PSSM) là một lựa chọn quốc tế có khả năng thích nghi, nhưng chưa được kiểm định trên dân số Việt Nam. Khảo sát của Đinh Thị Hồng Vân và cộng sự (2021) trên 749 học sinh trung học cơ sở Hà Nội và Thành phố Hồ Chí Minh ghi nhận yếu tố trường học (gồm gắn bó với bạn bè, giáo viên, môi trường) có ảnh hưởng đáng kể đến mức lo âu, dù chưa sử dụng công cụ chuyên biệt cho gắn bó trường học.'),

    ('H3', '1.1.5.3. Hỗ trợ của cha mẹ'),

    ('P', 'Hỗ trợ của cha mẹ — bao gồm sự ấm áp, đáp ứng nhạy cảm với cảm xúc của con, hỗ trợ học tập và sẵn sàng lắng nghe — là yếu tố bảo vệ kinh điển trong nghiên cứu sức khỏe tâm thần trẻ em — vị thành niên. Mô hình giao thức can thiệp của Barrett, Dadds và Rapee (1996) tại Úc đặt nền tảng cho hướng tích hợp gia đình vào chương trình điều trị rối loạn lo âu vị thành niên, ghi nhận nhóm có cha mẹ tham gia đạt tỷ lệ không còn chẩn đoán cao hơn nhóm CBT đơn thuần (84% so với 57%) sau 12 tháng theo dõi — bằng chứng gián tiếp xác nhận vai trò bảo vệ của hỗ trợ cha mẹ.'),

    ('P', 'Phạm Sỹ Tiến và cộng sự (2024) trên 546 vị thành niên tại các cơ sở bảo trợ xã hội Việt Nam ghi nhận chất lượng chăm sóc tình cảm — một thành tố của hỗ trợ cha mẹ — có hệ số β = -0,40 với điểm sức khỏe tâm thần. Đây là bằng chứng định lượng mạnh từ Việt Nam xác nhận vai trò bảo vệ của sự ấm áp gia đình. Nghiên cứu của Hoàng Trung Học và cộng sự (2025) cũng nhận diện "mối quan hệ cha mẹ — con" là yếu tố ảnh hưởng quan trọng đến sức khỏe tâm thần học sinh thanh thiếu niên Việt Nam, dù chưa lượng hóa đầy đủ.'),

    ('P', 'Bối cảnh văn hóa Việt Nam đặt ra cả thuận lợi lẫn thách thức cho việc khai thác hỗ trợ cha mẹ như yếu tố bảo vệ. Thuận lợi nằm ở mật độ tiếp xúc gia đình thường xuyên hơn so với mô hình hạt nhân phương Tây, và vai trò của gia đình mở rộng (ông bà, cô dì chú bác) trong nuôi dạy. Thách thức gồm xu hướng cha mẹ ít giao tiếp cảm xúc với con — thiên về kiểm soát thành tích học tập — và tình trạng nhiều cha mẹ đi làm xa ở khu vực nông thôn dẫn đến giảm tiếp xúc trực tiếp.'),

    ('H3', '1.1.5.4. Hỗ trợ từ bạn bè'),

    ('P', 'Quan hệ với bạn đồng đẳng đóng vai trò ngày càng tăng trong vị thành niên — một mô hình phát triển kinh điển của Erikson. Hỗ trợ từ bạn bè bao gồm chia sẻ cảm xúc, hỗ trợ thực tế khi gặp khó khăn, và cảm giác chấp nhận trong nhóm. Đây là yếu tố bảo vệ có cơ chế tương đối khác với hỗ trợ cha mẹ — gắn với phát triển bản sắc và năng lực xã hội ngoài gia đình.'),

    ('P', 'Nghiên cứu của Ngô Anh Vinh và cộng sự (2024) trên 845 học sinh dân tộc thiểu số nội trú Lạng Sơn xác nhận chất lượng quan hệ bạn bè kém có liên hệ thuận với điểm lo âu, stress và trầm cảm, đồng thời số trải nghiệm bất lợi thời thơ ấu (ACEs) có liên hệ thuận với điểm lo âu (hệ số 0,28). Phạm Thị Ngọc và cộng sự (2024) tại Vĩnh Bảo, Hải Phòng ghi nhận không hòa đồng với bạn có tỷ số chênh đã hiệu chỉnh AOR = 2,25 với rối loạn lo âu — đặc biệt cao khi xét cùng yếu tố bắt nạt học đường.'),

    ('P', 'Vai trò của hỗ trợ bạn bè tại Việt Nam đang được nghiên cứu nhiều hơn trong những năm gần đây, song vẫn thiếu các nghiên cứu sử dụng thang đo chuyên biệt cho hỗ trợ xã hội từ bạn bè (như Multidimensional Scale of Perceived Social Support — MSPSS) trên mẫu học sinh trung học cơ sở. Đây là một khoảng trống về công cụ tương tự như với gắn bó trường học và hỗ trợ cha mẹ.'),

    ('H3', '1.1.5.5. Biện pháp ứng phó với rối loạn lo âu'),

    ('P', 'Biện pháp ứng phó (coping strategies) là cách thức cá nhân phản ứng và quản lý căng thẳng — khái niệm được Lazarus và Folkman (1984) đặt nền tảng. Lazarus và Folkman phân biệt hai dạng cốt lõi: ứng phó tập trung vào vấn đề (problem-focused) — chủ động giải quyết tình huống gây căng thẳng — và ứng phó tập trung vào cảm xúc (emotion-focused) — điều tiết phản ứng cảm xúc trước tình huống. Trong các nghiên cứu hiện đại, biện pháp ứng phó được tinh thêm thành phân biệt giữa adaptive (chủ động, hướng tới giải quyết hoặc điều tiết hiệu quả) và maladaptive (né tránh, kìm nén cảm xúc, phủ nhận).'),

    ('P', 'Phân tích tổng hợp của Compas và cộng sự (2017) trên 212 nghiên cứu với 80.850 trẻ em — vị thành niên là bằng chứng định lượng quan trọng nhất về vai trò của biện pháp ứng phó. Kết quả xác nhận ứng phó tập trung vào vấn đề và đánh giá lại nhận thức (cognitive reappraisal) — hai chiến lược adaptive — có liên hệ ngược chiều và bền vững với triệu chứng lo âu và trầm cảm. Ngược lại, đối phó né tránh (avoidance), kìm nén cảm xúc (suppression) và phủ nhận (denial) — ba chiến lược maladaptive — có liên hệ thuận chiều với triệu chứng. Phát hiện này hỗ trợ luận điểm rằng biện pháp ứng phó nên được xếp vào nhóm yếu tố bảo vệ, nhưng với điều kiện làm rõ chiến lược cụ thể: chiến lược adaptive bảo vệ, chiến lược maladaptive là yếu tố nguy cơ.'),

    ('P', 'Tại Việt Nam, các nghiên cứu về biện pháp ứng phó của học sinh trung học cơ sở còn rất ít. Khảo sát của Phạm Thị Thu Hoa và cộng sự (2024) là một trong những công trình hiếm có đề cập cụ thể đến chiến lược ứng phó của học sinh khi đối mặt với áp lực học tập và lo âu trong giai đoạn COVID-19. Các phỏng vấn định tính của tác giả cùng các nghiên cứu khác ghi nhận một số chiến lược học sinh Việt Nam thường sử dụng gồm: tự tạo động lực qua hoạt động lành mạnh (chơi thể thao, viết nhật ký), tâm sự với cha mẹ hoặc bạn thân, và tổ chức thời gian biểu hợp lý. Tuy nhiên, có tỷ lệ đáng kể học sinh báo cáo sử dụng các chiến lược maladaptive — đặc biệt là tăng thời lượng sử dụng điện thoại như hình thức né tránh thực tại. Đây là phát hiện đáng lưu ý vì gắn liền yếu tố ứng phó maladaptive với yếu tố nguy cơ nghiện smartphone đã nêu ở mục 1.1.4.'),

    ('P', 'Trong luận án này, biện pháp ứng phó được xếp vào nhóm yếu tố bảo vệ ở cấp độ phân loại lý thuyết, với cách trình bày làm rõ tính hai chiều: thang đo Brief COPE phân tách thành hai tiểu thang adaptive và maladaptive; phân tích thống kê báo cáo hệ số ảnh hưởng cho từng chiều riêng biệt. Cách trình bày này vừa giữ được khung lý thuyết kinh điển về ứng phó như yếu tố bảo vệ, vừa cho phép kiểm định thực nghiệm chiều hiệu ứng cụ thể — đáp ứng cả góc độ lý luận và đòi hỏi về tính thực nghiệm chặt chẽ.'),

    ('H3', '1.1.5.6. Mạng lưới yếu tố bảo vệ và hàm ý can thiệp'),

    ('P', 'Năm nhóm yếu tố bảo vệ — lòng tự trọng, gắn bó trường học, hỗ trợ cha mẹ, hỗ trợ bạn bè, biện pháp ứng phó adaptive — không hoạt động riêng lẻ mà tạo thành một mạng lưới có tương tác phức tạp. Lòng tự trọng cao gắn liền với khả năng xây dựng quan hệ tích cực hơn — cả với cha mẹ, bạn bè, lẫn trong môi trường trường học. Hỗ trợ cha mẹ tạo nền tảng cho việc học các chiến lược ứng phó adaptive. Gắn bó trường học cung cấp môi trường thực hành các kỹ năng ứng phó. Cấu trúc đan xen này có hàm ý quan trọng cho can thiệp: thay vì tập trung vào một yếu tố bảo vệ duy nhất, các chương trình hiệu quả thường nhắm tới đồng thời nhiều yếu tố — như mô hình FRIENDS phát triển từ công trình Barrett, Dadds, Rapee (1996), tích hợp huấn luyện kỹ năng ứng phó cho cá nhân, tăng cường hỗ trợ cha mẹ qua phiên gia đình, và đặt trong bối cảnh trường học để củng cố gắn bó với cộng đồng học sinh.'),

    ('P', 'Đối với học sinh trung học cơ sở Việt Nam, đặc thù văn hóa cộng đồng — gia đình mở rộng, mạng lưới quan hệ xã hội mật thiết — vừa là cơ hội vừa là thách thức khi thiết kế can thiệp dựa vào yếu tố bảo vệ. Cơ hội nằm ở việc dễ huy động sự tham gia của cha mẹ và người thân trong các chương trình can thiệp; thách thức nằm ở kỳ thị xã hội đối với rối loạn tâm thần khiến nhiều gia đình ngại tiếp cận dịch vụ chuyên môn. Việc thiết kế các chương trình tăng cường yếu tố bảo vệ ở cấp phổ quát — tích hợp vào hoạt động giáo dục trải nghiệm hoặc môn giáo dục công dân — có thể là cách giảm rào cản tiếp cận, song cần được kiểm định thực nghiệm trên mẫu Việt Nam.'),

    ('P', 'Khoảng trống nghiên cứu lớn nhất về yếu tố bảo vệ tại Việt Nam là sự thiếu hụt các thiết kế nghiên cứu đo lường đồng thời nhiều yếu tố bảo vệ trong cùng một mẫu, kèm theo phân tích tương tác giữa các yếu tố. Hiện nay, các nghiên cứu Việt Nam thường chỉ tập trung vào một yếu tố tại một thời điểm — hoặc lòng tự trọng, hoặc hỗ trợ xã hội, hoặc ứng phó — dẫn đến khó hình dung được cấu trúc tổng thể của mạng lưới bảo vệ. Việc xây dựng các nghiên cứu đa biến tích hợp năm nhóm yếu tố bảo vệ và phân tích vai trò trung gian, điều tiết giữa chúng là hướng nghiên cứu ưu tiên trong giai đoạn 2026-2030.'),
]

# ============================================================
# 6. CAN THIEP (TOM TAT + REF BAI 2)
# ============================================================
SEC_CT = [
    ('H3', '1.1.6. Can thiệp rối loạn lo âu ở học sinh trung học cơ sở'),

    ('P', 'Phân tích chi tiết về các nghiên cứu can thiệp được tác giả trình bày trong Bài 2 — Khoảng trống can thiệp rối loạn lo âu ở học sinh trung học cơ sở (đính kèm luận án). Bài này hệ thống hóa 21 nghiên cứu can thiệp giai đoạn 2015-2026 theo ba kênh — lâm sàng, trường học, nền tảng số — trong khung sức khỏe tâm thần cộng đồng ba tầng (phổ quát, chọn lọc, chỉ định) của Mrazek và Haggerty (1994). Tổng quan này chỉ tóm tắt ba kênh và năm khoảng trống chính ở Việt Nam.'),

    ('P', 'Kênh thứ nhất — can thiệp lâm sàng — chủ yếu áp dụng liệu pháp nhận thức — hành vi (CBT) cá nhân hoặc nhóm, thực hiện bởi nhà tâm lý lâm sàng. Đây là kênh có chất lượng chuyên môn cao nhất và phù hợp cho học sinh có triệu chứng nặng hoặc rối loạn đồng diễn. Bằng chứng định lượng đến từ phân tích mạng lưới của Liu và cộng sự (2025) trên 52 thử nghiệm lâm sàng ngẫu nhiên ở bệnh nhân rối loạn lo âu lan tỏa (chủ yếu người trưởng thành) cùng phân tích mạng lưới của Xian và cộng sự (2024) trên 30 thử nghiệm cho rối loạn lo âu xã hội ở trẻ em — vị thành niên. Cả hai đều xếp CBT cá nhân và CBT nhóm ở vị trí hiệu quả cao nhất trong số các hình thức cung cấp. Tại Việt Nam, kênh lâm sàng có khả năng tiếp cận thấp do thiếu nhân lực chuyên khoa và chi phí cao.'),

    ('P', 'Kênh thứ hai — can thiệp tại trường học — có tiềm năng tiếp cận lớn nhất do trường học là nơi học sinh tới hằng ngày, đồng thời giảm rào cản kỳ thị và chi phí. Bằng chứng tổng hợp đến từ phân tích tổng hợp của Cai và cộng sự (2025) trên 38 thử nghiệm về chương trình tăng cường khả năng phục hồi tại trường (hiệu số trung bình chuẩn hóa SMD = 0,17), và đánh giá hệ thống của Jagiello và cộng sự (2025) trên 31 nghiên cứu can thiệp áp lực học tập từ 13 quốc gia. Tại Việt Nam, chương trình Happy House do Tran và cộng sự (2023) thử nghiệm trong khuôn khổ hợp tác Việt — Úc trên 1.084 học sinh trung học phổ thông tại Hà Nội là một trong số ít nghiên cứu can thiệp tại trường được công bố quốc tế, song chưa có chương trình CBT bản địa được kiểm định cho học sinh trung học cơ sở.'),

    ('P', 'Kênh thứ ba — can thiệp qua nền tảng số — đang phát triển nhanh nhất, đặc biệt trong và sau đại dịch COVID-19. Phân tích tổng hợp của Walder và cộng sự (2025) trên 21 thử nghiệm lâm sàng ngẫu nhiên về can thiệp số cho rối loạn lo âu xã hội ở trẻ em, vị thành niên và thanh niên trẻ báo cáo hiệu ứng tổng hợp g = 0,508; can thiệp số có hướng dẫn đạt g = 0,825 — cao hơn rõ rệt so với không hướng dẫn (g = 0,27). Thử nghiệm ứng dụng Maya của Bress và cộng sự (2024) trên 59 thanh niên 18-25 tuổi với CBT tự hướng dẫn ghi nhận kích thước hiệu ứng rất lớn trên các thang đo lo âu xã hội. Tại Việt Nam, chưa có nền tảng CBT số tiếng Việt nào được kiểm định cho học sinh trung học cơ sở.'),

    ('P', 'Bài 2 đề xuất khung tích hợp ba kênh × ba tầng cho Việt Nam, cùng mô hình chăm sóc theo bậc (stepped care) dựa trên nguyên lý của Bower và Gilbody (2005). Năm khoảng trống nghiên cứu chính được nhận diện gồm: thiếu thử nghiệm lâm sàng ngẫu nhiên đa trung tâm trên học sinh trung học cơ sở Việt Nam, thiếu chương trình CBT trường học bản địa phù hợp với chương trình giáo dục phổ thông 2018, thiếu nền tảng CBT số tiếng Việt, thiếu nghiên cứu thiết kế và đo lường kết cục dài hạn, và thiếu công cụ sàng lọc — đo lường chuẩn hóa tiếng Việt. Luận án này — với phần thực trạng và phần đề xuất khung chương trình tập huấn phòng ngừa ở Chương 3, mục 3.7 — đóng góp một bước vào việc thu hẹp các khoảng trống trên.'),

    ('P', 'Mở rộng phân tích về kênh can thiệp lâm sàng, hai giao thức CBT nền tảng được tham chiếu rộng rãi trong y văn cho trẻ em — vị thành niên là Coping Cat của Kendall (1994) tại Hoa Kỳ và chương trình can thiệp gia đình của Barrett, Dadds, Rapee (1996) tại Úc. Coping Cat có cấu trúc 16 buổi chia làm hai pha: 8 buổi đầu tập trung vào dạy kỹ năng (nhận diện cảm xúc, kỹ thuật thư giãn, tái cấu trúc nhận thức, lập kế hoạch ứng phó), 8 buổi sau tập trung vào thực hành tiếp xúc dần với các tình huống gây lo âu. Mô hình của Barrett và cộng sự bổ sung thành phần làm việc với cha mẹ — phiên gia đình — vào giao thức CBT cá nhân, ghi nhận nhóm có cha mẹ tham gia đạt tỷ lệ không còn chẩn đoán cao hơn nhóm CBT đơn thuần (84% so với 57%) sau 12 tháng theo dõi. Cả hai mô hình đã được dịch và bản địa hóa tại hơn 15 quốc gia, đặt nền tảng cho hầu hết các giao thức CBT cho rối loạn lo âu trẻ em — vị thành niên hiện nay.'),

    ('P', 'Tổng quan hệ thống của Praptomojati và cộng sự (2024) trên các phiên bản CBT thích nghi văn hóa cho rối loạn lo âu tại Đông Nam Á đưa ra ba khuyến nghị quan trọng cho việc bản địa hóa CBT tại khu vực: tích hợp tường minh các yếu tố tôn giáo và tín ngưỡng vào nội dung can thiệp, mở rộng phạm vi "gia đình" để bao gồm ông bà và họ hàng (gia đình mở rộng), và giải quyết kỳ thị xã hội đối với "bệnh tâm thần" qua giáo dục cộng đồng đồng thời với can thiệp cá nhân. Áp dụng vào bối cảnh Việt Nam, ba khuyến nghị này có ý nghĩa thực tế cao: vai trò của tín ngưỡng dân gian trong nhận thức về sức khỏe tâm thần, sự ảnh hưởng của ông bà trong nuôi dạy con, và mức độ kỳ thị còn lớn đối với chủ đề tâm thần đều là những đặc thù cần được phản ánh trong giao thức can thiệp.'),

    ('P', 'Đối với kênh can thiệp tại trường học, hai mô hình chương trình có giá trị tham khảo cao là Journey of the Brave của Urao và cộng sự tại Nhật Bản (2018, 2022) và Early Adolescent Coping Power của Bradshaw và cộng sự (2025) tại Hoa Kỳ. Journey of the Brave được thiết kế cho học sinh cuối tiểu học — đầu trung học cơ sở (10-11 tuổi); phiên bản gốc 2018 gồm 10 buổi × 45 phút, phiên bản 2022 rút ngắn thành 14 buổi × 20 phút hoạt động ngắn lồng ghép vào chương trình môn học chính khóa. Việc rút ngắn mỗi buổi từ 45 phút xuống 20 phút trong bản 2022 là một thay đổi thiết kế đáng chú ý — tận dụng được khe giờ ngắn giữa các tiết học chính khóa, qua đó giảm gánh nặng cho thời gian biểu của trường. Mô hình "buổi ngắn lồng ghép" này có giá trị tham khảo cao cho thiết kế chương trình tại Việt Nam, nơi quỹ thời gian dành cho hoạt động tâm lý ngoài giờ học rất hạn chế.'),

    ('P', 'Early Adolescent Coping Power do Bradshaw và cộng sự thử nghiệm trên 709 học sinh lớp 7 tại 40 trường trung học cơ sở Hoa Kỳ qua thiết kế thử nghiệm lâm sàng ngẫu nhiên cụm — đây là một trong những thử nghiệm có quy mô lớn và thiết kế chặt chẽ nhất về can thiệp CBT trường học cho lứa tuổi trung học cơ sở. Chương trình gồm 25 buổi với học sinh và 12 buổi với cha mẹ. Theo dõi đến cuối lớp 8 cho thấy nhóm can thiệp có cải thiện đáng kể các vấn đề ngoại hiện do giáo viên đánh giá, đồng thời ghi nhận hiệu quả cao hơn ở học sinh nữ. Mặc dù chương trình gốc nhắm tới học sinh có hành vi gây hấn, các thành phần CBT cốt lõi của nó có thể được bản địa hóa cho mục tiêu phòng ngừa lo âu.'),

    ('P', 'Phân tích tổng hợp lớn của Cai và cộng sự (2025) trên 38 thử nghiệm lâm sàng ngẫu nhiên (21 thử nghiệm trong phân tích định lượng) về các chương trình tăng cường khả năng phục hồi tâm lý tại trường báo cáo hiệu ứng tổng hợp khá nhỏ với hiệu số trung bình chuẩn hóa SMD = 0,17 (khoảng tin cậy 95% 0,06-0,29). Khi phân nhóm theo loại chương trình, các chương trình dựa trên chánh niệm cho hiệu ứng cao nhất (SMD = 0,57), tiếp đến là các chương trình lấy hoạt động thể thao làm trung tâm (SMD = 0,41). Mặc dù hiệu ứng tổng hợp nhỏ, các tác giả nhấn mạnh giá trị của can thiệp phổ quát quy mô lớn không qua sàng lọc — đặc biệt khi được tích hợp vào hoạt động trải nghiệm hoặc môn Giáo dục công dân; năng lực phục hồi được củng cố là một cấu trúc bảo vệ có liên quan đến việc giảm nguy cơ rối loạn lo âu. Phát hiện này gợi ý mô hình hai tầng cho Việt Nam: tầng phổ quát (4-6 buổi tích hợp môn học chính khóa, tập trung vào kỹ năng nhận diện cảm xúc) và tầng có chọn lọc (8-12 buổi cho học sinh được sàng lọc có triệu chứng cận lâm sàng).'),

    ('P', 'Đánh giá hệ thống của Jagiello và cộng sự (2025) trên 31 nghiên cứu can thiệp áp lực học tập tại trường từ 13 quốc gia là tài liệu tham chiếu cho việc thiết kế chương trình tập trung vào yếu tố nguy cơ hàng đầu của Việt Nam — áp lực học. Kết quả tổng hợp cho thấy liệu pháp nhận thức — hành vi là can thiệp có bằng chứng mạnh nhất; cả tiếp cận phổ quát lẫn tiếp cận có đối tượng đều có hiệu quả. Phần lớn chương trình hiệu quả được thực hiện bởi nhà tâm lý chuyên nghiệp, dù một số ít chương trình do giáo viên dẫn dắt cũng đạt hiệu quả khi có đào tạo và giám sát chuyên môn — phát hiện này có ý nghĩa đặc biệt cho điều kiện Việt Nam khi nguồn nhân lực tâm lý lâm sàng còn hạn chế.'),

    ('P', 'Tại Trung Quốc, một thử nghiệm pilot có ý nghĩa tham khảo là chương trình Power Up — CBTD do He và cộng sự (2026) công bố trên Journal of Affective Disorders, đánh giá một chương trình CBT trường học ngắn cho học sinh có triệu chứng trầm cảm. Chương trình cải thiện triệu chứng trầm cảm có ý nghĩa thống kê, trong khi triệu chứng lo âu có xu hướng giảm nhưng khác biệt giữa hai nhóm chưa đạt ý nghĩa thống kê. Phát hiện này cho thấy hiệu quả lan tỏa từ can thiệp tập trung vào trầm cảm sang lo âu — một mô hình "transdiagnostic" có tiềm năng cho thiết kế can thiệp tích hợp.'),

    ('P', 'Đối với kênh can thiệp qua nền tảng số, năm 2020-2026 chứng kiến sự phát triển bùng nổ của các ứng dụng và nền tảng internet — bao gồm cả các ứng dụng độc lập, các chương trình tích hợp vào hệ thống chăm sóc y tế quốc gia, và các nền tảng đồng thiết kế cùng vị thành niên. Phân tích tổng hợp của Walder và cộng sự (2025) trên 21 thử nghiệm lâm sàng ngẫu nhiên về can thiệp số cho rối loạn lo âu xã hội ở trẻ em, vị thành niên và thanh niên trẻ báo cáo hiệu ứng tổng hợp g = 0,508 (khoảng tin cậy 95% 0,31-0,71). Khi phân nhóm theo mức độ hỗ trợ, các can thiệp số có hướng dẫn đạt hiệu ứng g = 0,825, cao hơn rõ rệt so với các can thiệp không hướng dẫn (g = 0,27) — cho thấy thành phần hỗ trợ chuyên môn, dù tối thiểu, vẫn đóng vai trò quan trọng đối với hiệu quả của can thiệp số.'),

    ('P', 'Hai thử nghiệm có ảnh hưởng lớn trong lĩnh vực này là nghiên cứu của Matsumoto và cộng sự (2024) tại Nhật Bản và Bress và cộng sự (2024) tại Hoa Kỳ. Matsumoto đánh giá một chương trình CBT qua internet không hướng dẫn trên điện thoại cho 77 vị thành niên và thanh niên trẻ Nhật Bản (15-25 tuổi) có rối loạn lo âu xã hội dưới ngưỡng, báo cáo hiệu ứng g = 0,66 sau 10 tuần can thiệp — con số đáng chú ý vì can thiệp gần như không có sự tham gia trực tiếp của chuyên gia. Bress và cộng sự đánh giá ứng dụng Maya — một nền tảng CBT tự hướng dẫn 12 phiên trên điện thoại — trên 59 thanh niên 18-25 tuổi với rối loạn lo âu (lo âu tổng quát 56%, lo âu xã hội 41%), ghi nhận hiệu ứng kích thước rất lớn trên các thang đo phụ (Cohen d = 0,93-1,07). Mặc dù hai mẫu này lớn hơn lứa tuổi trung học cơ sở, kết quả gợi ý mạnh rằng CBT số được thiết kế chu đáo có thể đạt hiệu quả đáng kể và cần được điều chỉnh cho lứa tuổi nhỏ hơn.'),

    ('P', 'Một hướng phát triển đáng chú ý là quy trình đồng thiết kế (co-design) ứng dụng cùng vị thành niên. Li và cộng sự (2022) khi xây dựng ứng dụng ClearlyMe cho vị thành niên Úc đã dành hơn một năm cho giai đoạn đồng thiết kế với người dùng cuối trước khi phát hành công khai. Quá trình này giúp các thành phần CBT vốn có nguồn gốc lâm sàng được "dịch" sang ngôn ngữ, hình ảnh và bối cảnh tương tác phù hợp với vị thành niên. Đối với Việt Nam, một dự án phát triển nền tảng CBT số tiếng Việt cần dành ít nhất 6-9 tháng cho giai đoạn đồng thiết kế trước khi bắt đầu thử nghiệm chính thức.'),

    ('P', 'Tại Việt Nam, một số nỗ lực ban đầu về can thiệp tâm lý cho học sinh đã được công bố nhưng phần lớn ở quy mô nhỏ. Chương trình Happy House của Tran và cộng sự (2023) thuộc hợp tác Việt — Úc đã đánh giá một can thiệp nâng cao sức khỏe tâm thần phổ quát theo mô hình thử nghiệm hai nhánh có đối chứng trên 1.084 học sinh trung học phổ thông tại Hà Nội — đây là một trong số rất ít công trình của Việt Nam được công bố trên tạp chí quốc tế (Cambridge Prisms: Global Mental Health). Tuy nhiên, các thử nghiệm lâm sàng ngẫu nhiên đa trung tâm trên mẫu học sinh trung học cơ sở vẫn chưa được triển khai. Luận án tiến sĩ của Trần Nguyễn Ngọc (2018) tại Đại học Y Hà Nội về liệu pháp thư giãn luyện tập trong điều trị rối loạn lo âu lan tỏa cung cấp dữ liệu về một thành phần CBT, nhưng trên mẫu người trưởng thành.'),

    ('P', 'Trên cơ sở khung tích hợp ba kênh × ba tầng được Bài 2 trình bày chi tiết, mô hình can thiệp khả thi cho Việt Nam giai đoạn 2026-2030 có thể được tổ chức theo nguyên lý chăm sóc theo bậc (stepped care) của Bower và Gilbody (2005). Bậc 1 (mức độ cận lâm sàng nhẹ): can thiệp số tự hướng dẫn hoặc tài liệu tự giúp; nếu không cải thiện sau 4-6 tuần, chuyển lên bậc 2. Bậc 2 (mức độ cận lâm sàng vừa): CBT nhóm tại trường do giáo viên tâm lý dẫn dắt, hoặc can thiệp số có hướng dẫn; nếu không cải thiện hoặc triệu chứng nặng lên, chuyển lên bậc 3. Bậc 3 (mức độ lâm sàng): CBT cá nhân với nhà tâm lý lâm sàng, kết hợp tâm thần khoa khi cần thiết. Mô hình này phù hợp với nguồn lực hạn chế của Việt Nam — chỉ dành can thiệp chuyên sâu cho những trường hợp thực sự cần — đồng thời tạo cơ chế tiếp cận rõ ràng từ phổ quát đến chuyên khoa.'),
]

# ============================================================
# 7. NHAN XET KHOANG TRONG VN
# ============================================================
SEC_NX = [
    ('H3', '1.1.7. Nhận xét chung và khoảng trống nghiên cứu tại Việt Nam'),

    ('P', 'Tổng hợp các phát hiện từ sáu tiểu mục trên cho thấy bức tranh nghiên cứu rối loạn lo âu ở học sinh trung học cơ sở Việt Nam có những điểm mạnh và sáu khoảng trống chính.'),

    ('P', 'Điểm mạnh nổi bật nhất là sự xuất hiện của một số nghiên cứu đại diện quốc gia và nghiên cứu đa trung tâm trong khoảng 5 năm gần đây — V-NAMHS (Viện Xã hội học và cộng sự, 2022) trên 5.996 cặp, Phạm Thị Thu Hoa và cộng sự (2024) trên 3.910 học sinh trung học phổ thông Hà Nội, Hoàng Trung Học và Nguyễn Thùy Dung (2025) trên gần 8.500 thanh thiếu niên ở 6 tỉnh, Trúc Thanh Thái và cộng sự (2026) trên 2.631 học sinh tại Thành phố Hồ Chí Minh. Nhóm các nghiên cứu này cung cấp ước tính tỷ lệ ở các điểm dữ liệu khác nhau và đặt nền tảng cho việc xây dựng cơ sở dữ liệu dịch tễ về sức khỏe tâm thần học đường.'),

    ('P', 'Khoảng trống thứ nhất là về công cụ đo lường. Hiện chưa có bộ thang đo lo âu cho trẻ em — vị thành niên được thẩm định tâm trắc toàn diện trên dân số Việt Nam, bao gồm độ tin cậy, độ hiệu lực hội tụ và phân biệt, ngưỡng cắt riêng cho dân số Việt Nam. Phần lớn nghiên cứu sử dụng các bản dịch tiếng Việt chưa qua quy trình thẩm định đầy đủ, dẫn đến chênh lệch lớn về tỷ lệ giữa các nghiên cứu cùng đối tượng.'),

    ('P', 'Khoảng trống thứ hai là về phạm vi rối loạn được khảo sát. Đa số nghiên cứu tập trung vào rối loạn lo âu lan tỏa hoặc lo âu tổng hợp; rối loạn lo âu xã hội và rối loạn lo âu chia ly hầu như chưa có nghiên cứu chuyên biệt ở học sinh trung học cơ sở Việt Nam, dù đây là hai dạng quan trọng ở lứa tuổi đầu vị thành niên.'),

    ('P', 'Khoảng trống thứ ba là về yếu tố bảo vệ. Trong khi yếu tố nguy cơ đã được nghiên cứu khá đầy đủ trong khoảng 5 năm gần đây — đặc biệt là áp lực học tập, nghiện điện thoại và bắt nạt — thì các yếu tố bảo vệ (lòng tự trọng, gắn bó trường, hỗ trợ cha mẹ và bạn bè, biện pháp ứng phó adaptive) còn ít được khảo sát đồng thời và tích hợp trong cùng một thiết kế nghiên cứu. Việc thiếu thang đo chuẩn hóa cho gắn bó trường học và hỗ trợ xã hội là một nguyên nhân khách quan.'),

    ('P', 'Khoảng trống thứ tư là về thiết kế nghiên cứu. Phần lớn nghiên cứu Việt Nam hiện có sử dụng thiết kế cắt ngang đơn lẻ, không cho phép phân tích nguyên nhân — kết quả. Số nghiên cứu dọc còn rất ít (Trần Thảo Vi và cộng sự, 2024 là một ngoại lệ) và chưa có thử nghiệm lâm sàng ngẫu nhiên đa trung tâm trên học sinh trung học cơ sở. Khoảng trống này được phân tích chi tiết hơn ở Bài 2 đính kèm.'),

    ('P', 'Khoảng trống thứ năm là về khu vực địa lý và đặc thù vùng miền. Nhiều nghiên cứu tập trung ở Hà Nội và Thành phố Hồ Chí Minh; mẫu nghiên cứu ở khu vực nông thôn, miền núi và dân tộc thiểu số còn ít, ngoại trừ nghiên cứu của Ngô Anh Vinh và cộng sự (2024) tại Lạng Sơn và Lê Minh và cộng sự (2025) tại An Giang. Đặc thù vùng miền có thể ảnh hưởng cả đến tỷ lệ phổ biến lẫn cơ chế tác động của các yếu tố ảnh hưởng — chẳng hạn vai trò của hỗ trợ cha mẹ ở khu vực có nhiều cha mẹ đi làm xa khác với khu vực gia đình hạt nhân tại đô thị.'),

    ('P', 'Khoảng trống thứ sáu là về can thiệp. Như đã phân tích chi tiết ở Bài 2, các chương trình can thiệp CBT bản địa được kiểm định trên học sinh trung học cơ sở Việt Nam còn vắng bóng, ở cả ba kênh lâm sàng, trường học và số. Đây là khoảng trống có tính chiến lược nhất vì nó là điểm chuyển từ tri thức về nguy cơ sang hành động giảm gánh nặng lo âu cho lứa tuổi này.'),

    ('P', 'Luận án này, với phần thực trạng trên 1.352 học sinh trung học cơ sở Hà Nội cùng phần đề xuất khung chương trình tập huấn phòng ngừa, đóng góp một bước cụ thể vào việc thu hẹp các khoảng trống trên — đặc biệt là khoảng trống về tích hợp đồng thời yếu tố nguy cơ và yếu tố bảo vệ trong cùng một thiết kế (khoảng trống thứ ba) và bước đầu đưa ra khung chương trình phòng ngừa (khoảng trống thứ sáu). Các khoảng trống còn lại — về công cụ đo, phạm vi rối loạn, thiết kế dọc và phân bố vùng miền — là hướng nghiên cứu ưu tiên cho giai đoạn 2026-2030, được cụ thể hóa trong phần Khuyến nghị cuối luận án và trong hai bài tổng quan chuyên sâu đính kèm.'),

    ('P', 'Đặt trong bối cảnh quốc tế, nghiên cứu này có ba điểm khác biệt phương pháp luận đáng được nêu rõ. Thứ nhất, mẫu nghiên cứu được lấy từ hai trường trung học cơ sở Hà Nội (Nhật Tân và Tây Mỗ) đại diện cho hai khu vực có đặc thù xã hội — kinh tế khác nhau trong cùng đô thị: khu vực gần trung tâm hơn (Nhật Tân) và khu vực ngoại thành đang đô thị hóa nhanh (Tây Mỗ). Cấu trúc này cho phép phân tích so sánh nội bộ đô thị, một góc nhìn ít được khai thác trong các nghiên cứu Việt Nam vốn thường gộp toàn bộ học sinh đô thị thành một nhóm. Thứ hai, thiết kế nghiên cứu khảo sát đồng thời cả yếu tố nguy cơ (áp lực học tập, nghiện điện thoại, bắt nạt, lòng tự trọng) và yếu tố bảo vệ (gắn bó trường học, hỗ trợ xã hội, biện pháp ứng phó) trên cùng mẫu — cho phép phân tích vai trò trung gian và điều tiết giữa các yếu tố. Thứ ba, nghiên cứu kết hợp phương pháp định lượng (khảo sát bảng hỏi trên 1.352 học sinh) với phương pháp định tính (phỏng vấn sâu 12 học sinh và 6 giáo viên chủ nhiệm) — mô hình kết hợp đem lại chiều sâu giải thích cho các quan sát định lượng.'),

    ('P', 'Một số giới hạn của nghiên cứu cần được ghi nhận để diễn giải kết quả phù hợp. Thứ nhất, thiết kế cắt ngang không cho phép quy kết nhân quả chắc chắn — chỉ có thể đo lường mối liên hệ ở một thời điểm. Thứ hai, mẫu giới hạn ở hai trường tại Hà Nội nên kết quả có thể không khái quát hóa được cho học sinh trung học cơ sở ở các vùng miền khác — đặc biệt là khu vực nông thôn, miền núi và dân tộc thiểu số. Thứ ba, thông tin về một số biến quan trọng (như rối loạn tâm thần ở cha mẹ, tiền sử y khoa) phụ thuộc vào tự báo cáo của học sinh và không được kiểm chứng qua hồ sơ y tế hoặc phỏng vấn cha mẹ. Thứ tư, công cụ đo được sử dụng — dù được lựa chọn dựa trên cơ sở thẩm định trước đó — chưa đạt mức chuẩn hóa toàn diện riêng cho dân số học sinh trung học cơ sở Việt Nam.'),

    ('P', 'Với những đóng góp và giới hạn nêu trên, luận án đặt trong logic của một chương trình nghiên cứu dài hạn về sức khỏe tâm thần học đường Việt Nam. Các nghiên cứu tiếp theo trong lĩnh vực này — đặc biệt từ nhóm tác giả và các nhóm nghiên cứu khác trong nước — nên ưu tiên: (i) nhân rộng thiết kế trên mẫu đa vùng miền; (ii) áp dụng thiết kế dọc với ít nhất hai đến ba thời điểm đo; (iii) sử dụng công cụ phân tách dạng rối loạn (RCADS, SCARED) thay vì thang tổng hợp (DASS, GAD-7) để có thể phân tích cấu trúc đồng diễn; (iv) thử nghiệm các giao thức can thiệp đã được bản địa hóa cho học sinh trung học cơ sở Việt Nam. Bốn ưu tiên này, cùng với các đề xuất cụ thể trong Bài 1 và Bài 2, vạch ra một lộ trình thực tế cho nghiên cứu sức khỏe tâm thần học sinh trung học cơ sở giai đoạn 2026-2030.'),
]

# ============================================================
# BUILD
# ============================================================
doc = doc_init()
for sec in [INTRO, SEC_TY_LE, SEC_MUC_DO, SEC_BIEU_HIEN, SEC_YTNC, SEC_YTBV, SEC_CT, SEC_NX]:
    render(doc, sec)

doc.save(OUT)

from docx import Document as D
d = D(OUT)
w = sum(len(p.text.split()) for p in d.paragraphs)
n_p = sum(1 for p in d.paragraphs if p.text.strip())
n_h2 = sum(1 for p in d.paragraphs if p.style.name == 'Heading 2')
n_h3 = sum(1 for p in d.paragraphs if p.style.name == 'Heading 3')
print(f"Da luu: {OUT}")
print(f"Tu: {w} (target 8000-10000)")
print(f"Doan: {n_p}, H2: {n_h2}, H3: {n_h3}")
print(f"Size: {os.path.getsize(OUT) // 1024}KB")
