# -*- coding: utf-8 -*-
"""Xoa text 'Nhan F9...' trong TOC field + scan kiem watermark khac.
Giu nguyen TOC field code (de F9 van sinh muc luc).
28/05/2026."""
import os, sys, io, shutil
os.environ['PYTHONIOENCODING'] = 'utf-8'
if hasattr(sys.stdout, 'buffer'):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

from docx import Document
from docx.oxml.ns import qn

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
FILE = os.path.join(ROOT, 'Luận án TS', '01_LuanAn_v3_1_FixCoping_28052026.docx')

# Backup
backup2 = FILE.replace('.docx', '_BEFORE_REMOVE_PLACEHOLDER.docx')
shutil.copy(FILE, backup2)
print(f"Backup: {backup2}")

d = Document(FILE)

# ============================================================
# 1. Find and remove placeholder text in TOC field
# ============================================================
print("\n[1] Removing TOC placeholder text...")
placeholder = 'Nhấn F9 hoặc chuột phải > Update Field để cập nhật Mục lục.'
removed_placeholders = 0

# Iterate through all w:t elements inside TOC field (between separate and end markers)
in_toc_field = False
field_depth = 0
for elem in d.element.body.iter():
    tag = elem.tag
    if tag == qn('w:fldChar'):
        ft = elem.get(qn('w:fldCharType'))
        if ft == 'begin':
            field_depth += 1
        elif ft == 'separate' and field_depth > 0:
            in_toc_field = True
        elif ft == 'end':
            in_toc_field = False
            if field_depth > 0:
                field_depth -= 1
    elif tag == qn('w:t') and in_toc_field:
        if elem.text and placeholder in elem.text:
            elem.text = ''
            removed_placeholders += 1
        elif elem.text and 'F9' in elem.text:
            # Catch any other variant
            elem.text = ''
            removed_placeholders += 1

print(f"  Removed {removed_placeholders} placeholder text(s)")


# ============================================================
# 2. Scan for ANY remaining "watermark"-like additions
# ============================================================
print("\n[2] Scanning for Claude-added watermarks...")
suspicious_terms = ['Claude', 'CLAUDE', 'Anthropic', 'watermark', 'Watermark',
                    'WaterMark', 'WATERMARK', 'placeholder', 'PLACEHOLDER',
                    '<<', '>>', 'TODO:', '[Draft]', '[DRAFT]',
                    'Generated by', 'Auto-generated']
found = []
for i, p in enumerate(d.paragraphs):
    for term in suspicious_terms:
        if term in p.text:
            found.append((i, term, p.text[:100]))
            break
# Also in headers/footers
for si, sec in enumerate(d.sections):
    for hf_name in ['header', 'footer']:
        hf = getattr(sec, hf_name)
        for p in hf.paragraphs:
            for term in suspicious_terms:
                if term in p.text:
                    found.append((f'sect{si+1}/{hf_name}', term, p.text[:100]))
                    break

if found:
    print(f"  Found {len(found)} suspicious items:")
    for loc, term, txt in found:
        print(f"    [{loc}] ({term!r}): {txt!r}")
else:
    print(f"  ✓ Khong tim thay tu khoa nghi van")


# ============================================================
# 3. Scan for w:pict elements (true watermarks via Word Insert > Watermark)
# ============================================================
print("\n[3] Scanning for w:pict watermark elements...")
pict_body = sum(1 for e in d.element.body.iter(qn('w:pict')))
pict_hf = 0
for sec in d.sections:
    for hf in [sec.header, sec.first_page_header, sec.even_page_header,
               sec.footer, sec.first_page_footer, sec.even_page_footer]:
        for e in hf._element.iter(qn('w:pict')):
            pict_hf += 1
print(f"  w:pict in body: {pict_body}")
print(f"  w:pict in headers/footers: {pict_hf}")
print(f"  (w:pict in body is usually OK — inline images. In header/footer = often watermark)")


# ============================================================
# 4. Save
# ============================================================
d.save(FILE)
print(f"\n[4] Saved: {FILE}")
print(f"  Size: {os.path.getsize(FILE)//1024} KB")


# ============================================================
# 5. Verify TOC field still exists
# ============================================================
print("\n[5] Verifying TOC field still intact...")
d2 = Document(FILE)
has_toc = False
for elem in d2.element.body.iter():
    if elem.tag == qn('w:instrText'):
        if elem.text and 'TOC' in elem.text:
            has_toc = True
            print(f"  ✓ TOC field code intact: {elem.text!r}")
            break
if not has_toc:
    print("  ✗ TOC field MISSING")

# Check paragraph 61 text
if 61 < len(d2.paragraphs):
    p61 = d2.paragraphs[61]
    print(f"  Para 61 text: {p61.text!r} (should be empty or near-empty)")
