# -*- coding: utf-8 -*-
"""Sửa phần ĐÁNH GIÁ NHANH: thay chữ không dấu → có dấu, cập nhật ảnh đã crop"""
import sys, io
try:
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
except: pass
from docx import Document
from docx.shared import RGBColor

# Map không dấu → có dấu
REPLACEMENTS = {
    'TOM TAT DANH GIA NHANH': 'TÓM TẮT ĐÁNH GIÁ NHANH',
    'Diem noi bat:': 'Điểm nổi bật:',
    'Han che:': 'Hạn chế:',
    'Huong cai thien:': 'Hướng cải thiện:',
    'Co mau lon': 'Cỡ mẫu lớn',
    'phuong phap hon hop': 'phương pháp hỗn hợp',
    'phong van sau': 'phỏng vấn sâu',
    'Ty le lo au': 'Tỷ lệ lo âu',
    'cao hon nhieu nuoc cung thoi diem': 'cao hơn nhiều nước cùng thời điểm',
    'Phat hien dinh tinh bo sung': 'Phát hiện định tính bổ sung',
    'ap luc thi cu': 'áp lực thi cử',
    'ky thi xa hoi': 'kỳ thị xã hội',
    'ky vong gia dinh': 'kỳ vọng gia đình',
    'Do tin cay thang do rat cao': 'Độ tin cậy thang đo rất cao',
    'Chi tai Ha Noi': 'Chỉ tại Hà Nội',
    'do thi': 'đô thị',
    'khong dai dien nong thon va mien nui': 'không đại diện nông thôn và miền núi',
    'Thoi diem khao sat trung COVID-19 lockdown': 'Thời điểm khảo sát trùng COVID-19 lockdown',
    'la sang loc': 'là sàng lọc',
    'khong phai chan doan': 'không phải chẩn đoán',
    'chi ghi nhan': 'chỉ ghi nhận',
    'theo DISC-5': 'theo DISC-5',
    'Phong van dinh tinh chi': 'Phỏng vấn định tính chỉ',
    'chua du tong quat hoa': 'chưa đủ tổng quát hóa',
    'Mo rong ra nong thon': 'Mở rộng ra nông thôn',
    'mien nui': 'miền núi',
    'dan toc thieu so': 'dân tộc thiểu số',
    'So sanh sang loc': 'So sánh sàng lọc',
    'voi chan doan': 'với chẩn đoán',
    'tren cung mau': 'trên cùng mẫu',
    'Nghien cuu doc theo doi thay doi lo au': 'Nghiên cứu dọc theo dõi thay đổi lo âu',
    'truoc-trong-sau COVID': 'trước-trong-sau COVID',
    'Danh gia vai tro trung gian cua giac ngu va mang xa hoi': 'Đánh giá vai trò trung gian của giấc ngủ và mạng xã hội',
    'Lancet Public Health': 'Lancet Public Health',
    'tap chi hang dau the gioi': 'tạp chí hàng đầu thế giới',
    'Du lieu GBD chuan hoa 30 nam': 'Dữ liệu GBD chuẩn hóa 30 năm',
    'quoc gia ASEAN': 'quốc gia ASEAN',
    'Nhom 10-14 tuoi chiu ganh nang cao nhat': 'Nhóm 10-14 tuổi chịu gánh nặng cao nhất',
    'tong DALYs': 'tổng DALYs',
    'trieu ca roi loan tam than': 'triệu ca rối loạn tâm thần',
    'tang 70% so voi 1990': 'tăng 70% so với 1990',
    'Du lieu GBD phu thuoc chat luong bao cao quoc gia': 'Dữ liệu GBD phụ thuộc chất lượng báo cáo quốc gia',
    'Khong phan tich rieng hoc sinh THCS/THPT': 'Không phân tích riêng học sinh THCS/THPT',
    'Ty le thap o Viet Nam': 'Tỷ lệ thấp ở Việt Nam',
    'co the phan anh thieu du lieu': 'có thể phản ánh thiếu dữ liệu',
    'Mo hinh DisMod-MR dua tren gia dinh phan bo': 'Mô hình DisMod-MR dựa trên giả định phân bố',
    'Can nghien cuu cap quoc gia': 'Cần nghiên cứu cấp quốc gia',
    'voi phuong phap chuan hoa tai tung nuoc ASEAN': 'với phương pháp chuẩn hóa tại từng nước ASEAN',
    'Phan tich rieng nhom hoc sinh': 'Phân tích riêng nhóm học sinh',
    'thay vi chi theo nhom tuoi': 'thay vì chỉ theo nhóm tuổi',
    'Bo sung du lieu tu Myanmar, Lao, Campuchia': 'Bổ sung dữ liệu từ Myanmar, Lào, Campuchia',
    'So sanh ty le GBD voi ket qua khao sat truc tiep': 'So sánh tỷ lệ GBD với kết quả khảo sát trực tiếp',
    'Tong quan he thong dau tien tap trung vao can thiep truong hoc tai LMIC': 'Tổng quan hệ thống đầu tiên tập trung vào can thiệp trường học tại LMIC',
    'Phat hien: can thiep hieu qua cho tram cam': 'Phát hiện: can thiệp hiệu quả cho trầm cảm',
    'nhung kem cho lo au': 'nhưng kém cho lo âu',
    'Danh gia GRADE cho thay chat luong bang chung rat thap': 'Đánh giá GRADE cho thấy chất lượng bằng chứng rất thấp',
    'Xac dinh khoang trong lon': 'Xác định khoảng trống lớn',
    'chua co RCT nao tu nuoc thu nhap thap': 'chưa có RCT nào từ nước thu nhập thấp',
    'Chi 6 RCTs dap ung tieu chi': 'Chỉ 6 RCTs đáp ứng tiêu chí',
    'so luong rat it': 'số lượng rất ít',
    'Khong co nghien cuu nao tu nuoc thu nhap thap': 'Không có nghiên cứu nào từ nước thu nhập thấp',
    'Thieu theo doi dai han': 'Thiếu theo dõi dài hạn',
    'thieu da dang phuong phap': 'thiếu đa dạng phương pháp',
    'RCT can thiep tai truong hoc Viet Nam': 'RCT can thiệp tại trường học Việt Nam',
    'Thu nghiem can thiep phi CBT': 'Thử nghiệm can thiệp phi CBT',
    'mindfulness, SEL, giao duc tam ly': 'mindfulness, SEL, giáo dục tâm lý',
    'Theo doi hieu qua dai han': 'Theo dõi hiệu quả dài hạn',
    'Danh gia chi phi-hieu qua cho boi canh LMIC': 'Đánh giá chi phí-hiệu quả cho bối cảnh LMIC',
    'Tong quan 61 bai bao': 'Tổng quan 61 bài báo',
    'bao quat nhieu yeu to': 'bao quát nhiều yếu tố',
    'hoc tap, mang xa hoi, gia dinh': 'học tập, mạng xã hội, gia đình',
    'VTN 13-18 tuoi co roi loan lo au': 'VTN 13-18 tuổi có rối loạn lo âu',
    'The he Z cao nhat 3 the he': 'Thế hệ Z cao nhất 3 thế hệ',
    'nghien cuu xac nhan tuong quan duong': 'nghiên cứu xác nhận tương quan dương',
    'giua ap luc hoc tap va SKTT kem': 'giữa áp lực học tập và SKTT kém',
    'De xuat can thiep da tang': 'Đề xuất can thiệp đa tầng',
    'lam sang + giao duc + cong dong': 'lâm sàng + giáo dục + cộng đồng',
    'Tong quan tuong thuat': 'Tổng quan tường thuật',
    'khong phai he thong': 'không phải hệ thống',
    'khong co phan tich tong hop': 'không có phân tích tổng hợp',
    'Du lieu chu yeu tu phuong Tay': 'Dữ liệu chủ yếu từ phương Tây',
    'thieu boi canh chau A, chau Phi': 'thiếu bối cảnh châu Á, châu Phi',
    'Khong danh gia chat luong tung nghien cuu duoc dua vao': 'Không đánh giá chất lượng từng nghiên cứu được đưa vào',
    'Thieu phan tich theo nhom tuoi cu the': 'Thiếu phân tích theo nhóm tuổi cụ thể',
    'THCS vs THPT': 'THCS vs THPT',
    'Tong quan he thong + meta-analysis voi tieu chi PRISMA': 'Tổng quan hệ thống + meta-analysis với tiêu chí PRISMA',
    'Bo sung nghien cuu tu chau A': 'Bổ sung nghiên cứu từ châu Á',
    'Viet Nam, Trung Quoc, Han Quoc': 'Việt Nam, Trung Quốc, Hàn Quốc',
    'Phan tich yeu to dac thu van hoa': 'Phân tích yếu tố đặc thù văn hóa',
    'hoc them': 'học thêm',
    'ky vong gia dinh kieu A Dong': 'kỳ vọng gia đình kiểu Á Đông',
    'Danh gia hieu qua can thiep theo tung yeu to nguy co': 'Đánh giá hiệu quả can thiệp theo từng yếu tố nguy cơ',
    'Khao sat dai dien quoc gia DAU TIEN': 'Khảo sát đại diện quốc gia ĐẦU TIÊN',
    'tai Viet Nam dung cong cu chan doan DISC-5/DSM-5': 'tại Việt Nam dùng công cụ chẩn đoán DISC-5/DSM-5',
    'VTN 10-17 tuoi tai 38 tinh': 'VTN 10-17 tuổi tại 38 tỉnh',
    'pham vi bao phu chua tung co': 'phạm vi bao phủ chưa từng có',
    'Phan biet ro van de SKTT': 'Phân biệt rõ vấn đề SKTT',
    'va roi loan tam than': 'và rối loạn tâm thần',
    'Phat hien khoang cach dich vu lon': 'Phát hiện khoảng cách dịch vụ lớn',
    'chi 8,4% co van de SKTT tiep can dich vu': 'chỉ 8,4% có vấn đề SKTT tiếp cận dịch vụ',
    'Du lieu thu thap 2021-2022': 'Dữ liệu thu thập 2021-2022',
    'co the chiu anh huong COVID-19': 'có thể chịu ảnh hưởng COVID-19',
    'DISC-5 chua duoc chuan hoa cho van hoa Viet Nam': 'DISC-5 chưa được chuẩn hóa cho văn hóa Việt Nam',
    'Thieu phan tich theo vung dia ly chi tiet': 'Thiếu phân tích theo vùng địa lý chi tiết',
    'Chi 6 roi loan duoc danh gia': 'Chỉ 6 rối loạn được đánh giá',
    'thieu OCD, roi loan an uong': 'thiếu OCD, rối loạn ăn uống',
    'V-NAMHS lan 2': 'V-NAMHS lần 2',
    'nghien cuu doc': 'nghiên cứu dọc',
    'de theo doi xu huong sau COVID': 'để theo dõi xu hướng sau COVID',
    'Chuan hoa DISC-5 cho boi canh van hoa Viet Nam': 'Chuẩn hóa DISC-5 cho bối cảnh văn hóa Việt Nam',
    'Phan tich chi tiet theo vung': 'Phân tích chi tiết theo vùng',
    'do thi, nong thon, mien nui, DTTS': 'đô thị, nông thôn, miền núi, DTTS',
    'RCT can thiep tai truong hoc dua tren ket qua V-NAMHS': 'RCT can thiệp tại trường học dựa trên kết quả V-NAMHS',
    # Red critique V-NAMHS
    'PHAN BIEN CHI TIET': 'PHẢN BIỆN CHI TIẾT',
    'Diem manh:': 'Điểm mạnh:',
    'Khao sat quoc gia dau tien voi DISC-5/DSM-5': 'Khảo sát quốc gia đầu tiên với DISC-5/DSM-5',
    'Phan biet van de SKTT': 'Phân biệt vấn đề SKTT',
    'va roi loan': 'và rối loạn',
    'giup hoach dinh chinh sach': 'giúp hoạch định chính sách',
    'Danh gia su dung dich vu': 'Đánh giá sử dụng dịch vụ',
    'cung cap bang chung khoang trong': 'cung cấp bằng chứng khoảng trống',
    'chua chuan hoa cho van hoa VN': 'chưa chuẩn hóa cho văn hóa VN',
    'bieu hien trieu chung co the khac phuong Tay': 'biểu hiện triệu chứng có thể khác phương Tây',
    'Thu thap du lieu 2021-2022 trung COVID-19': 'Thu thập dữ liệu 2021-2022 trùng COVID-19',
    'Chi 6/hang tram roi loan tam than duoc danh gia': 'Chỉ 6/hàng trăm rối loạn tâm thần được đánh giá',
    'Phu huynh la gatekeeper': 'Phụ huynh là gatekeeper',
    'chi 5,1% nhan ra con can giup do': 'chỉ 5,1% nhận ra con cần giúp đỡ',
    'Khoang trong nghien cuu (Gap):': 'Khoảng trống nghiên cứu (Gap):',
    'So sanh ty le V-NAMHS voi GSHS va DASS-21 tren cung mau': 'So sánh tỷ lệ V-NAMHS với GSHS và DASS-21 trên cùng mẫu',
    'Nghien cuu rao can tiep can dich vu SKTT o VTN Viet Nam': 'Nghiên cứu rào cản tiếp cận dịch vụ SKTT ở VTN Việt Nam',
    # Anderson
    'Theo thong ke hien tai': 'Theo thống kê hiện tại',
    'vi thanh nien tu 13-18 tuoi': 'vị thành niên từ 13-18 tuổi',
    'da hoac dang duoc chan doan roi loan lo au': 'đã hoặc đang được chẩn đoán rối loạn lo âu',
    'co trieu chung tram cam': 'có triệu chứng trầm cảm',
    'Lo au pho bien hon dang ke o The he Z': 'Lo âu phổ biến hơn đáng kể ở Thế hệ Z',
    'so voi bat ky the he nao trong ba the he gan day': 'so với bất kỳ thế hệ nào trong ba thế hệ gần đây',
}

files = [
    '02_Hoa_2024_Frontiers.docx',
    '03_GBD_ASEAN_2025_Lancet.docx',
    '04_Zhameden_2025_PLOSONE.docx',
    '05_Anderson_2025_Wiley.docx',
    '06_VNAMHS_2022.docx',
]

for fname in files:
    doc = Document(fname)
    count = 0
    for para in doc.paragraphs:
        for run in para.runs:
            original = run.text
            text = run.text
            for old, new in REPLACEMENTS.items():
                if old in text:
                    text = text.replace(old, new)
            if text != original:
                run.text = text
                count += 1
    doc.save(fname)
    sys.stderr.write(f'{fname}: {count} runs updated\n')
